-- Reviewed additive migration. Do not apply automatically.
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_profile varchar(30) DEFAULT 'PRACTITIONER' NOT NULL CHECK(access_profile IN('PRACTITIONER','RECEPTIONIST','MANAGER'));
CREATE TABLE IF NOT EXISTS locations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE cascade,name varchar(150) NOT NULL,address text NOT NULL,postcode varchar(20) NOT NULL,phone varchar(30),timezone varchar(100) NOT NULL,is_primary boolean DEFAULT false NOT NULL,is_active boolean DEFAULT true NOT NULL,created_at timestamptz DEFAULT now() NOT NULL,updated_at timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS locations_one_primary ON locations(tenant_id) WHERE is_primary;
INSERT INTO locations(tenant_id,name,address,postcode,timezone,is_primary) SELECT id,name,'Address not configured','Not configured',timezone,true FROM tenants ON CONFLICT DO NOTHING;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS location_id uuid REFERENCES locations(id) ON DELETE restrict;ALTER TABLE resources ADD COLUMN IF NOT EXISTS description text;ALTER TABLE resources ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true NOT NULL;
ALTER TABLE resources ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now() NOT NULL;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS location_id uuid REFERENCES locations(id) ON DELETE restrict;
CREATE TABLE IF NOT EXISTS staff_locations(tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE cascade,staff_user_id uuid NOT NULL REFERENCES users(id) ON DELETE restrict,location_id uuid NOT NULL REFERENCES locations(id) ON DELETE restrict,PRIMARY KEY(staff_user_id,location_id));
CREATE TABLE IF NOT EXISTS service_locations(tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE cascade,service_id uuid NOT NULL REFERENCES services(id) ON DELETE restrict,location_id uuid NOT NULL REFERENCES locations(id) ON DELETE restrict,PRIMARY KEY(service_id,location_id));
CREATE TABLE IF NOT EXISTS staff_time_off(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE cascade,staff_user_id uuid NOT NULL REFERENCES users(id) ON DELETE restrict,type varchar(30) NOT NULL CHECK(type IN('HOLIDAY','SICKNESS','TRAINING','UNAVAILABLE','OTHER')),status varchar(20) DEFAULT 'PENDING' NOT NULL CHECK(status IN('PENDING','APPROVED','REJECTED','CANCELLED')),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL CHECK(starts_at<ends_at),all_day boolean DEFAULT false NOT NULL,reason varchar(500),created_by_user_id uuid NOT NULL REFERENCES users(id),approved_by_user_id uuid REFERENCES users(id),created_at timestamptz DEFAULT now() NOT NULL,updated_at timestamptz DEFAULT now() NOT NULL);
CREATE INDEX IF NOT EXISTS staff_time_off_availability_idx ON staff_time_off(tenant_id,staff_user_id,starts_at,ends_at) WHERE status='APPROVED';
CREATE TABLE IF NOT EXISTS commission_rules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE cascade,staff_user_id uuid REFERENCES users(id) ON DELETE restrict,name varchar(150) NOT NULL,service_percentage_basis_points integer CHECK(service_percentage_basis_points BETWEEN 0 AND 10000),product_percentage_basis_points integer CHECK(product_percentage_basis_points BETWEEN 0 AND 10000),fixed_service_amount_minor integer CHECK(fixed_service_amount_minor>=0),effective_from timestamptz NOT NULL,effective_to timestamptz,is_active boolean DEFAULT true NOT NULL,created_at timestamptz DEFAULT now() NOT NULL,updated_at timestamptz DEFAULT now() NOT NULL);
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;ALTER TABLE staff_locations ENABLE ROW LEVEL SECURITY;ALTER TABLE service_locations ENABLE ROW LEVEL SECURITY;ALTER TABLE staff_time_off ENABLE ROW LEVEL SECURITY;ALTER TABLE commission_rules ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON locations,staff_locations,service_locations,staff_time_off,commission_rules FROM anon,authenticated;
