import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import { formatInTimeZone, fromZonedTime } from 'date-fns-tz';
import { getDatabase, reportExportJobs, reportScheduleRuns, reportSchedules, tenants, users } from '@ks-os/database';
import { CreateReportScheduleSchema, type CreateReportSchedule, type UpdateReportSchedule } from '@ks-os/contracts';
import { EmailService } from '../email/email.service.js';
import { ReportExportsService } from './report-exports.service.js';

const reportError=(statusCode:number,code:string,message:string)=>Object.assign(new Error(message),{statusCode,code});
const dateKey=(date:Date)=>date.toISOString().slice(0,10);const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*86_400_000);
type Recurrence={frequency:'DAILY'|'WEEKLY'|'MONTHLY';deliveryTimeLocal:string;weekday?:number|null;monthlyDay?:string|null};
export function nextReportRun(recurrence:Recurrence,timezone:string,after=new Date()){
  const localDate=new Date(`${formatInTimeZone(after,timezone,'yyyy-MM-dd')}T00:00:00Z`);
  for(let offset=0;offset<370;offset++){const date=addDays(localDate,offset);const day=date.getUTCDate();const next=addDays(date,1);const matches=recurrence.frequency==='DAILY'||(recurrence.frequency==='WEEKLY'&&date.getUTCDay()===recurrence.weekday)||(recurrence.frequency==='MONTHLY'&&(recurrence.monthlyDay==='FIRST'?day===1:recurrence.monthlyDay==='LAST'?next.getUTCMonth()!==date.getUTCMonth():day===Number(recurrence.monthlyDay)));
    if(!matches)continue;const candidate=fromZonedTime(`${dateKey(date)}T${recurrence.deliveryTimeLocal}:00`,timezone);if(candidate>after)return candidate;
  }
  throw reportError(400,'REPORT_SCHEDULE_INVALID','A next schedule occurrence could not be calculated.');
}
const mask=(email:string)=>{const[local,domain]=email.split('@');return`${local.slice(0,1)}***@${domain}`;};
const serialise=(row:any)=>({id:row.id,name:row.name,reportType:row.reportType,filters:row.filtersJson,frequency:row.frequency,timezone:row.timezone,deliveryTimeLocal:String(row.deliveryTimeLocal).slice(0,5),weekday:row.weekday??null,monthlyDay:row.monthlyDay??null,recipientUserIds:row.recipientUserIds,additionalRecipientsMasked:(row.additionalRecipientEmails as string[]).map(mask),status:row.status,nextRunAt:row.nextRunAt?.toISOString()??null,lastRunAt:row.lastRunAt?.toISOString()??null,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()});

export class ReportSchedulesService {
  private db=getDatabase();private exports:ReportExportsService;private email:EmailService;
  constructor(exportsService=new ReportExportsService(),emailService=new EmailService()){this.exports=exportsService;this.email=emailService;}
  private async tenant(tenantId:string){const[row]=await this.db.select({timezone:tenants.timezone,name:tenants.name,primaryColor:tenants.primaryColor}).from(tenants).where(eq(tenants.id,tenantId)).limit(1);if(!row)throw reportError(404,'REPORT_SCHEDULE_INVALID','Tenant configuration is unavailable.');return row;}
  private async validateRecipients(tenantId:string,ids:string[]){if(!ids.length)return;const rows=await this.db.select({id:users.id}).from(users).where(and(eq(users.tenantId,tenantId),eq(users.accountStatus,'ACTIVE'),inArray(users.id,ids)));if(rows.length!==new Set(ids).size)throw reportError(400,'REPORT_SCHEDULE_INVALID','Recipients must be active users in this tenant.');}
  async create(tenantId:string,userId:string,input:CreateReportSchedule){const parsed=CreateReportScheduleSchema.parse(input);await this.validateRecipients(tenantId,parsed.recipientUserIds);this.exports.validate(parsed.reportType,parsed.filters);const tenant=await this.tenant(tenantId);const next=nextReportRun(parsed.recurrence,tenant.timezone);const[row]=await this.db.insert(reportSchedules).values({tenantId,createdByUserId:userId,name:parsed.name,reportType:parsed.reportType,filtersJson:parsed.filters,frequency:parsed.recurrence.frequency,timezone:tenant.timezone,deliveryTimeLocal:parsed.recurrence.deliveryTimeLocal,weekday:parsed.recurrence.weekday??null,monthlyDay:parsed.recurrence.monthlyDay??null,recipientUserIds:parsed.recipientUserIds,additionalRecipientEmails:[...new Set(parsed.additionalRecipientEmails.map(email=>email.toLowerCase()))],status:'ACTIVE',nextRunAt:next}).returning();return serialise(row);}
  async list(tenantId:string){const rows=await this.db.select().from(reportSchedules).where(and(eq(reportSchedules.tenantId,tenantId),sql`${reportSchedules.status}<>'DELETED'`)).orderBy(desc(reportSchedules.createdAt));return{data:rows.map(serialise)};}
  async row(tenantId:string,id:string,includeDeleted=false){const conditions=[eq(reportSchedules.tenantId,tenantId),eq(reportSchedules.id,id)];if(!includeDeleted)conditions.push(sql`${reportSchedules.status}<>'DELETED'`);const[row]=await this.db.select().from(reportSchedules).where(and(...conditions)).limit(1);if(!row)throw reportError(404,'REPORT_SCHEDULE_NOT_FOUND','Report schedule not found.');return row;}
  async get(tenantId:string,id:string){return serialise(await this.row(tenantId,id));}
  async update(tenantId:string,id:string,input:UpdateReportSchedule){const current=await this.row(tenantId,id);const recurrence={frequency:(input.recurrence?.frequency??current.frequency) as any,deliveryTimeLocal:input.recurrence?.deliveryTimeLocal??String(current.deliveryTimeLocal).slice(0,5),weekday:input.recurrence?.weekday??current.weekday,monthlyDay:input.recurrence?.monthlyDay??current.monthlyDay};const recipients=input.recipientUserIds??current.recipientUserIds as string[];await this.validateRecipients(tenantId,recipients);const reportType=input.reportType??current.reportType as any;const filters=input.filters??current.filtersJson as any;this.exports.validate(reportType,filters);const next=current.status==='ACTIVE'?nextReportRun(recurrence,current.timezone):current.nextRunAt;const[row]=await this.db.update(reportSchedules).set({name:input.name??current.name,reportType,filtersJson:filters,frequency:recurrence.frequency,deliveryTimeLocal:recurrence.deliveryTimeLocal,weekday:recurrence.weekday??null,monthlyDay:recurrence.monthlyDay??null,recipientUserIds:recipients,additionalRecipientEmails:input.additionalRecipientEmails?.map((x:string)=>x.toLowerCase())??current.additionalRecipientEmails,nextRunAt:next,updatedAt:new Date()}).where(and(eq(reportSchedules.id,id),eq(reportSchedules.tenantId,tenantId))).returning();return serialise(row);}
  async pause(tenantId:string,id:string){const current=await this.row(tenantId,id);if(current.status==='PAUSED')throw reportError(409,'REPORT_SCHEDULE_ALREADY_PAUSED','The schedule is already paused.');const[row]=await this.db.update(reportSchedules).set({status:'PAUSED',nextRunAt:null,updatedAt:new Date()}).where(and(eq(reportSchedules.id,id),eq(reportSchedules.tenantId,tenantId))).returning();return serialise(row);}
  async resume(tenantId:string,id:string){const current=await this.row(tenantId,id);const next=nextReportRun({frequency:current.frequency as any,deliveryTimeLocal:String(current.deliveryTimeLocal).slice(0,5),weekday:current.weekday,monthlyDay:current.monthlyDay},current.timezone);const[row]=await this.db.update(reportSchedules).set({status:'ACTIVE',nextRunAt:next,updatedAt:new Date()}).where(and(eq(reportSchedules.id,id),eq(reportSchedules.tenantId,tenantId))).returning();return serialise(row);}
  async remove(tenantId:string,id:string){await this.row(tenantId,id);await this.db.update(reportSchedules).set({status:'DELETED',nextRunAt:null,updatedAt:new Date()}).where(and(eq(reportSchedules.id,id),eq(reportSchedules.tenantId,tenantId)));}
  async runs(tenantId:string,id:string){await this.row(tenantId,id,true);const rows=await this.db.select().from(reportScheduleRuns).where(and(eq(reportScheduleRuns.tenantId,tenantId),eq(reportScheduleRuns.scheduleId,id))).orderBy(desc(reportScheduleRuns.scheduledFor)).limit(100);return rows.map(row=>({id:row.id,scheduledFor:row.scheduledFor.toISOString(),status:row.status,reportExportJobId:row.reportExportJobId??null,failureCode:row.failureCode??null,startedAt:row.startedAt?.toISOString()??null,completedAt:row.completedAt?.toISOString()??null}));}
  async queueDue(limit=20){let queued=0;await this.db.transaction(async tx=>{const result=await tx.execute(sql`select * from report_schedules where status='ACTIVE' and next_run_at<=now() order by next_run_at,id for update skip locked limit ${Math.min(100,Math.max(1,limit))}`);for(const schedule of result.rows as any[]){const[run]=await tx.insert(reportScheduleRuns).values({tenantId:schedule.tenant_id,scheduleId:schedule.id,scheduledFor:new Date(schedule.next_run_at),status:'QUEUED'}).onConflictDoNothing({target:[reportScheduleRuns.scheduleId,reportScheduleRuns.scheduledFor]}).returning();if(run){const job=await this.exports.createScheduled(tx,schedule.tenant_id,schedule.created_by_user_id,schedule.report_type,schedule.filters_json);await tx.update(reportScheduleRuns).set({reportExportJobId:job.id}).where(eq(reportScheduleRuns.id,run.id));queued++;}const next=nextReportRun({frequency:schedule.frequency,deliveryTimeLocal:String(schedule.delivery_time_local).slice(0,5),weekday:schedule.weekday,monthlyDay:schedule.monthly_day},schedule.timezone,new Date(schedule.next_run_at));await tx.update(reportSchedules).set({lastRunAt:new Date(schedule.next_run_at),nextRunAt:next,updatedAt:new Date()}).where(eq(reportSchedules.id,schedule.id));}});return{queued};}
  async deliverReady(limit=20){const result=await this.db.execute(sql`select r.id run_id,r.tenant_id,r.schedule_id,r.report_export_job_id,s.name schedule_name,s.report_type,s.recipient_user_ids,s.additional_recipient_emails,t.name tenant_name,t.primary_color,j.status job_status,j.failure_code job_failure_code,j.expires_at from report_schedule_runs r join report_schedules s on s.id=r.schedule_id and s.tenant_id=r.tenant_id join report_export_jobs j on j.id=r.report_export_job_id and j.tenant_id=r.tenant_id join tenants t on t.id=r.tenant_id where r.status='QUEUED' and j.status in ('READY','FAILED') order by r.scheduled_for limit ${Math.min(100,Math.max(1,limit))}`);let delivered=0,failed=0;for(const row of result.rows as any[]){try{const[claimed]=await this.db.update(reportScheduleRuns).set({status:'PROCESSING',startedAt:new Date()}).where(and(eq(reportScheduleRuns.id,row.run_id),eq(reportScheduleRuns.status,'QUEUED'))).returning({id:reportScheduleRuns.id});if(!claimed)continue;if(row.job_status==='FAILED')throw reportError(409,row.job_failure_code||'REPORT_SCHEDULE_RUN_FAILED','The scheduled export failed.');const ids=row.recipient_user_ids as string[];const members=ids.length?await this.db.select({id:users.id,email:users.email,name:users.name}).from(users).where(and(eq(users.tenantId,row.tenant_id),eq(users.accountStatus,'ACTIVE'),inArray(users.id,ids))):[];const recipients=[...members.map(m=>({email:m.email,name:m.name})),...(row.additional_recipient_emails as string[]).map(email=>({email,name:undefined}))];const unique=new Map(recipients.map(item=>[item.email.toLowerCase(),item]));if(!unique.size)throw reportError(409,'REPORT_SCHEDULE_INVALID','No active recipients remain.');const base=process.env.PUBLIC_APP_URL||process.env.WEB_APP_URL;if(!base)throw reportError(500,'REPORT_DELIVERY_URL_UNAVAILABLE','The application URL is not configured.');for(const recipient of unique.values())await this.email.enqueueEmail({tenantId:row.tenant_id,recipientEmail:recipient.email,recipientName:recipient.name,templateKey:'scheduled-report-ready',templateDataJson:{tenantName:row.tenant_name,tenantPrimaryColor:row.primary_color,reportName:row.schedule_name,reportType:row.report_type,downloadPageUrl:`${base.replace(/\/$/,'')}/app/reports/exports?download=${row.report_export_job_id}`,expiresAt:new Date(row.expires_at).toISOString()},idempotencyKey:`scheduled-report:${row.run_id}:${recipient.email.toLowerCase()}`,relatedEntityType:'report_schedule_run',relatedEntityId:row.run_id});await this.db.update(reportScheduleRuns).set({status:'SUCCEEDED',completedAt:new Date()}).where(eq(reportScheduleRuns.id,row.run_id));delivered++;}catch(cause:any){failed++;await this.db.update(reportScheduleRuns).set({status:'FAILED',failureCode:String(cause?.code||'REPORT_SCHEDULE_RUN_FAILED').slice(0,80),completedAt:new Date()}).where(eq(reportScheduleRuns.id,row.run_id));}}return{claimed:result.rows.length,delivered,failed};}
}
