import type { FastifyInstance, FastifyRequest } from 'fastify';
import { CreateReportExportSchema, CreateReportScheduleSchema, ReportExportDownloadSchema, ReportExportIdParamsSchema, ReportExportListSchema, ReportExportSchema, ReportHistoryQuerySchema, ReportScheduleIdParamsSchema, ReportScheduleListSchema, ReportScheduleRunSchema, ReportScheduleSchema, UpdateReportScheduleSchema } from '@ks-os/contracts';
import { ReportExportsService } from './report-exports.service.js';
import { ReportSchedulesService } from './report-schedules.service.js';

const owner=(request:FastifyRequest,code:string)=>{request.requireAuth();if(request.auth!.role!=='owner')throw Object.assign(new Error('Owner access is required.'),{statusCode:403,code});return request.auth!;};
const handle=async(reply:any,run:()=>Promise<any>)=>{try{return await run();}catch(error:any){const validation=error?.name==='ZodError';const status=validation?400:Number(error?.statusCode||500);const code=validation?'EXPORT_INVALID_FILTER':String(error?.code||'EXPORT_GENERATION_FAILED');return reply.code(status).send({success:false,error:{code,message:status>=500?'Report operations are temporarily unavailable.':error.message}});}};

export async function reportingRoutes(app:FastifyInstance){const exportsService=new ReportExportsService();const schedules=new ReportSchedulesService(exportsService);
  app.post('/api/v1/report-exports',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'EXPORT_ACCESS_DENIED');const data=await exportsService.create(auth.tenantId,auth.tenantUserId,CreateReportExportSchema.parse(request.body));return reply.code(202).send({success:true,data:ReportExportSchema.parse(data)});}));
  app.get('/api/v1/report-exports',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'EXPORT_ACCESS_DENIED');const query=ReportHistoryQuerySchema.parse(request.query);return reply.send({success:true,data:ReportExportListSchema.parse(await exportsService.list(auth.tenantId,query.limit,query.cursor?new Date(query.cursor):undefined))});}));
  app.get('/api/v1/report-exports/:exportId',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'EXPORT_ACCESS_DENIED');const{id}=({id:ReportExportIdParamsSchema.parse(request.params).exportId});return reply.send({success:true,data:ReportExportSchema.parse(await exportsService.get(auth.tenantId,id))});}));
  app.post('/api/v1/report-exports/:exportId/download',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'EXPORT_ACCESS_DENIED');const{exportId}=ReportExportIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportExportDownloadSchema.parse(await exportsService.download(auth.tenantId,exportId))});}));
  app.post('/api/v1/report-exports/:exportId/cancel',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'EXPORT_ACCESS_DENIED');const{exportId}=ReportExportIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportExportSchema.parse(await exportsService.cancel(auth.tenantId,exportId))});}));

  app.get('/api/v1/report-schedules',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');return reply.send({success:true,data:ReportScheduleListSchema.parse(await schedules.list(auth.tenantId))});}));
  app.post('/api/v1/report-schedules',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const data=await schedules.create(auth.tenantId,auth.tenantUserId,CreateReportScheduleSchema.parse(request.body));return reply.code(201).send({success:true,data:ReportScheduleSchema.parse(data)});}));
  app.get('/api/v1/report-schedules/:scheduleId',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportScheduleSchema.parse(await schedules.get(auth.tenantId,scheduleId))});}));
  app.patch('/api/v1/report-schedules/:scheduleId',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportScheduleSchema.parse(await schedules.update(auth.tenantId,scheduleId,UpdateReportScheduleSchema.parse(request.body)))});}));
  app.post('/api/v1/report-schedules/:scheduleId/pause',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportScheduleSchema.parse(await schedules.pause(auth.tenantId,scheduleId))});}));
  app.post('/api/v1/report-schedules/:scheduleId/resume',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportScheduleSchema.parse(await schedules.resume(auth.tenantId,scheduleId))});}));
  app.delete('/api/v1/report-schedules/:scheduleId',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);await schedules.remove(auth.tenantId,scheduleId);return reply.code(204).send();}));
  app.get('/api/v1/report-schedules/:scheduleId/runs',async(request,reply)=>handle(reply,async()=>{const auth=owner(request,'REPORT_SCHEDULE_ACCESS_DENIED');const{scheduleId}=ReportScheduleIdParamsSchema.parse(request.params);return reply.send({success:true,data:ReportScheduleRunSchema.array().parse(await schedules.runs(auth.tenantId,scheduleId))});}));
}

export async function reportingWorkerRoutes(app:FastifyInstance){const exportsService=new ReportExportsService();const schedules=new ReportSchedulesService(exportsService);const authorize=(request:FastifyRequest)=>{const supplied=request.headers.authorization?.replace(/^Bearer\s+/i,'');if(!process.env.AUTOMATION_WORKER_SECRET||supplied!==process.env.AUTOMATION_WORKER_SECRET)throw Object.assign(new Error('Unauthorized'),{statusCode:401,code:'UNAUTHENTICATED'});};
  app.post('/schedules',async request=>{authorize(request);return schedules.queueDue();});app.post('/exports',async request=>{authorize(request);const generated=await exportsService.processPending();const delivery=await schedules.deliverReady();return{...generated,delivery};});app.post('/cleanup',async request=>{authorize(request);return exportsService.cleanupExpired();});
}
