import test from 'node:test';import assert from 'node:assert/strict';
import { resolveAnalyticsPeriod } from '../src/modules/analytics/analytics.period.js';
import { compareKpi,safeRate } from '../src/modules/analytics/analytics.calculations.js';
import { AnalyticsService } from '../src/modules/analytics/analytics.service.js';
import type { AnalyticsRepositoryLike,Summary } from '../src/modules/analytics/analytics.repository.js';

const iso=(d:Date)=>d.toISOString();
test('period presets use tenant-local boundaries and previous equivalent period',()=>{const now=new Date('2026-07-19T15:00:00Z');const today=resolveAnalyticsPeriod({preset:'TODAY'},'Europe/London',now);assert.equal(iso(today.from),'2026-07-18T23:00:00.000Z');assert.equal(iso(today.to),'2026-07-19T23:00:00.000Z');const yesterday=resolveAnalyticsPeriod({preset:'YESTERDAY'},'Europe/London',now);assert.equal(yesterday.localFrom,'2026-07-18');const week=resolveAnalyticsPeriod({preset:'LAST_7_DAYS'},'Europe/London',now);assert.equal(week.localFrom,'2026-07-13');assert.equal(iso(week.previousTo),iso(week.from));const month=resolveAnalyticsPeriod({preset:'THIS_MONTH'},'Europe/London',now);assert.equal(month.localFrom,'2026-07-01');});
test('custom ranges enforce ordering and 366-day maximum',()=>{const p=resolveAnalyticsPeriod({preset:'CUSTOM',from:'2026-07-01',to:'2026-07-07'},'Asia/Tokyo');assert.equal(p.localFrom,'2026-07-01');assert.equal(p.previousFrom.toISOString(),'2026-06-23T15:00:00.000Z');assert.throws(()=>resolveAnalyticsPeriod({preset:'CUSTOM',from:'2026-07-02',to:'2026-07-01'},'UTC'),/invalid/);assert.throws(()=>resolveAnalyticsPeriod({preset:'CUSTOM',from:'2025-01-01',to:'2026-07-01'},'UTC'),/366/);});
test('UK DST transition produces correct UTC day lengths',()=>{const spring=resolveAnalyticsPeriod({preset:'CUSTOM',from:'2026-03-29',to:'2026-03-29'},'Europe/London');assert.equal((spring.to.getTime()-spring.from.getTime())/3600000,23);const autumn=resolveAnalyticsPeriod({preset:'CUSTOM',from:'2026-10-25',to:'2026-10-25'},'Europe/London');assert.equal((autumn.to.getTime()-autumn.from.getTime())/3600000,25);});
test('KPI comparisons and zero denominators are safe',()=>{assert.deepEqual(compareKpi(12,10),{value:12,previousValue:10,changeValue:2,changePercentage:20});assert.equal(compareKpi(3,0).changePercentage,null);assert.equal(safeRate(2,0),0);});

const current:Summary={total:10,completed:6,cancelled:2,noShow:1,eligible:10,uniqueClients:7,newClients:3,returningClients:4,recordedRevenue:10000,refundedAmount:1000,outstandingAmount:2500,transactionCount:4};
const previous:Summary={...current,total:5,completed:3,cancelled:1,noShow:0,eligible:5,recordedRevenue:5000,refundedAmount:0,outstandingAmount:1000,transactionCount:2};
test('overview is tenant scoped and calculates money, rates and comparisons',async()=>{const tenants:string[]=[];let call=0;const repo:AnalyticsRepositoryLike={async getSummary(tenantId){tenants.push(tenantId);return call++===0?current:previous},async getOperations(tenantId){tenants.push(tenantId);return{todayAppointments:2,awaitingPayment:1,incompleteForms:1,failedEmails:0,failedSms:0,openDisputes:0,failedPayouts:0,stripeActionRequired:0}},async getTopServices(tenantId){tenants.push(tenantId);return[]},async getStaffUtilisation(tenantId){tenants.push(tenantId);return[{staffId:'11111111-1111-1111-1111-111111111111',staffName:'No schedule',bookedMinutes:60,availableMinutes:null,utilisationPercentage:null,completedAppointments:1,recordedRevenue:1000}]},async getDailyTrend(tenantId){tenants.push(tenantId);return[]}};const service=new AnalyticsService(repo,async()=>({timezone:'Europe/London',currency:'GBP'}));const result=await service.overview('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',{preset:'LAST_7_DAYS'},new Date('2026-07-19T12:00:00Z'));assert.ok(tenants.every(id=>id==='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'));assert.equal(result.bookings.cancellationRate.value,20);assert.equal(result.revenue.netRecordedRevenue.value,9000);assert.equal(result.revenue.averageTransactionValue.value,2500);assert.equal(result.staffUtilisation[0].utilisationPercentage,null);});
