import assert from 'node:assert/strict';
import test from 'node:test';
import { AutomationActionSchema, AutomationConditionSchema, CreateAutomationSchema, TriggerSchema } from '@ks-os/contracts';
import { stableEventId } from '../src/modules/automations/business-events.service.js';

test('automation schemas accept constrained predefined workflows',()=>{const parsed=CreateAutomationSchema.parse({name:'Booking confirmation',description:'',trigger:{type:'BOOKING_CONFIRMED',config:{}},conditions:[{type:'CLIENT_HAS_EMAIL'}],actions:[{type:'SEND_EMAIL',templateKey:'booking-confirmed'},{type:'SCHEDULE_SMS',templateKey:'appointment-reminder',offsetMinutes:1440}]});assert.equal(parsed.actions.length,2);});
test('automation schemas reject arbitrary code, URLs, operators and offsets',()=>{assert.equal(TriggerSchema.safeParse({type:'SCHEDULED_BEFORE_APPOINTMENT',config:{offsetMinutes:999999}}).success,false);assert.equal(AutomationConditionSchema.safeParse({type:'RAW_SQL',sql:'select *'}).success,false);assert.equal(AutomationActionSchema.safeParse({type:'HTTP_REQUEST',url:'https://example.com'}).success,false);assert.equal(CreateAutomationSchema.safeParse({name:'unsafe',trigger:{type:'BOOKING_CONFIRMED',config:{}},conditions:[],actions:[{type:'SEND_EMAIL',templateKey:'booking-confirmed',javascript:'alert(1)'}]}).success,false);});
test('business event IDs are stable for the same domain transition',()=>{assert.equal(stableEventId('BOOKING_RESCHEDULED','11111111-1111-1111-1111-111111111111','2026-07-20T09:00:00.000Z'),stableEventId('BOOKING_RESCHEDULED','11111111-1111-1111-1111-111111111111','2026-07-20T09:00:00.000Z'));});
test('platform limits reject excessive conditions and actions',()=>{const conditions=Array.from({length:11},()=>({type:'CLIENT_HAS_EMAIL'}));const actions=Array.from({length:11},()=>({type:'SEND_EMAIL',templateKey:'booking-confirmed'}));assert.equal(CreateAutomationSchema.safeParse({name:'too many',trigger:{type:'BOOKING_CONFIRMED',config:{}},conditions,actions:[{type:'SEND_EMAIL',templateKey:'booking-confirmed'}]}).success,false);assert.equal(CreateAutomationSchema.safeParse({name:'too many',trigger:{type:'BOOKING_CONFIRMED',config:{}},conditions:[],actions}).success,false);});
