import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import { renderCalendar } from '../src/modules/integrations/ical.js';
import { decryptSecret,encryptSecret,hashSecret,signState,verifyState,webhookSignature } from '../src/modules/integrations/integration-security.js';
import { CreateApiCredentialSchema,CreateCalendarFeedSchema,CreateWebhookSubscriptionSchema } from '@ks-os/contracts';

process.env.INTEGRATION_ENCRYPTION_KEY='11'.repeat(32);
test('calendar output is stable, escaped, folded, and represents cancellation',()=>{const output=renderCalendar('Demo, calendar',[{id:'abc',reference:'ref',start:'2026-10-25T00:30:00Z',end:'2026-10-25T02:30:00Z',updated:'2026-10-24T10:00:00Z',status:'CANCELLED',version:3,summary:'Cut, colour; style',description:'Line 1\nLine 2'}]);assert.match(output,/UID:booking-abc@ks-os/);assert.match(output,/DTSTART:20261025T003000Z/);assert.match(output,/SEQUENCE:3/);assert.match(output,/STATUS:CANCELLED/);assert.match(output,/SUMMARY:Cut\\, colour\\; style/);assert.ok(output.endsWith('\r\n'));});
test('encrypted secrets and signed OAuth state reject tampering',()=>{const encrypted=encryptSecret({refreshToken:'private'});assert.equal(encrypted.includes('private'),false);assert.deepEqual(decryptSecret(encrypted),{refreshToken:'private'});const state=signState({tenantId:'tenant'});assert.equal((verifyState<any>(state)).tenantId,'tenant');assert.throws(()=>verifyState(state+'tampered'));});
test('hash and webhook signatures are deterministic without exposing secrets',()=>{assert.equal(hashSecret('a'),hashSecret('a'));assert.equal(webhookSignature('secret',123,'{}'),webhookSignature('secret',123,'{}'));assert.notEqual(webhookSignature('secret',123,'{}'),webhookSignature('secret',124,'{}'));});
test('integration contracts enforce scope, strict fields, and versioned webhook events',()=>{assert.equal(CreateCalendarFeedSchema.safeParse({scope:'STAFF',privacyLevel:'BUSY_ONLY',bookingStatuses:['CONFIRMED']}).success,false);assert.equal(CreateApiCredentialSchema.safeParse({name:'Zapier',scopes:['admin:*']}).success,false);assert.equal(CreateWebhookSubscriptionSchema.safeParse({name:'Test hook',targetUrl:'https://example.com/hook',eventTypes:['booking.created']}).success,false);});
test('migration enables RLS and stores only encrypted or hashed credentials',()=>{const migration=fs.readFileSync(path.resolve(process.cwd(),'../../packages/database/migrations/20260723000000_phase_13_integrations.sql'),'utf8');for(const table of ['integration_connections','calendar_feeds','webhook_subscriptions','api_credentials','hardware_integrations'])assert.match(migration,new RegExp(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY`));assert.match(migration,/token_ciphertext text/);assert.match(migration,/key_hash varchar\(64\)/);assert.doesNotMatch(migration,/access_token\s+text/i);});
