import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import type {OperationsIssue} from '@ks-os/contracts';
import {assignIssue,createIssueTask,getOperationsIssue,issueCommand} from './operations.api.js';
import {useAuth} from '../../context/AuthContext.js';

export function OperationIssueDetailPage(){const{issueId=''}=useParams();const navigate=useNavigate();const{user}=useAuth();const[issue,setIssue]=useState<OperationsIssue|null>(null);const[assignee,setAssignee]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const load=()=>getOperationsIssue(issueId).then(x=>{setIssue(x);setAssignee(x.assignedToUserId??'')}).catch(e=>setError(e.message));useEffect(()=>{void load()},[issueId]);const command=async(action:'acknowledge'|'resolve'|'dismiss'|'retry')=>{setBusy(true);setError('');try{await issueCommand(issueId,action);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};const saveAssignee=async()=>{setBusy(true);try{const result=await assignIssue(issueId,assignee||null);setIssue(result.data)}catch(e:any){setError(e.message)}finally{setBusy(false)}};const makeTask=async()=>{setBusy(true);try{const task=await createIssueTask(issueId,{title:`Follow up: ${issue?.title??'operations issue'}`,priority:issue?.severity==='CRITICAL'?'URGENT':'HIGH',assignedUserId:issue?.assignedToUserId??undefined,dueAt:issue?.actionDeadline??undefined});navigate(`/app/tasks/${task.id}`)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(error&&!issue)return <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}</p>;if(!issue)return <p>Loading issue…</p>;
 return <main className="mx-auto max-w-4xl space-y-5"><Link to="/app/operations" className="text-sm font-bold text-indigo-700">← Operations inbox</Link><header className="rounded-xl border bg-white p-6"><div className="flex flex-wrap gap-2 text-xs font-black"><span>{issue.severity}</span><span>·</span><span>{issue.category}</span><span>·</span><span>{issue.status}</span></div><h1 className="mt-2 text-2xl font-black">{issue.title}</h1><p className="mt-2 text-slate-600">{issue.message}</p></header>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}<section className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border bg-white p-5"><h2 className="font-extrabold">Issue details</h2><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-slate-500">Last occurred</dt><dd>{new Date(issue.lastOccurredAt).toLocaleString()}</dd></div><div><dt className="text-slate-500">Occurrences</dt><dd>{issue.occurrenceCount}</dd></div>{issue.actionDeadline&&<div><dt className="text-slate-500">Action deadline</dt><dd>{new Date(issue.actionDeadline).toLocaleString()}</dd></div>}<div><dt className="text-slate-500">Source</dt><dd className="font-mono text-xs">{issue.sourceType} · {issue.sourceId}</dd></div></dl></article><article className="rounded-xl border bg-white p-5"><h2 className="font-extrabold">Actions</h2><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={makeTask} className="rounded-lg bg-indigo-700 px-3 py-2 text-sm font-bold text-white">Create follow-up task</button>{issue.status==='OPEN'&&<button disabled={busy} onClick={()=>command('acknowledge')} className="rounded-lg border px-3 py-2 text-sm font-bold">Acknowledge</button>}{['OPEN','ACKNOWLEDGED'].includes(issue.status)&&<button disabled={busy} onClick={()=>command('resolve')} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white">Resolve</button>}{user?.role==='owner'&&['OPEN','ACKNOWLEDGED'].includes(issue.status)&&<button disabled={busy} onClick={()=>command('retry')} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">Retry safely</button>}{user?.role==='owner'&&<button disabled={busy} onClick={()=>command('dismiss')} className="rounded-lg border px-3 py-2 text-sm font-bold text-slate-600">Dismiss</button>}</div>{user?.role==='owner'&&<div className="mt-4"><label htmlFor="issue-assignee" className="block text-xs font-bold text-slate-500">Assignee user ID</label><div className="mt-1 flex gap-2"><input id="issue-assignee" value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="Leave blank to unassign" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm"/><button type="button" disabled={busy} onClick={saveAssignee} className="rounded-lg border px-3 py-2 text-sm font-bold">Save</button></div></div>}</article></section></main>}
