import type { AdvancedAnalyticsQuery } from '@ks-os/contracts';
import { resolveAnalyticsPeriod } from './analytics.period.js';
import { AdvancedAnalyticsRepository } from './advanced-analytics.repository.js';

const n=(v:unknown)=>Number(v??0);const minimum=()=>Math.min(100,Math.max(5,Number(process.env.ANALYTICS_MINIMUM_SAMPLE_SIZE||10)));
const percentage=(matched:number,eligible:number)=>eligible?Number((matched/eligible*100).toFixed(1)):null;
export class AdvancedAnalyticsService {
  constructor(private repository=new AdvancedAnalyticsRepository()){}
  async overview(tenantId:string,query:AdvancedAnalyticsQuery){const tenant=await this.repository.tenant(tenantId);if(!tenant)throw Object.assign(new Error('Analytics data is unavailable.'),{statusCode:404,code:'ANALYTICS_DATA_UNAVAILABLE'});const period=resolveAnalyticsPeriod(query as any,tenant.timezone);const days=Math.ceil((period.to.getTime()-period.from.getTime())/86_400_000);const grain=query.grain==='AUTO'?(days<=90?'DAY':days<=210?'WEEK':'MONTH'):query.grain;const sqlGrain=grain.toLowerCase();const min=minimum();
    const[bookingTrend,revenueTrend,retentionRaw,rebookingRaw,leadRaw,serviceRaw,staffRaw,patternRaw,mixRaw,frequencyRaw,forwardRaw]=await Promise.all([
      this.repository.bookingTrend(tenantId,period,sqlGrain),this.repository.revenueTrend(tenantId,period,sqlGrain),this.repository.retention(tenantId,period,query.retentionWindowDays),this.repository.rebooking(tenantId,period),this.repository.leadTime(tenantId,period),this.repository.serviceDemand(tenantId,period),this.repository.staffTrend(tenantId,period,sqlGrain),this.repository.patterns(tenantId,period),this.repository.revenueMix(tenantId,period),this.repository.clientFrequency(tenantId,period),this.repository.forward(tenantId,period)
    ]);
    const rate=(raw:{eligible:number;matched:number},explanation:string)=>{const available=raw.eligible>=min;return{status:available?'AVAILABLE' as const:'INSUFFICIENT_DATA' as const,sampleSize:raw.eligible,eligible:raw.eligible,matched:raw.matched,percentage:available?percentage(raw.matched,raw.eligible):null,explanation};};
    const serviceDemand=serviceRaw.map((r:any)=>{const eligible=n(r.eligible),available=eligible>=min;return{serviceId:r.service_id,serviceName:r.name,bookings:n(r.bookings),completed:n(r.completed),cancelled:n(r.cancelled),noShows:n(r.no_shows),uniqueClients:n(r.unique_clients),recordedRevenue:n(r.revenue),cancellationRate:available?percentage(n(r.cancelled),eligible):null,noShowRate:available?percentage(n(r.no_shows),eligible):null,rateStatus:available?'AVAILABLE' as const:'INSUFFICIENT_DATA' as const};});
    const staffUtilisationTrend=staffRaw.map((r:any)=>{const booked=n(r.booked),available=r.available==null?null:n(r.available);return{bucket:r.bucket,bookedMinutes:booked,availableMinutes:available,utilisationPercentage:available&&available>0?Number((booked/available*100).toFixed(1)):null};});
    const bookingPatterns=patternRaw.map((r:any)=>{const eligible=n(r.eligible),noShows=n(r.no_shows),available=eligible>=min;return{dimension:r.dimension,key:r.key,label:r.label.trim(),eligible,noShows,noShowRate:available?percentage(noShows,eligible):null,status:available?'AVAILABLE' as const:'INSUFFICIENT_DATA' as const};});
    const current=n(forwardRaw.current_pace),previous=n(forwardRaw.previous_pace);
    return{period:{preset:period.preset,from:period.from.toISOString(),to:period.to.toISOString(),previousFrom:period.previousFrom.toISOString(),previousTo:period.previousTo.toISOString(),timezone:period.timezone,localFrom:period.localFrom,localTo:period.localTo,grain},currency:tenant.currency,minimumSampleSize:min,bookingTrend,revenueTrend,
      retention:{...rate(retentionRaw,`Clients whose first completed visit in the selected period is fully observable for ${query.retentionWindowDays} days, and who completed another visit within that window.`),windowDays:query.retentionWindowDays},
      rebooking:rate(rebookingRaw,'Distinct clients with a completed visit in the selected period who have a later, future confirmed appointment.'),
      leadTime:{status:leadRaw.sample>=min?'AVAILABLE':'INSUFFICIENT_DATA',sampleSize:leadRaw.sample,explanation:'Time from booking creation to appointment start; median is the primary measure.',medianHours:leadRaw.sample>=min?leadRaw.median:null,averageHours:leadRaw.sample>=min?leadRaw.average:null,distribution:leadRaw.distribution},
      serviceDemand,staffUtilisationTrend,bookingPatterns,revenueMix:mixRaw.map((r:any)=>({dimension:r.dimension,key:r.key,grossRecordedRevenue:n(r.gross),transactionCount:n(r.transactions)})),clientFrequency:frequencyRaw.map((r:any)=>({bucket:r.bucket,clients:n(r.clients)})),
      forwardBookings:{horizonDays:forwardRaw.horizon,confirmedAppointmentCount:n(forwardRaw.future_count),confirmedBookingValue:n(forwardRaw.future_value),currentBookingPace:current,previousBookingPace:previous,paceChangePercentage:previous?Number(((current-previous)/previous*100).toFixed(1)):null,label:'Projected from bookings already confirmed' as const},
      limitations:['Recorded revenue is not profit and uses local successful transaction and refund records.','Cancellation timing is unavailable because reliable appointment status history is not yet stored.','Service and product revenue are not split where a transaction cannot be attributed accurately.','Forward values include confirmed bookings only and are not guaranteed revenue.'],generatedAt:new Date().toISOString()};
  }
}
