export const CAPABILITIES = [
  'REPUTATION_VIEW','REPUTATION_MANAGE','REPUTATION_CONNECTIONS_MANAGE','REPUTATION_REPLY',
  'TASKS_VIEW_OWN','TASKS_VIEW_ALL','TASKS_CREATE','TASKS_ASSIGN','TASKS_UPDATE_OWN','TASKS_UPDATE_ALL','TASKS_COMPLETE_OWN','TASKS_COMPLETE_ALL',
  'WORK_VIEW_OWN','WORK_VIEW_ALL','WORK_CREATE','WORK_ASSIGN','WORK_UPDATE_OWN','WORK_UPDATE_ALL','WORK_COMPLETE_OWN','WORK_COMPLETE_ALL',
  'BOOKINGS_VIEW_OWN','BOOKINGS_VIEW_ALL','BOOKINGS_CREATE','BOOKINGS_UPDATE_OWN','BOOKINGS_UPDATE_ALL','BOOKINGS_CANCEL_OWN','BOOKINGS_CANCEL_ALL',
  'CLIENTS_VIEW_BASIC','CLIENTS_CREATE','CLIENTS_EDIT','CLIENTS_VIEW_HISTORY','CLIENTS_VIEW_SENSITIVE','FORMS_ASSIGN','FORMS_VIEW_ASSIGNED','FORMS_VIEW_ALL','FORMS_MANAGE',
  'SALES_VIEW_OWN','SALES_VIEW_ALL','SALES_CREATE','SALES_UPDATE_OWN','SALES_UPDATE_ALL','QUOTES_VIEW','QUOTES_MANAGE','PIPELINES_MANAGE',
  'POS_USE','POS_CHECKOUT_OWN','POS_CHECKOUT_ALL','PRODUCTS_VIEW','PRODUCTS_MANAGE','STOCK_ADJUST','REPORTS_VIEW_OPERATIONAL','REPORTS_VIEW_FINANCIAL','REPORT_EXPORT','REPORT_SCHEDULE',
  'ANALYTICS_ADVANCED_VIEW','OPERATIONS_VIEW_ASSIGNED','OPERATIONS_VIEW_ALL','OPERATIONS_MANAGE','TEAM_VIEW','TEAM_MANAGE','BUSINESS_SETTINGS_VIEW','BUSINESS_SETTINGS_MANAGE',
  'FINANCE_VIEW','REFUNDS_CREATE','PAYMENT_INTEGRATION_MANAGE',
] as const;

export type Capability = typeof CAPABILITIES[number];
export type AccessProfile = 'PRACTITIONER' | 'RECEPTIONIST' | 'MANAGER';

const practitioner: Capability[] = ['TASKS_VIEW_OWN','TASKS_CREATE','TASKS_UPDATE_OWN','TASKS_COMPLETE_OWN','WORK_VIEW_OWN','WORK_CREATE','WORK_UPDATE_OWN','WORK_COMPLETE_OWN','BOOKINGS_VIEW_OWN','BOOKINGS_UPDATE_OWN','BOOKINGS_CANCEL_OWN','CLIENTS_VIEW_BASIC','CLIENTS_VIEW_HISTORY','FORMS_ASSIGN','FORMS_VIEW_ASSIGNED','SALES_VIEW_OWN','SALES_CREATE','SALES_UPDATE_OWN','QUOTES_VIEW','POS_USE','POS_CHECKOUT_OWN','PRODUCTS_VIEW','OPERATIONS_VIEW_ASSIGNED'];
const receptionist: Capability[] = ['TASKS_VIEW_ALL','TASKS_CREATE','TASKS_ASSIGN','TASKS_UPDATE_ALL','TASKS_COMPLETE_ALL','WORK_VIEW_ALL','WORK_CREATE','WORK_ASSIGN','WORK_UPDATE_ALL','WORK_COMPLETE_ALL','BOOKINGS_VIEW_ALL','BOOKINGS_CREATE','BOOKINGS_UPDATE_ALL','BOOKINGS_CANCEL_ALL','CLIENTS_VIEW_BASIC','CLIENTS_CREATE','CLIENTS_EDIT','CLIENTS_VIEW_HISTORY','FORMS_ASSIGN','FORMS_VIEW_ASSIGNED','SALES_VIEW_ALL','SALES_CREATE','SALES_UPDATE_ALL','QUOTES_VIEW','QUOTES_MANAGE','POS_USE','POS_CHECKOUT_ALL','PRODUCTS_VIEW','OPERATIONS_VIEW_ALL','TEAM_VIEW'];
const manager: Capability[] = ['TASKS_VIEW_ALL','TASKS_CREATE','TASKS_ASSIGN','TASKS_UPDATE_ALL','TASKS_COMPLETE_ALL','WORK_VIEW_ALL','WORK_CREATE','WORK_ASSIGN','WORK_UPDATE_ALL','WORK_COMPLETE_ALL','BOOKINGS_VIEW_ALL','BOOKINGS_CREATE','BOOKINGS_UPDATE_ALL','BOOKINGS_CANCEL_ALL','CLIENTS_VIEW_BASIC','CLIENTS_CREATE','CLIENTS_EDIT','CLIENTS_VIEW_HISTORY','CLIENTS_VIEW_SENSITIVE','FORMS_ASSIGN','FORMS_VIEW_ALL','FORMS_MANAGE','SALES_VIEW_ALL','SALES_CREATE','SALES_UPDATE_ALL','QUOTES_VIEW','QUOTES_MANAGE','PIPELINES_MANAGE','POS_USE','POS_CHECKOUT_ALL','PRODUCTS_VIEW','PRODUCTS_MANAGE','STOCK_ADJUST','REPORTS_VIEW_OPERATIONAL','OPERATIONS_VIEW_ALL','OPERATIONS_MANAGE','TEAM_VIEW','BUSINESS_SETTINGS_VIEW'];
export const PROFILE_CAPABILITIES: Record<AccessProfile, Capability[]> = { PRACTITIONER: practitioner, RECEPTIONIST: receptionist, MANAGER: manager };

const OWNER_ONLY_CAPABILITIES: readonly Capability[] = [
  'TEAM_MANAGE','FINANCE_VIEW','REFUNDS_CREATE','PAYMENT_INTEGRATION_MANAGE','BUSINESS_SETTINGS_MANAGE','REPORTS_VIEW_FINANCIAL',
  'REPUTATION_MANAGE','REPUTATION_CONNECTIONS_MANAGE','REPUTATION_REPLY',
];

export function effectiveCapabilities(role: 'owner' | 'staff', profile: AccessProfile = 'PRACTITIONER', overrides: Record<string, boolean> = {}): Capability[] {
  if (role === 'owner') return [...CAPABILITIES];
  return PROFILE_CAPABILITIES[profile]
    .filter((capability) => overrides[capability] !== false)
    .concat(CAPABILITIES.filter((capability) => overrides[capability] === true && !PROFILE_CAPABILITIES[profile].includes(capability) && !OWNER_ONLY_CAPABILITIES.includes(capability)));
}
