import {
  DEFAULT_PUBLICATION_POLICY_VERSION,
  SITE_QUALITY_ENGINE_VERSION,
  SITE_QUALITY_VIEWPORTS,
  SiteQualityCheckDefinitionSchema,
  type SiteQualityAuditType,
  type SiteQualityCategory,
  type SiteQualityCheckDefinition,
} from './contracts.js';

const check = (
  value: Omit<SiteQualityCheckDefinition, 'engineVersion'>,
): SiteQualityCheckDefinition => SiteQualityCheckDefinitionSchema.parse({
  ...value,
  engineVersion: SITE_QUALITY_ENGINE_VERSION,
});

const definitions: SiteQualityCheckDefinition[] = [
  check({
    checkId: 'KSQ_PLATFORM_SNAPSHOT_VALID',
    category: 'PUBLICATION_READINESS',
    name: 'Snapshot structure is valid',
    description: 'The exact version satisfies the controlled public snapshot schema.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['PLATFORM_SNAPSHOT_STRUCTURE'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Snapshot schema result and digest'],
    remediationGuidance: 'Regenerate or repair the structured version through the controlled workflow.',
  }),
  check({
    checkId: 'KSQ_PLATFORM_VERSION_COMPLETE',
    category: 'PUBLICATION_READINESS',
    name: 'Version is complete and current',
    description: 'The target version is complete, reviewable, and not superseded.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['PLATFORM_VERSION_LIFECYCLE'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Version status and immutable digest'],
    remediationGuidance: 'Complete generation or select the current reviewable version.',
  }),
  check({
    checkId: 'KSQ_PLATFORM_TENANT_ISOLATION',
    category: 'PUBLICATION_READINESS',
    name: 'Tenant and site ownership',
    description: 'All run, version, page, booking, and canonical references share one tenant and site.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['PLATFORM_TENANT_ISOLATION'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Server-side ownership resolution'],
    remediationGuidance: 'Reject the run and investigate the ownership boundary.',
  }),
  check({
    checkId: 'KSQ_TECH_SEO_RENDERABLE',
    category: 'TECHNICAL_SEO',
    name: 'Pages render successfully',
    description: 'Every active public page returns a successful document with main content.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_PUBLIC_RENDERABILITY'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['HTTP status and main-content result'],
    remediationGuidance: 'Repair the renderer or page structure and rerun the audit.',
  }),
  check({
    checkId: 'KSQ_TECH_SEO_CANONICAL',
    category: 'TECHNICAL_SEO',
    name: 'Canonical URL is correct',
    description: 'Rendered pages expose one controlled canonical URL matching the page path.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_CANONICAL_URL'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Structured SEO metadata and rendered canonical link'],
    remediationGuidance: 'Correct canonical metadata using the structured generation workflow.',
  }),
  check({
    checkId: 'KSQ_TECH_SEO_PREVIEW_NOINDEX',
    category: 'TECHNICAL_SEO',
    name: 'Preview is not indexable',
    description: 'Secure audit previews use noindex, nofollow and no-store.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['PLATFORM_SECURE_PREVIEW'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Robots metadata and response cache headers'],
    remediationGuidance: 'Repair preview response headers and robots metadata.',
  }),
  check({
    checkId: 'KSQ_ONPAGE_TITLE_DESCRIPTION',
    category: 'ON_PAGE_SEO',
    name: 'Title and description are complete',
    description: 'Each indexable page has bounded, useful title and description metadata.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_PAGE_METADATA'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Structured metadata and rendered head'],
    remediationGuidance: 'Regenerate or correct page metadata.',
  }),
  check({
    checkId: 'KSQ_ONPAGE_SINGLE_H1',
    category: 'ON_PAGE_SEO',
    name: 'Page has one primary heading',
    description: 'Each rendered marketing page has exactly one h1.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_HEADING_HIERARCHY'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Rendered heading count'],
    remediationGuidance: 'Adjust the registered page renderer or structured heading content.',
  }),
  check({
    checkId: 'KSQ_LOCAL_CANONICAL_FACTS',
    category: 'LOCAL_SEO',
    name: 'Local facts use canonical records',
    description: 'Trading name, public phone, address, and opening hours match canonical records.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_LOCAL_FACT_CONSISTENCY'],
    applicablePageTypes: ['HOME', 'LOCATION_HUB', 'LOCATION_DETAIL', 'CONTACT'],
    applicableSectionTypes: ['LOCATION', 'OPENING_HOURS', 'CONTACT', 'FOOTER'],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Canonical record references and fact digests'],
    remediationGuidance: 'Correct the canonical business record and regenerate affected content.',
  }),
  check({
    checkId: 'KSQ_STRUCTURED_DATA_VALID',
    category: 'STRUCTURED_DATA',
    name: 'Structured data is valid',
    description: 'JSON-LD is syntactically valid, appropriate, and derived from canonical facts.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_STRUCTURED_DATA'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Rendered JSON-LD types and validation result'],
    remediationGuidance: 'Regenerate structured data from canonical site records.',
  }),
  check({
    checkId: 'KSQ_A11Y_AUTOMATED_WCAG22_AA',
    category: 'ACCESSIBILITY',
    name: 'Automated WCAG 2.2 A/AA checks',
    description: 'Rendered content passes applicable automated WCAG 2.2 A and AA checks.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['WCAG_2_2_AA'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Axe violation IDs, impact, and safe node counts'],
    remediationGuidance: 'Correct the component or content accessibility defect.',
  }),
  check({
    checkId: 'KSQ_A11Y_PRIMARY_KEYBOARD',
    category: 'ACCESSIBILITY',
    name: 'Primary journey is keyboard accessible',
    description: 'The primary booking journey is reachable and usable by keyboard without a focus trap.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['WCAG_2_1_1', 'WCAG_2_4_3'],
    applicablePageTypes: [],
    applicableSectionTypes: ['HERO', 'SERVICE_DETAILS', 'BOOKING_CTA', 'FINAL_CTA'],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Keyboard traversal and focus-trap result'],
    remediationGuidance: 'Repair focus order, keyboard handling, or obstructing elements.',
  }),
  check({
    checkId: 'KSQ_A11Y_IMAGE_ALTERNATIVES',
    category: 'ACCESSIBILITY',
    name: 'Images have appropriate alternatives',
    description: 'Informative images have alt text and decorative images use an empty alternative.',
    validationMethod: 'MIXED',
    ruleIds: ['WCAG_1_1_1'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Structured asset purpose and rendered image summary'],
    remediationGuidance: 'Add a concise alternative or mark the image decorative.',
  }),
  check({
    checkId: 'KSQ_RESPONSIVE_NO_OVERFLOW',
    category: 'RESPONSIVE_UX',
    name: 'No horizontal overflow or clipping',
    description: 'Representative viewports have no material horizontal overflow or clipped controls.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_RESPONSIVE_LAYOUT'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Viewport dimensions and overflow metrics'],
    remediationGuidance: 'Repair the component layout at the failing viewport.',
  }),
  check({
    checkId: 'KSQ_RESPONSIVE_TOUCH_TARGETS',
    category: 'RESPONSIVE_UX',
    name: 'Touch targets are usable',
    description: 'Primary interactive targets meet the policy minimum at touch viewports.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['WCAG_2_5_8'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Safe count of undersized interactive targets'],
    remediationGuidance: 'Increase target size or spacing for affected controls.',
  }),
  check({
    checkId: 'KSQ_CONVERSION_PRIMARY_ACTION',
    category: 'CONVERSION',
    name: 'Primary conversion action is present',
    description: 'Conversion pages expose a clear native booking action above or within the primary journey.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_PRIMARY_CONVERSION_ACTION'],
    applicablePageTypes: [],
    applicableSectionTypes: ['HERO', 'SERVICE_DETAILS', 'STAFF_PROFILE', 'BOOKING_CTA', 'FINAL_CTA'],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Structured booking action and rendered visibility'],
    remediationGuidance: 'Add a KS OS native booking action through structured generation.',
  }),
  check({
    checkId: 'KSQ_CONVERSION_MOBILE_BOOKING',
    category: 'CONVERSION',
    name: 'Mobile booking action is visible',
    description: 'The primary booking action remains visible and usable on representative mobile viewports.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_MOBILE_BOOKING_ACTION'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Mobile viewport booking visibility'],
    remediationGuidance: 'Repair responsive layout or action placement.',
  }),
  check({
    checkId: 'KSQ_BOOKING_NATIVE_ONLY',
    category: 'BOOKING_INTEGRITY',
    name: 'Booking uses KS OS native routes',
    description: 'All booking actions use controlled KS OS references and no external booking destination.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_NATIVE_BOOKING_DESTINATION'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Action discriminator and server-side reference resolution'],
    remediationGuidance: 'Replace the destination with a controlled KS OS booking action.',
  }),
  check({
    checkId: 'KSQ_BOOKING_CANONICAL_REFERENCES',
    category: 'BOOKING_INTEGRITY',
    name: 'Booking references are canonical',
    description: 'Service, location, and staff references resolve within the same tenant and eligibility graph.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['RUL_CANONICAL_BOOKING_RECORDS'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Server-side canonical record resolution'],
    remediationGuidance: 'Correct canonical eligibility or regenerate the action.',
  }),
  check({
    checkId: 'KSQ_CONTENT_NO_EXECUTABLE',
    category: 'CONTENT_INTEGRITY',
    name: 'Content contains no executable injection',
    description: 'Structured content contains no scripts, event handlers, or unsafe arbitrary HTML.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['PLATFORM_NO_EXECUTABLE_CONTENT'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Safe field paths only'],
    remediationGuidance: 'Remove the unsafe content and regenerate through controlled components.',
  }),
  check({
    checkId: 'KSQ_CONTENT_CLAIMS_SUPPORTED',
    category: 'TRUST_AND_FACTUAL_INTEGRITY',
    name: 'Public claims are supported',
    description: 'Prices, locations, credentials, testimonials, reviews, and sensitive claims are verified.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_CLAIM_SUPPORT'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Claim status and canonical fact references'],
    remediationGuidance: 'Remove or verify the unsupported claim in the review workflow.',
  }),
  check({
    checkId: 'KSQ_INTERNAL_LINKS_VALID',
    category: 'INTERNAL_LINKING',
    name: 'Internal links resolve',
    description: 'Structured and rendered internal links target active pages in the exact version.',
    validationMethod: 'MIXED',
    ruleIds: ['RUL_INTERNAL_LINKS'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Link target references and rendered status'],
    remediationGuidance: 'Update the structured internal link or page navigation.',
  }),
  check({
    checkId: 'KSQ_ASSETS_APPROVED',
    category: 'ASSET_READINESS',
    name: 'Public assets are approved and ready',
    description: 'Referenced assets are approved, safe, HTTPS, and include required dimensions and alternatives.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['RUL_PUBLIC_ASSET_READINESS'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Asset reference, status, metadata, and digest'],
    remediationGuidance: 'Approve, replace, or remove the affected asset.',
  }),
  check({
    checkId: 'KSQ_PERFORMANCE_RENDER',
    category: 'PERFORMANCE',
    name: 'Critical rendering performance',
    description: 'Pages complete load, render main content, pass lab Core Web Vitals gates, and avoid critical or misconfigured LCP resources.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_CRITICAL_RENDER_PERFORMANCE'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['LCP, INP, CLS, measurement mode, viewport, LCP element and critical-resource metrics'],
    remediationGuidance: 'Repair failing resources, Core Web Vitals regressions, or LCP discovery and loading behaviour.',
  }),
  check({
    checkId: 'KSQ_PERFORMANCE_ADVISORY',
    category: 'PERFORMANCE',
    name: 'Advisory lab performance',
    description: 'Lab performance remains within the versioned policy advisory thresholds.',
    validationMethod: 'RENDERED_BROWSER',
    ruleIds: ['RUL_LAB_PERFORMANCE'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'WARNING',
    publicationEffect: 'WARNING',
    waivable: true,
    evidenceRequirements: ['Metric value, unit, threshold, viewport, and tool version'],
    remediationGuidance: 'Optimise assets, layout, or rendering without changing canonical content.',
  }),
  check({
    checkId: 'KSQ_REVIEW_APPROVAL_FRESH',
    category: 'REVIEW_AND_APPROVAL',
    name: 'Required approvals are current',
    description: 'Agency and required client approvals match the exact site-version content digest.',
    validationMethod: 'DETERMINISTIC',
    ruleIds: ['PLATFORM_APPROVAL_FRESHNESS'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Approval level, digest, invalidation state, and review revision'],
    remediationGuidance: 'Complete approval for the current digest through the review workflow.',
  }),
  check({
    checkId: 'KSQ_HUMAN_TRUST_REVIEW',
    category: 'TRUST_AND_FACTUAL_INTEGRITY',
    name: 'Human trust review',
    description: 'An authorised agency reviewer confirms tone, trust interpretation, and qualitative presentation.',
    validationMethod: 'HUMAN_REVIEW',
    ruleIds: ['RUL_HUMAN_TRUST_REVIEW'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'BLOCKING',
    publicationEffect: 'BLOCK',
    waivable: false,
    evidenceRequirements: ['Durable agency decision'],
    remediationGuidance: 'Complete the required Site Studio human-review task.',
  }),
  check({
    checkId: 'KSQ_AI_QUALITATIVE_REVIEW',
    category: 'TRUST_AND_FACTUAL_INTEGRITY',
    name: 'Optional AI-assisted qualitative review',
    description: 'A configured provider may identify bounded qualitative concerns without deciding publication readiness.',
    validationMethod: 'AI_REVIEW',
    ruleIds: ['RUL_AI_REVIEW_ADVISORY_ONLY'],
    applicablePageTypes: [],
    applicableSectionTypes: [],
    severity: 'INFO',
    publicationEffect: 'RECOMMENDATION',
    waivable: true,
    evidenceRequirements: ['Provider key, model version, bounded result, and output digest'],
    remediationGuidance: 'Review any advisory concern through the agency-controlled human workflow.',
  }),
];

const categoryByAudit: Record<SiteQualityAuditType, readonly SiteQualityCategory[]> = {
  FULL_SITE_QUALITY: [
    'TECHNICAL_SEO',
    'ON_PAGE_SEO',
    'LOCAL_SEO',
    'STRUCTURED_DATA',
    'ACCESSIBILITY',
    'RESPONSIVE_UX',
    'CONVERSION',
    'BOOKING_INTEGRITY',
    'CONTENT_INTEGRITY',
    'PERFORMANCE',
    'INTERNAL_LINKING',
    'ASSET_READINESS',
    'TRUST_AND_FACTUAL_INTEGRITY',
    'REVIEW_AND_APPROVAL',
    'PUBLICATION_READINESS',
  ],
  TECHNICAL_SEO: ['TECHNICAL_SEO'],
  ON_PAGE_SEO: ['ON_PAGE_SEO'],
  LOCAL_SEO: ['LOCAL_SEO'],
  STRUCTURED_DATA: ['STRUCTURED_DATA'],
  ACCESSIBILITY: ['ACCESSIBILITY'],
  RESPONSIVE_UX: ['RESPONSIVE_UX'],
  CONVERSION: ['CONVERSION'],
  BOOKING_INTEGRITY: ['BOOKING_INTEGRITY'],
  CONTENT_INTEGRITY: ['CONTENT_INTEGRITY', 'TRUST_AND_FACTUAL_INTEGRITY'],
  PERFORMANCE: ['PERFORMANCE'],
  INTERNAL_LINKING: ['INTERNAL_LINKING'],
  ASSET_READINESS: ['ASSET_READINESS'],
  PUBLICATION_READINESS: ['PUBLICATION_READINESS', 'REVIEW_AND_APPROVAL'],
};

export interface SiteQualityPolicy {
  version: typeof DEFAULT_PUBLICATION_POLICY_VERSION;
  requiredAuditCategories: readonly SiteQualityCategory[];
  requiredViewportKeys: readonly (typeof SITE_QUALITY_VIEWPORTS)[number]['key'][];
  requiredCheckIds: readonly string[];
  humanReviewCheckIds: readonly string[];
  thresholds: {
    pageLoadWarningMs: number;
    mainContentWarningMs: number;
    largestContentfulPaintBlockingMs: number;
    interactionToNextPaintBlockingMs: number;
    cumulativeLayoutShiftBlocking: number;
    cumulativeLayoutShiftWarning: number;
    transferBytesWarning: number;
    maximumImageTransferBytes: number;
    maximumHorizontalOverflowPixels: number;
    minimumTouchTargetPixels: number;
  };
}

export const DEFAULT_SITE_QUALITY_POLICY: SiteQualityPolicy = Object.freeze({
  version: DEFAULT_PUBLICATION_POLICY_VERSION,
  requiredAuditCategories: categoryByAudit.FULL_SITE_QUALITY,
  requiredViewportKeys: SITE_QUALITY_VIEWPORTS.map((viewport) => viewport.key),
  requiredCheckIds: definitions
    .filter((definition) => definition.validationMethod !== 'AI_REVIEW')
    .map((definition) => definition.checkId),
  humanReviewCheckIds: definitions
    .filter((definition) => definition.validationMethod === 'HUMAN_REVIEW')
    .map((definition) => definition.checkId),
  thresholds: {
    pageLoadWarningMs: 4_000,
    mainContentWarningMs: 2_500,
    largestContentfulPaintBlockingMs: 2_500,
    interactionToNextPaintBlockingMs: 200,
    cumulativeLayoutShiftBlocking: 0.1,
    cumulativeLayoutShiftWarning: 0.05,
    transferBytesWarning: 3_000_000,
    maximumImageTransferBytes: 500_000,
    maximumHorizontalOverflowPixels: 0,
    minimumTouchTargetPixels: 24,
  },
});

export function qualityCheckRegistry(): readonly SiteQualityCheckDefinition[] {
  return definitions;
}

export function qualityCheckById(checkId: string) {
  return definitions.find((definition) => definition.checkId === checkId);
}

export function checksForAuditType(
  auditType: SiteQualityAuditType,
): readonly SiteQualityCheckDefinition[] {
  const categories = new Set(categoryByAudit[auditType]);
  return definitions.filter((definition) => categories.has(definition.category));
}

export function auditCategories(
  auditType: SiteQualityAuditType,
): readonly SiteQualityCategory[] {
  return categoryByAudit[auditType];
}
