import { and, asc, desc, eq, inArray, sql } from 'drizzle-orm';
import {
  appointments, automationActionRuns, automationRuleActions, automationRules, automationRuns, businessEvents,
  clients, emailOutbox, formAssignments, forms, getDatabase, internalNotifications, services, smsOutbox, tenants, users,
} from '@ks-os/database';
import { AutomationActionSchema, AutomationConditionSchema, CreateAutomationSchema, TriggerSchema, type AutomationAction, type AutomationCondition, type CreateAutomationInput } from '@ks-os/contracts';
import { EmailService } from '../email/email.service.js';
import { OperationsIssueReporter } from '../operations/operations.issue-service.js';
import { SmsService } from '../sms/sms.service.js';
import { FormsService } from '../forms/forms.service.js';
import { env } from '../../config/env.js';
import {TaskService} from '../tasks/task.service.js';
import { ReviewInvitationService } from '../reputation/review-invitation.service.js';

type Actor = { tenantId: string; userId: string; role: 'owner' | 'staff' };
const fail = (statusCode: number, code: string, message: string) => Object.assign(new Error(message), { statusCode, code });
const owner = (actor: Actor) => { if (actor.role !== 'owner') throw fail(403, 'AUTOMATION_ACCESS_DENIED', 'Owner access is required.'); };
const notificationCopy: Record<string, [string, string]> = {
  FORM_COMPLETED: ['Form completed', 'A client form was completed.'], AUTOMATION_FAILED: ['Automation failed', 'An automation action needs attention.'],
  SMS_DELIVERY_FAILED: ['SMS delivery failed', 'An SMS could not be delivered.'], STRIPE_ACTION_REQUIRED: ['Stripe action required', 'Your Stripe account needs attention.'],
  PAYMENT_DISPUTE_ACTION_REQUIRED: ['Payment dispute action required', 'A payment dispute needs attention.'],
};

export class AutomationService {
  private db = getDatabase();
  private issues = new OperationsIssueReporter();
  private reviewInvitations = new ReviewInvitationService();

  async list(actor: Actor) { owner(actor); return this.db.select().from(automationRules).where(eq(automationRules.tenantId, actor.tenantId)).orderBy(desc(automationRules.updatedAt)); }
  async get(actor: Actor, id: string) {
    owner(actor); const [rule] = await this.db.select().from(automationRules).where(and(eq(automationRules.id,id),eq(automationRules.tenantId,actor.tenantId))).limit(1);
    if (!rule) throw fail(404,'AUTOMATION_NOT_FOUND','Automation not found.');
    const actions = await this.db.select().from(automationRuleActions).where(and(eq(automationRuleActions.automationRuleId,id),eq(automationRuleActions.tenantId,actor.tenantId))).orderBy(asc(automationRuleActions.position));
    return { ...rule, trigger: { type: rule.triggerType, config: rule.triggerConfigJson }, conditions: rule.conditionsJson, actions: actions.map((a) => ({ id:a.id, type:a.actionType, ...(a.actionConfigJson as object) })) };
  }
  async create(actor: Actor, value: unknown) { owner(actor); const input=CreateAutomationSchema.parse(value); const id=await this.db.transaction(async(tx)=>{
    const [rule]=await tx.insert(automationRules).values({tenantId:actor.tenantId,name:input.name,description:input.description,status:'DRAFT',triggerType:input.trigger.type,triggerConfigJson:input.trigger.config,conditionsJson:input.conditions,createdByUserId:actor.userId,updatedByUserId:actor.userId}).returning();
    await tx.insert(automationRuleActions).values(input.actions.map((action,position)=>{const {type,...config}=action;return{tenantId:actor.tenantId,automationRuleId:rule.id,position,actionType:type,actionConfigJson:config};})); return rule.id;
  }); return this.get(actor,id); }
  async update(actor: Actor,id:string,value:unknown){owner(actor);const current=await this.get(actor,id);if(current.status!=='DRAFT'&&current.status!=='PAUSED')throw fail(409,'AUTOMATION_ALREADY_ACTIVE','Pause the automation before editing it.');const base={name:current.name,description:current.description,trigger:current.trigger,conditions:current.conditions,actions:current.actions.map(({id:_,...action}:any)=>action)};const merged=CreateAutomationSchema.parse({...base,...(value as object)});await this.db.transaction(async(tx)=>{await tx.update(automationRules).set({name:merged.name,description:merged.description,triggerType:merged.trigger.type,triggerConfigJson:merged.trigger.config,conditionsJson:merged.conditions,updatedByUserId:actor.userId,updatedAt:new Date()}).where(and(eq(automationRules.id,id),eq(automationRules.tenantId,actor.tenantId)));await tx.delete(automationRuleActions).where(and(eq(automationRuleActions.automationRuleId,id),eq(automationRuleActions.tenantId,actor.tenantId)));await tx.insert(automationRuleActions).values(merged.actions.map((action,position)=>{const{type,...config}=action;return{tenantId:actor.tenantId,automationRuleId:id,position,actionType:type,actionConfigJson:config};}));});return this.get(actor,id);}
  async activate(actor:Actor,id:string){owner(actor);const rule=await this.get(actor,id);if(rule.status==='ACTIVE')throw fail(409,'AUTOMATION_ALREADY_ACTIVE','Automation is already active.');const summary=await this.validate(actor,rule);if(!summary.valid)throw fail(409,'AUTOMATION_REFERENCE_NOT_FOUND',summary.errors.join(' '));const [{count}]=await this.db.select({count:sql<number>`count(*)::int`}).from(automationRules).where(and(eq(automationRules.tenantId,actor.tenantId),eq(automationRules.status,'ACTIVE')));if(count>=25)throw fail(409,'AUTOMATION_LIMIT_REACHED','Maximum active automation rules reached.');await this.db.update(automationRules).set({status:'ACTIVE',enabledAt:new Date(),disabledAt:null,updatedAt:new Date(),updatedByUserId:actor.userId}).where(and(eq(automationRules.id,id),eq(automationRules.tenantId,actor.tenantId)));return summary;}
  async setStatus(actor:Actor,id:string,status:'PAUSED'|'ARCHIVED'){owner(actor);const rule=await this.get(actor,id);if(status==='PAUSED'&&rule.status!=='ACTIVE')throw fail(409,'AUTOMATION_NOT_ACTIVE','Automation is not active.');await this.db.update(automationRules).set({status,disabledAt:new Date(),updatedAt:new Date(),updatedByUserId:actor.userId}).where(and(eq(automationRules.id,id),eq(automationRules.tenantId,actor.tenantId)));}
  async validate(actor:Actor,rule:any){const errors:string[]=[];try{TriggerSchema.parse(rule.trigger);(rule.conditions as unknown[]).forEach((x)=>AutomationConditionSchema.parse(x));(rule.actions as unknown[]).forEach((x)=>AutomationActionSchema.parse(x));}catch{errors.push('Configuration schema is invalid.');}
    for(const condition of rule.conditions as any[]){if(condition.serviceId&&!await this.exists(services,services.id,condition.serviceId,actor.tenantId))errors.push('Referenced service was not found.');if(condition.staffId&&!await this.exists(users,users.id,condition.staffId,actor.tenantId))errors.push('Referenced staff member was not found.');}
    for(const action of rule.actions as any[]){if(action.formId&&!await this.exists(forms,forms.id,action.formId,actor.tenantId))errors.push('Referenced form was not found.');if(action.type==='CREATE_TASK'&&action.assignTo==='SPECIFIC_USER'&&(!action.specificUserId||!await this.exists(users,users.id,action.specificUserId,actor.tenantId)))errors.push('Referenced task assignee was not found.');}
    return{valid:errors.length===0,errors};}
  private async exists(table:any,idColumn:any,id:string,tenantId:string){const [row]=await this.db.select({id:idColumn}).from(table).where(and(eq(idColumn,id),eq(table.tenantId,tenantId))).limit(1);return!!row;}
  async runs(actor:Actor,automationId:string){owner(actor);await this.get(actor,automationId);return this.db.select().from(automationRuns).where(and(eq(automationRuns.automationRuleId,automationId),eq(automationRuns.tenantId,actor.tenantId))).orderBy(desc(automationRuns.createdAt)).limit(100);}
  async runDetail(actor:Actor,runId:string){owner(actor);const[run]=await this.db.select().from(automationRuns).where(and(eq(automationRuns.id,runId),eq(automationRuns.tenantId,actor.tenantId))).limit(1);if(!run)throw fail(404,'AUTOMATION_RUN_NOT_FOUND','Automation run not found.');const actions=await this.db.select().from(automationActionRuns).where(and(eq(automationActionRuns.automationRunId,runId),eq(automationActionRuns.tenantId,actor.tenantId))).orderBy(asc(automationActionRuns.createdAt));return{...run,actions};}

  async processEvents(limit=20){const claimed=await this.db.execute(sql`UPDATE business_events SET status='PROCESSING',attempt_count=attempt_count+1 WHERE id IN (SELECT id FROM business_events WHERE status IN ('PENDING','FAILED') AND next_attempt_at<=now() ORDER BY occurred_at FOR UPDATE SKIP LOCKED LIMIT ${limit}) RETURNING *`);for(const event of claimed.rows as any[]){try{if(event.event_type==='APPOINTMENT_COMPLETED'&&event.source_type==='appointment')await this.reviewInvitations.scheduleFromCompletion(event.tenant_id,event.source_id,new Date(event.occurred_at));const scheduledRuleId=(event.payload_json as any)?.automationRuleId;const rules=await this.db.select().from(automationRules).where(and(eq(automationRules.tenantId,event.tenant_id),eq(automationRules.status,'ACTIVE'),eq(automationRules.triggerType,event.event_type),scheduledRuleId?eq(automationRules.id,scheduledRuleId):undefined));for(const rule of rules)await this.startRun(rule,event);await this.db.update(businessEvents).set({status:'PROCESSED',processedAt:new Date(),lastErrorCode:null}).where(eq(businessEvents.id,event.id));}catch(error){const attempts=Number(event.attempt_count)+1;await this.db.update(businessEvents).set({status:attempts>=5?'FAILED':'PENDING',nextAttemptAt:new Date(Date.now()+Math.min(2**attempts,60)*60000),lastErrorCode:'AUTOMATION_EXECUTION_FAILED'}).where(eq(businessEvents.id,event.id));}}return{claimed:claimed.rows.length};}
  async generateScheduledEvents(limit=100){const rules=await this.db.select().from(automationRules).where(and(eq(automationRules.status,'ACTIVE'),inArray(automationRules.triggerType,['SCHEDULED_BEFORE_APPOINTMENT','SCHEDULED_AFTER_APPOINTMENT']))).limit(25);let created=0;for(const rule of rules){const offset=Number((rule.triggerConfigJson as any).offsetMinutes);const rows=await this.db.select({id:appointments.id,startTime:appointments.startTime,endTime:appointments.endTime,status:appointments.status}).from(appointments).where(and(eq(appointments.tenantId,rule.tenantId),inArray(appointments.status,['CONFIRMED','COMPLETED']))).limit(limit);for(const appointment of rows){const anchor=rule.triggerType==='SCHEDULED_BEFORE_APPOINTMENT'?appointment.startTime:appointment.endTime;const due=new Date(anchor.getTime()+(rule.triggerType==='SCHEDULED_BEFORE_APPOINTMENT'?-offset:offset)*60000);if(due>new Date())continue;if(rule.triggerType==='SCHEDULED_BEFORE_APPOINTMENT'&&appointment.startTime<=new Date())continue;const id=`${rule.triggerType}:${rule.id}:${appointment.id}:${anchor.toISOString()}`;const inserted=await this.db.insert(businessEvents).values({id,tenantId:rule.tenantId,eventType:rule.triggerType,sourceType:'appointment',sourceId:appointment.id,payloadJson:{automationRuleId:rule.id,appointmentId:appointment.id,offsetMinutes:offset},occurredAt:due}).onConflictDoNothing({target:businessEvents.id}).returning({id:businessEvents.id});created+=inserted.length;}}return{created};}
  private async startRun(rule:any,event:any){const context=await this.context(event.tenant_id,event.source_id,event.source_type);if(!this.matches(rule.conditionsJson as AutomationCondition[],context))return;const[run]=await this.db.insert(automationRuns).values({tenantId:event.tenant_id,automationRuleId:rule.id,triggerType:event.event_type,triggerEventId:event.id,sourceType:event.source_type,sourceId:event.source_id,status:'RUNNING',startedAt:new Date()}).onConflictDoNothing({target:[automationRuns.automationRuleId,automationRuns.triggerEventId]}).returning();if(!run)return;const actions=await this.db.select().from(automationRuleActions).where(eq(automationRuleActions.automationRuleId,rule.id)).orderBy(asc(automationRuleActions.position));for(const action of actions){const config={type:action.actionType,...action.actionConfigJson as object} as AutomationAction;const scheduledFor=this.schedule(config,context.startTime);await this.db.insert(automationActionRuns).values({tenantId:event.tenant_id,automationRunId:run.id,automationRuleActionId:action.id,status:scheduledFor>new Date()?'SCHEDULED':'PENDING',idempotencyKey:`automation:${rule.id}:${event.id}:${action.id}`,scheduledFor,nextAttemptAt:scheduledFor});}await this.db.update(automationRuns).set({status:'PENDING'}).where(eq(automationRuns.id,run.id));}
  private schedule(action:AutomationAction,startTime?:Date){if((action.type==='SCHEDULE_EMAIL'||action.type==='SCHEDULE_SMS')&&startTime)return new Date(startTime.getTime()-action.offsetMinutes*60000);return new Date();}
  private matches(conditions:AutomationCondition[],c:any){return conditions.every((x:any)=>x.type==='SERVICE_EQUALS'?c.serviceId===x.serviceId:x.type==='BOOKING_CHANNEL_EQUALS'?c.bookingChannel===x.bookingChannel:x.type==='STAFF_EQUALS'?c.staffId===x.staffId:x.type==='APPOINTMENT_STATUS_EQUALS'?c.status===x.status:x.type==='PAYMENT_STATUS_EQUALS'?c.paymentStatus===x.status:x.type==='CLIENT_HAS_EMAIL'?!!c.email:x.type==='CLIENT_HAS_SMS_NUMBER'?!!c.phone:x.type==='FORM_IS_INCOMPLETE'?c.formIncomplete:x.type==='TENANT_EMAIL_ENABLED'?c.emailEnabled:x.type==='TENANT_SMS_ENABLED'?c.smsEnabled:false);}
  private async context(tenantId:string,sourceId:string,sourceType='appointment'){let appointmentId=sourceId;if(sourceType==='form_assignment'){const[assignment]=await this.db.select({appointmentId:formAssignments.appointmentId}).from(formAssignments).where(and(eq(formAssignments.id,sourceId),eq(formAssignments.tenantId,tenantId))).limit(1);appointmentId=assignment?.appointmentId||'';}const[row]=await this.db.select({appointmentId:appointments.id,status:appointments.status,startTime:appointments.startTime,serviceId:appointments.serviceId,staffId:appointments.userId,bookingChannel:appointments.bookingChannel,paymentStatus:appointments.paymentStatus,clientId:clients.id,clientName:clients.name,email:clients.email,phone:clients.phone,tenantName:tenants.name,primaryColor:tenants.primaryColor,replyToEmail:tenants.replyToEmail,emailEnabled:tenants.bookingConfirmationEnabled,smsEnabled:tenants.smsEnabled,timezone:tenants.timezone,serviceName:services.name,staffName:users.name}).from(appointments).leftJoin(clients,eq(clients.id,appointments.clientId)).leftJoin(tenants,eq(tenants.id,appointments.tenantId)).leftJoin(services,eq(services.id,appointments.serviceId)).leftJoin(users,eq(users.id,appointments.userId)).where(and(eq(appointments.id,appointmentId),eq(appointments.tenantId,tenantId))).limit(1);const[pending]=row?await this.db.select({id:formAssignments.id}).from(formAssignments).where(and(eq(formAssignments.tenantId,tenantId),eq(formAssignments.appointmentId,row.appointmentId),inArray(formAssignments.status,['PENDING','OPENED']))).limit(1):[];return{...row,formIncomplete:!!pending};}
  async processActions(limit=20){const claimed=await this.db.execute(sql`UPDATE automation_action_runs SET status='RUNNING',started_at=now(),attempt_count=attempt_count+1 WHERE id IN (SELECT ar.id FROM automation_action_runs ar JOIN automation_rules r ON r.id=(SELECT runs.automation_rule_id FROM automation_runs runs WHERE runs.id=ar.automation_run_id) WHERE ar.status IN ('PENDING','SCHEDULED','FAILED') AND ar.scheduled_for<=now() AND ar.next_attempt_at<=now() AND r.status='ACTIVE' ORDER BY ar.scheduled_for FOR UPDATE OF ar SKIP LOCKED LIMIT ${limit}) RETURNING *`);for(const row of claimed.rows as any[]){try{await this.executeAction(row);await this.db.update(automationActionRuns).set({status:'SUCCEEDED',completedAt:new Date(),lastErrorCode:null}).where(eq(automationActionRuns.id,row.id));await this.issues.resolve(row.tenant_id,`AUTOMATION_ACTION_FAILED:${row.id}`);await this.finishRun(row.automation_run_id);}catch(error:any){const stateChanged=error?.code==='AUTOMATION_STATE_CHANGED';const attempts=Number(row.attempt_count)+1;const failed=attempts>=5;await this.db.update(automationActionRuns).set({status:stateChanged?'SKIPPED':failed?'FAILED':'PENDING',nextAttemptAt:new Date(Date.now()+Math.min(2**attempts,60)*60000),failedAt:failed?new Date():null,lastErrorCode:stateChanged?'AUTOMATION_STATE_CHANGED':'AUTOMATION_EXECUTION_FAILED'}).where(eq(automationActionRuns.id,row.id));if(failed)await this.issues.report({tenantId:row.tenant_id,category:'AUTOMATION',issueType:'AUTOMATION_ACTION_FAILED',severity:'CRITICAL',title:'Automation action failed',message:'An automation action exhausted its delivery attempts.',sourceType:'AUTOMATION_ACTION_RUN',sourceId:row.id,deduplicationKey:`AUTOMATION_ACTION_FAILED:${row.id}`,metadata:{automationRunId:row.automation_run_id,errorCode:'AUTOMATION_EXECUTION_FAILED'}});await this.finishRun(row.automation_run_id);}}return{claimed:claimed.rows.length};}
  private async executeAction(actionRun:any){const[action]=await this.db.select().from(automationRuleActions).where(eq(automationRuleActions.id,actionRun.automation_rule_action_id)).limit(1);const[run]=await this.db.select().from(automationRuns).where(eq(automationRuns.id,actionRun.automation_run_id)).limit(1);if(!action||!run)throw fail(409,'AUTOMATION_STATE_CHANGED','Automation state changed.');const config={type:action.actionType,...action.actionConfigJson as object} as any;const c=await this.context(run.tenantId,run.sourceId,run.sourceType);if(!c.appointmentId||['CANCELLED','COMPLETED','NO_SHOW'].includes(c.status)&&['SCHEDULE_EMAIL','SCHEDULE_SMS'].includes(config.type))throw fail(409,'AUTOMATION_STATE_CHANGED','Appointment state changed.');
    const data={tenantName:c.tenantName,tenantPrimaryColor:c.primaryColor,clientName:c.clientName,customerName:c.clientName,serviceName:c.serviceName,staffName:c.staffName,startTime:c.startTime?.toISOString(),timezone:c.timezone,bookingDate:'',bookingTime:''};
    if(config.type==='SEND_EMAIL'||config.type==='SCHEDULE_EMAIL'){if(!c.email)throw fail(409,'AUTOMATION_STATE_CHANGED','Client has no email.');await new EmailService().enqueueEmail({tenantId:run.tenantId,recipientEmail:c.email,recipientName:c.clientName||undefined,replyToEmail:c.replyToEmail||undefined,templateKey:config.templateKey,templateDataJson:data,idempotencyKey:actionRun.idempotency_key,relatedEntityType:'appointment',relatedEntityId:c.appointmentId,scheduledFor:new Date()},undefined);}
    else if(config.type==='SEND_SMS'||config.type==='SCHEDULE_SMS'){if(!c.phone)throw fail(409,'AUTOMATION_STATE_CHANGED','Client has no mobile number.');await new SmsService().enqueue({tenantId:run.tenantId,clientId:c.clientId||undefined,appointmentId:c.appointmentId,recipientPhone:c.phone,templateKey:config.templateKey,templateData:{appointmentDateTime:new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:c.timezone||'Europe/London'}).format(c.startTime)},idempotencyKey:actionRun.idempotency_key,validUntil:c.startTime||undefined});}
    else if(config.type==='CANCEL_PENDING_REMINDERS'){await this.db.update(emailOutbox).set({status:'CANCELLED'}).where(and(eq(emailOutbox.tenantId,run.tenantId),eq(emailOutbox.relatedEntityId,c.appointmentId),inArray(emailOutbox.status,['PENDING','DELAYED','PROCESSING'])));await new SmsService().cancelAppointmentReminders(run.tenantId,c.appointmentId);await this.db.execute(sql`UPDATE automation_action_runs ar SET status='CANCELLED' WHERE ar.tenant_id=${run.tenantId}::uuid AND ar.status IN ('PENDING','SCHEDULED') AND ar.id<>${actionRun.id}::uuid AND ar.automation_run_id IN (SELECT id FROM automation_runs WHERE tenant_id=${run.tenantId}::uuid AND source_id=${c.appointmentId}::uuid)`);}
    else if(config.type==='CANCEL_PENDING_FORM_ASSIGNMENTS'){await this.db.update(formAssignments).set({status:'CANCELLED',cancelledAt:new Date(),updatedAt:new Date()}).where(and(eq(formAssignments.tenantId,run.tenantId),eq(formAssignments.appointmentId,c.appointmentId),inArray(formAssignments.status,['PENDING','OPENED'])));}
    else if(config.type==='ASSIGN_FORM'){if(!c.clientId)throw fail(409,'AUTOMATION_STATE_CHANGED','Booking has no client.');const[existing]=await this.db.select({id:formAssignments.id}).from(formAssignments).where(and(eq(formAssignments.tenantId,run.tenantId),eq(formAssignments.formId,config.formId),eq(formAssignments.clientId,c.clientId),config.linkToAppointment?eq(formAssignments.appointmentId,c.appointmentId):undefined,inArray(formAssignments.status,['PENDING','OPENED']))).limit(1);const assigned=existing||await new FormsService().createAssignment({tenantId:run.tenantId,userId:(await this.ruleOwner(run.automationRuleId)),role:'owner'},{formId:config.formId,formVersionId:config.formVersionId,clientId:c.clientId,appointmentId:config.linkToAppointment?c.appointmentId:undefined,deliveryMethod:'COPY_LINK'},env.FORM_ASSIGNMENT_EXPIRY_DAYS);await this.db.update(automationActionRuns).set({resultReferenceType:'form_assignment',resultReferenceId:assigned.id}).where(eq(automationActionRuns.id,actionRun.id));}
    else if(config.type==='CREATE_INTERNAL_NOTIFICATION'){const[title,message]=notificationCopy[config.notificationType];await this.db.insert(internalNotifications).values({tenantId:run.tenantId,recipientRole:'owner',type:config.notificationType,title,message,sourceType:run.sourceType,sourceId:run.sourceId});}
    else if(config.type==='CREATE_TASK'){const createdByUserId=await this.ruleOwner(run.automationRuleId);const task=await new TaskService().createAutomationTask({tenantId:run.tenantId,automationRunId:run.id,idempotencyKey:actionRun.idempotency_key??actionRun.id,createdByUserId,appointmentId:c.appointmentId??undefined,clientId:c.clientId??undefined,appointmentStaffId:c.staffId??undefined,titleTemplateKey:config.titleTemplateKey,assignTo:config.assignTo,specificUserId:config.specificUserId??undefined,dueOffsetMinutes:config.dueOffsetMinutes,priority:config.priority});await this.db.update(automationActionRuns).set({resultReferenceType:'task',resultReferenceId:task.id}).where(eq(automationActionRuns.id,actionRun.id));}
  }
  private async ruleOwner(ruleId:string){const[rule]=await this.db.select({id:automationRules.createdByUserId}).from(automationRules).where(eq(automationRules.id,ruleId));return rule.id;}
  private async finishRun(runId:string){const rows=await this.db.select({status:automationActionRuns.status}).from(automationActionRuns).where(eq(automationActionRuns.automationRunId,runId));if(rows.some(x=>['PENDING','SCHEDULED','RUNNING'].includes(x.status)))return;const failed=rows.filter(x=>x.status==='FAILED').length;await this.db.update(automationRuns).set({status:failed===rows.length?'FAILED':failed?'PARTIALLY_FAILED':'SUCCEEDED',completedAt:new Date(),failedAt:failed?new Date():null,lastErrorCode:failed?'AUTOMATION_EXECUTION_FAILED':null}).where(eq(automationRuns.id,runId));}
  async retry(actor:Actor,actionRunId:string){owner(actor);const[row]=await this.db.select().from(automationActionRuns).where(and(eq(automationActionRuns.id,actionRunId),eq(automationActionRuns.tenantId,actor.tenantId))).limit(1);if(!row||row.status!=='FAILED')throw fail(409,'AUTOMATION_ACTION_NOT_RETRYABLE','Action cannot be retried.');await this.db.update(automationActionRuns).set({status:'PENDING',attemptCount:0,nextAttemptAt:new Date(),failedAt:null,lastErrorCode:null}).where(eq(automationActionRuns.id,actionRunId));}
}
