import type { FastifyInstance, FastifyRequest } from 'fastify';
import { AutomationActionRunIdParamsSchema, AutomationIdParamsSchema, AutomationRunIdParamsSchema, CreateAutomationSchema, UpdateAutomationSchema } from '@ks-os/contracts';
import { AutomationService } from './automation.service.js';
import { ReviewInvitationService } from '../reputation/review-invitation.service.js';
import { ReputationService } from '../reputation/reputation.service.js';
import { EntitlementService } from '../agency/agency.service.js';

const actor=(request:FastifyRequest)=>{request.requireAuth();return{tenantId:request.auth!.tenantId,userId:request.auth!.tenantUserId,role:request.auth!.role};};
export async function automationRoutes(app:FastifyInstance){const service=new AutomationService();const entitlements=new EntitlementService();app.addHook('preHandler',async request=>{request.requireAuth();await entitlements.assertBoolean(request.auth!.tenantId,'automations.enabled');});
  app.get('/',async request=>({data:await service.list(actor(request))}));
  app.post('/',async(request,reply)=>reply.code(201).send({data:await service.create(actor(request),CreateAutomationSchema.parse(request.body))}));
  app.get('/:automationId',async request=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);return{data:await service.get(actor(request),automationId)};});
  app.patch('/:automationId',async request=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);return{data:await service.update(actor(request),automationId,UpdateAutomationSchema.parse(request.body))};});
  app.post('/:automationId/activate',async request=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);return{data:await service.activate(actor(request),automationId)};});
  app.post('/:automationId/pause',async(request,reply)=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);await service.setStatus(actor(request),automationId,'PAUSED');return reply.code(204).send();});
  app.post('/:automationId/archive',async(request,reply)=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);await service.setStatus(actor(request),automationId,'ARCHIVED');return reply.code(204).send();});
  app.get('/:automationId/runs',async request=>{const{automationId}=AutomationIdParamsSchema.parse(request.params);return{data:await service.runs(actor(request),automationId)};});
}
export async function automationRunRoutes(app:FastifyInstance){const service=new AutomationService();const entitlements=new EntitlementService();app.addHook('preHandler',async request=>{request.requireAuth();await entitlements.assertBoolean(request.auth!.tenantId,'automations.enabled');});app.get('/:runId',async request=>{const{runId}=AutomationRunIdParamsSchema.parse(request.params);return{data:await service.runDetail(actor(request),runId)};});}
export async function automationActionRoutes(app:FastifyInstance){const service=new AutomationService();const entitlements=new EntitlementService();app.addHook('preHandler',async request=>{request.requireAuth();await entitlements.assertBoolean(request.auth!.tenantId,'automations.enabled');});app.post('/:actionRunId/retry',async(request,reply)=>{const{actionRunId}=AutomationActionRunIdParamsSchema.parse(request.params);await service.retry(actor(request),actionRunId);return reply.code(204).send();});}
export async function automationWorkerRoutes(app:FastifyInstance){const service=new AutomationService();const reviewInvitations=new ReviewInvitationService();const reputation=new ReputationService();const authorize=(request:FastifyRequest)=>{const supplied=request.headers.authorization?.replace(/^Bearer\s+/i,'');if(!process.env.AUTOMATION_WORKER_SECRET||supplied!==process.env.AUTOMATION_WORKER_SECRET)throw Object.assign(new Error('Unauthorized'),{statusCode:401,code:'UNAUTHENTICATED'});};app.post('/schedules',async request=>{authorize(request);return service.generateScheduledEvents();});app.post('/events',async request=>{authorize(request);return service.processEvents();});app.post('/actions',async request=>{authorize(request);const [actions,reviews,reviewSync]=await Promise.all([service.processActions(),reviewInvitations.processDue(),reputation.syncDueConnections()]);return{...actions,reviewInvitationsClaimed:reviews.claimed,reviewConnectionsClaimed:reviewSync.claimed,externalReviewsSynced:reviewSync.synced,reviewSyncFailed:reviewSync.failed};});}
