import { randomUUID } from 'node:crypto';
import { and, eq, sql } from 'drizzle-orm';
import { agencyExportJobs, getDatabase } from '@ks-os/database';
import { csvLine } from '../reporting/report-csv.js';
import { SupabaseReportStorage } from '../reporting/report-storage.js';

const definitions:Record<string,{headers:string[];query:any}>={
  TENANTS:{headers:['agency_reference','name','legal_business_name','subdomain','lifecycle_status','plan','created_at','launched_at'],query:sql`select t.agency_reference,t.name,t.legal_business_name,t.subdomain,t.lifecycle_status,p.key plan,t.created_at,t.launched_at from tenants t left join tenant_plan_assignments a on a.tenant_id=t.id and a.status='ACTIVE' left join platform_plan_versions v on v.id=a.plan_version_id left join platform_plans p on p.id=v.plan_id order by t.created_at desc limit 10000`},
  SUBSCRIPTIONS:{headers:['tenant_reference','tenant_name','plan','status','amount_minor','currency','next_charge_at','grace_ends_at','created_at'],query:sql`select t.agency_reference tenant_reference,t.name tenant_name,p.key plan,s.status,s.amount_minor,s.currency,s.next_charge_at,s.grace_ends_at,s.created_at from tenant_subscriptions s join tenants t on t.id=s.tenant_id join platform_plan_versions v on v.id=s.plan_version_id join platform_plans p on p.id=v.plan_id order by s.created_at desc limit 10000`},
  ONBOARDING:{headers:['tenant_reference','tenant_name','status','completion_percentage','current_stage','target_launch_at','launched_at','next_action'],query:sql`select t.agency_reference tenant_reference,t.name tenant_name,o.status,o.completion_percentage,o.current_stage,o.target_launch_at,o.launched_at,o.next_action from tenant_onboarding o join tenants t on t.id=o.tenant_id order by o.updated_at desc limit 10000`},
  FULFILMENT:{headers:['tenant_reference','tenant_name','type','title','status','due_at','estimated_minutes','actual_minutes','cost_minor','completed_at'],query:sql`select t.agency_reference tenant_reference,t.name tenant_name,d.type,d.title,d.status,d.due_at,d.estimated_minutes,d.actual_minutes,d.cost_minor,d.completed_at from managed_deliverables d join tenants t on t.id=d.tenant_id order by d.created_at desc limit 10000`},
  AUDIT:{headers:['occurred_at','agency_user_id','tenant_reference','action','target_type','target_id','outcome','reason','request_id'],query:sql`select a.occurred_at,a.agency_user_id,t.agency_reference tenant_reference,a.action,a.target_type,a.target_id,a.outcome,a.reason,a.request_id from platform_audit_events a left join tenants t on t.id=a.tenant_id order by a.occurred_at desc limit 10000`},
};
export class AgencyExportsService{
  private db=getDatabase();private storage=new SupabaseReportStorage();
  async process(limit=3){const claimed=await this.db.execute(sql`with candidates as (select id from agency_export_jobs where status='PENDING' order by requested_at,id for update skip locked limit ${Math.min(10,Math.max(1,limit))}) update agency_export_jobs j set status='PROCESSING' from candidates where j.id=candidates.id returning j.*`);let ready=0,failed=0;for(const job of claimed.rows as any[]){try{const def=definitions[job.export_type];if(!def)throw new Error('Unsupported export');const result=await this.db.execute(def.query);const chunks=[Buffer.from('\uFEFF'+csvLine(def.headers),'utf8')];for(const row of result.rows as any[])chunks.push(Buffer.from(csvLine(def.headers.map(header=>row[header])),'utf8'));const body=Buffer.concat(chunks);if(body.byteLength>10_485_760)throw new Error('Export too large');const path=`agency/${job.id}/${randomUUID()}.csv`;await this.storage.upload(path,body);await this.db.update(agencyExportJobs).set({status:'READY',storagePath:path,rowCount:result.rows.length,completedAt:new Date(),expiresAt:new Date(Date.now()+72*3600000)}).where(and(eq(agencyExportJobs.id,job.id),eq(agencyExportJobs.status,'PROCESSING')));ready++;}catch{await this.db.update(agencyExportJobs).set({status:'FAILED',failureCode:'EXPORT_GENERATION_FAILED',completedAt:new Date()}).where(eq(agencyExportJobs.id,job.id));failed++;}}return{claimed:claimed.rows.length,ready,failed};}
  async download(id:string){const[job]=await this.db.select().from(agencyExportJobs).where(eq(agencyExportJobs.id,id)).limit(1);if(!job)throw Object.assign(new Error('Agency export not found.'),{statusCode:404,code:'EXPORT_NOT_FOUND'});if(job.status!=='READY'||!job.storagePath)throw Object.assign(new Error('Agency export is not ready.'),{statusCode:409,code:'EXPORT_NOT_READY'});if(!job.expiresAt||job.expiresAt<=new Date())throw Object.assign(new Error('Agency export has expired.'),{statusCode:410,code:'EXPORT_EXPIRED'});return{url:await this.storage.signedUrl(job.storagePath,120,`${job.exportType.toLowerCase()}-${job.id}.csv`),expiresAt:new Date(Date.now()+120000).toISOString()};}
}

