import { randomBytes, createHash } from 'node:crypto';
import { and, asc, desc, eq, gt, gte, inArray, isNull, lt, lte, or, sql } from 'drizzle-orm';
import {
  agencyExportJobs, agencySessions, agencySupportSessions, agencyUsers, applicationSessions, appointments, emailOutbox, getDatabase,
  locations, managedDeliverableActivity, managedDeliverableApprovals, managedDeliverables, managedServiceTimeEntries, platformAuditEvents, platformFailedJobs, platformIncidents,
  platformPlanEntitlements, platformPlans, platformPlanVersions, platformSupportNotes, services, smsOutbox, stripeConnections, stripeWebhookEvents,
  tenantBillingAccounts, tenantEntitlementOverrides, tenantEntitlementUsage, tenantLaunchChecks, tenantOnboarding,
  tenantOnboardingStages, tenantPlanAssignments, tenantPriceExceptions, tenantSetupPayments, tenantSubscriptionEvents,
  tenantActivationMilestones, tenantChurnRecords, tenantSubscriptions, tenants, users,
} from '@ks-os/database';
import {
  agencyRoleNeedsMfa, capabilitiesForAgencyRole, evaluateDowngrade, type AgencyCapability, type AgencyRole,
  type CreateAgencyTenantSchema, type CreateBillingRequestSchema, type CreateDeliverableSchema,
  type CreateEntitlementOverrideSchema, type StartSupportSessionSchema,
} from '@ks-os/contracts';
import type { z } from 'zod';
import { GoCardlessClient } from './gocardless.service.js';
import { AccountInvitationService } from '../authentication/account-invitation.service.js';
import { getSupabaseAdmin } from '../../lib/supabase-admin.js';

export interface AgencyActor { agencyUserId: string; role: AgencyRole; requestId?: string; ipHash?: string; sessionId?:string; userAgent?:string }
const fail = (statusCode:number, code:string, message:string) => Object.assign(new Error(message), { statusCode, code });
const STAGES = ['SALE_HANDOVER','CONTRACT','SETUP_FEE','DIRECT_DEBIT','BUSINESS_PROFILE','BRAND_ASSETS','CATALOGUE','TEAM_AND_LOCATIONS','PAYMENTS','COMMUNICATIONS','TRAINING','LAUNCH'] as const;

const protectedAuditKey=/(password|passcode|token|secret|authorization|cookie|card|cvv|cvc|medical|answer|bank|accountnumber)/i;
export function redactAuditValue(value:unknown,key='metadata'):{value:unknown;redacted:boolean}{
  if(protectedAuditKey.test(key))return{value:'[REDACTED]',redacted:true};
  if(Array.isArray(value)){const items=value.map(item=>redactAuditValue(item,key));return{value:items.map(item=>item.value),redacted:items.some(item=>item.redacted)};}
  if(value&&typeof value==='object'){let redacted=false;const safe:Record<string,unknown>={};for(const[k,v]of Object.entries(value as Record<string,unknown>)){const item=redactAuditValue(v,k);safe[k]=item.value;redacted||=item.redacted;}return{value:safe,redacted};}
  return{value,redacted:false};
}

export class AgencyAuditService {
  private db = getDatabase();
  async write(actor: AgencyActor | null, action:string, targetType:string, targetId?:string|null, options:{tenantId?:string|null;reason?:string|null;outcome?:string;metadata?:Record<string,unknown>;category?:string;description?:string;previousValues?:unknown;newValues?:unknown;sourceComponent?:string;tx?:any}={}) {
    const metadata=redactAuditValue(options.metadata||{});const previous=redactAuditValue(options.previousValues,'previousValues');const next=redactAuditValue(options.newValues,'newValues');const db=options.tx||this.db;
    await db.insert(platformAuditEvents).values({ agencyUserId: actor?.agencyUserId, tenantId: options.tenantId, action, targetType, targetId, outcome: options.outcome || 'SUCCESS', reason: options.reason, requestId: actor?.requestId, ipHash: actor?.ipHash, metadata: metadata.value as Record<string,unknown>, eventCategory:options.category||'ADMINISTRATION',description:options.description,actorRole:actor?.role,sessionId:actor?.sessionId,userAgent:actor?.userAgent,previousValues:previous.value,newValues:next.value,environment:process.env.NODE_ENV||'development',sourceComponent:options.sourceComponent||'agency-api',containsRedactions:metadata.redacted||previous.redacted||next.redacted });
  }
}

export class EntitlementService {
  private db = getDatabase();
  async resolve(tenantId:string, now = new Date()) {
    const assignments = await this.db.select({ assignment:tenantPlanAssignments, version:platformPlanVersions, plan:platformPlans })
      .from(tenantPlanAssignments).innerJoin(platformPlanVersions,eq(tenantPlanAssignments.planVersionId,platformPlanVersions.id)).innerJoin(platformPlans,eq(platformPlanVersions.planId,platformPlans.id))
      .where(and(eq(tenantPlanAssignments.tenantId,tenantId),eq(tenantPlanAssignments.status,'ACTIVE'),lte(tenantPlanAssignments.startsAt,now),or(isNull(tenantPlanAssignments.endsAt),gt(tenantPlanAssignments.endsAt,now)))).orderBy(desc(tenantPlanAssignments.startsAt)).limit(1);
    if (!assignments.length) return { plan:null, entitlements:{} as Record<string,any> };
    const entitlements = await this.db.select().from(platformPlanEntitlements).where(eq(platformPlanEntitlements.planVersionId,assignments[0].version.id));
    const overrides = await this.db.select().from(tenantEntitlementOverrides).where(and(eq(tenantEntitlementOverrides.tenantId,tenantId),lte(tenantEntitlementOverrides.startsAt,now),gt(tenantEntitlementOverrides.expiresAt,now),isNull(tenantEntitlementOverrides.revokedAt)));
    const values:Record<string,any>={};
    for(const entitlement of entitlements) if(entitlement.availability==='GENERALLY_AVAILABLE') values[entitlement.entitlementKey]=entitlement.valueJson;
    for(const override of overrides) values[override.entitlementKey]=override.valueJson;
    return { plan:{ key:assignments[0].plan.key, version:assignments[0].version.version, name:assignments[0].version.name, monthlyPriceMinor:assignments[0].version.monthlyPriceMinor, setupFeeAmountMinor:assignments[0].version.setupFeeAmountMinor, currency:assignments[0].version.currency }, entitlements:values };
  }
  async assertBoolean(tenantId:string,key:string){const resolved=await this.resolve(tenantId);if(resolved.entitlements[key]?.enabled!==true)throw fail(403,'ENTITLEMENT_REQUIRED',`The ${key} entitlement is not available.`);return resolved;}
  async assertQuantity(tenantId:string,key:string,current:number){const resolved=await this.resolve(tenantId);if(!resolved.plan||!resolved.entitlements[key])throw fail(403,'ENTITLEMENT_REQUIRED',`The ${key} entitlement is not available.`);const limit=resolved.entitlements[key]?.limit;if(typeof limit==='number'&&current>=limit)throw fail(409,'ENTITLEMENT_LIMIT_REACHED',`${key} is limited to ${limit}.`);return resolved;}
  async assertUsageAvailable(tenantId:string,key:string,now=new Date()){
    const resolved=await this.resolve(tenantId,now);if(!resolved.plan||!resolved.entitlements[key])throw fail(403,'ENTITLEMENT_REQUIRED',`The ${key} entitlement is not available.`);const limit=resolved.entitlements[key]?.limit;
    if(typeof limit!=='number')return resolved;
    const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1));
    let used=0;
    if(key==='bookings.monthly'){
      const [row]=await this.db.select({used:sql<number>`count(*)::int`}).from(appointments).where(and(eq(appointments.tenantId,tenantId),gte(appointments.createdAt,start),lt(appointments.createdAt,end)));
      used=Number(row?.used||0);
    }else{
      const [row]=await this.db.select().from(tenantEntitlementUsage).where(and(eq(tenantEntitlementUsage.tenantId,tenantId),eq(tenantEntitlementUsage.entitlementKey,key),eq(tenantEntitlementUsage.periodStart,start))).limit(1);
      used=row?.used||0;
    }
    if(used>=limit)throw fail(409,'ENTITLEMENT_USAGE_EXCEEDED',`${key} monthly allowance has been used.`);
    return resolved;
  }
}

export class AgencyService {
  private db=getDatabase(); private audit=new AgencyAuditService(); private entitlements=new EntitlementService(); private gc=new GoCardlessClient(); private invitations=new AccountInvitationService();

  async listUsers(){return this.db.select({id:agencyUsers.publicReference,email:agencyUsers.emailNormalized,displayName:agencyUsers.displayName,role:agencyUsers.role,status:agencyUsers.status,lastAuthenticatedAt:agencyUsers.lastAuthenticatedAt,createdAt:agencyUsers.createdAt}).from(agencyUsers).orderBy(asc(agencyUsers.displayName));}
  async inviteUser(actor:AgencyActor,input:{email:string;displayName:string;role:AgencyRole}){
    if(actor.role!=='PLATFORM_OWNER')throw fail(403,'AGENCY_FORBIDDEN','Only a platform owner can manage agency users.');
    const record=await this.invitations.createAgencyInvitation(actor.agencyUserId,input);
    await this.audit.write(actor,'AGENCY_USER_INVITED','AGENCY_INVITATION',record.invitationReference,{metadata:{role:input.role}});return record;
  }
  async inviteTenantOwner(actor:AgencyActor,tenantReference:string,input:{email:string;displayName:string}){
    const[tenant]=await this.db.select().from(tenants).where(or(eq(tenants.agencyReference,tenantReference),eq(tenants.id,tenantReference))).limit(1);if(!tenant)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');
    const[inviter]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.id,actor.agencyUserId)).limit(1);if(!inviter?.authUserId)throw fail(403,'AGENCY_ACCESS_DENIED','Agency identity is unavailable.');
    const invitation=await this.invitations.createTenantInvitation({tenantId:tenant.id,invitedByAuthUserId:inviter.authUserId,invitedByAgencyUserId:actor.agencyUserId,email:input.email,displayName:input.displayName,role:'owner'});
    await this.audit.write(actor,'TENANT_OWNER_INVITED','TENANT_INVITATION',invitation.invitationReference,{tenantId:tenant.id});return invitation;
  }
  async listTenantUsers(actor:AgencyActor,tenantId:string){
    const[tenant]=await this.db.select({id:tenants.id}).from(tenants).where(or(eq(tenants.id,tenantId),eq(tenants.agencyReference,tenantId),eq(tenants.subdomain,tenantId))).limit(1);
    if(!tenant)return [];
    const records=await this.db.select({id:users.publicReference,email:users.emailNormalized,displayName:users.name,role:users.role,status:users.accountStatus,lastLoginAt:users.lastLoginAt,createdAt:users.createdAt}).from(users).where(eq(users.tenantId,tenant.id)).orderBy(asc(users.name));
    await this.audit.write(actor,'TENANT_USERS_VIEWED','TENANT',tenant.id,{tenantId:tenant.id});return records;
  }
  async setTenantUserStatus(actor:AgencyActor,tenantId:string,userReference:string,status:'ACTIVE'|'SUSPENDED'){
    const[target]=await this.db.select().from(users).where(and(eq(users.tenantId,tenantId),eq(users.publicReference,userReference))).limit(1);if(!target)throw fail(404,'TENANT_USER_NOT_FOUND','Business user not found.');
    if(status==='SUSPENDED'&&target.role==='owner'){
      const[owners]=await this.db.select({value:sql<number>`count(*)::int`}).from(users).where(and(eq(users.tenantId,tenantId),eq(users.role,'owner'),eq(users.accountStatus,'ACTIVE')));
      if(Number(owners?.value||0)<=1)throw fail(409,'LAST_OWNER_PROTECTION','The final active business owner cannot be suspended.');
    }
    const now=new Date();
    const[record]=await this.db.transaction(async tx=>{
      const updated=await tx.update(users).set({accountStatus:status,suspendedAt:status==='SUSPENDED'?now:null,...(status==='SUSPENDED'?{sessionsValidAfter:now}:{}),securityVersion:sql`${users.securityVersion}+1`,updatedAt:now}).where(eq(users.id,target.id)).returning();
      if(status==='SUSPENDED')await tx.update(applicationSessions).set({selectedTenantUserId:null,securityVersion:1,lastSeenAt:now}).where(and(eq(applicationSessions.selectedTenantUserId,target.id),eq(applicationSessions.applicationContext,'TENANT'),isNull(applicationSessions.revokedAt)));
      return updated;
    });
    await this.audit.write(actor,`TENANT_USER_${status}`,'TENANT_USER',target.id,{tenantId});return{...record,id:record.publicReference};
  }
  async revokeTenantUserSessions(actor:AgencyActor,tenantId:string,userReference:string){
    const[target]=await this.db.select().from(users).where(and(eq(users.tenantId,tenantId),eq(users.publicReference,userReference))).limit(1);if(!target)throw fail(404,'TENANT_USER_NOT_FOUND','Business user not found.');
    const now=new Date();await this.db.transaction(async tx=>{
      await tx.update(users).set({securityVersion:sql`${users.securityVersion}+1`,sessionsValidAfter:now,updatedAt:now}).where(eq(users.id,target.id));
      await tx.update(applicationSessions).set({selectedTenantUserId:null,securityVersion:1,lastSeenAt:now}).where(and(eq(applicationSessions.selectedTenantUserId,target.id),eq(applicationSessions.applicationContext,'TENANT'),isNull(applicationSessions.revokedAt)));
    });
    await this.audit.write(actor,'TENANT_USER_SESSIONS_REVOKED','TENANT_USER',target.id,{tenantId});
  }
  async resendAccountInvitation(actor:AgencyActor,invitationReference:string){const[inviter]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.id,actor.agencyUserId)).limit(1);if(!inviter?.authUserId)throw fail(403,'AGENCY_ACCESS_DENIED','Agency identity is unavailable.');return this.invitations.resend(invitationReference,{authUserId:inviter.authUserId,agencyUserId:actor.agencyUserId});}
  async cancelAccountInvitation(actor:AgencyActor,invitationReference:string){const[inviter]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.id,actor.agencyUserId)).limit(1);if(!inviter?.authUserId)throw fail(403,'AGENCY_ACCESS_DENIED','Agency identity is unavailable.');return this.invitations.cancel(invitationReference,{authUserId:inviter.authUserId,agencyUserId:actor.agencyUserId});}
  async setUserStatus(actor:AgencyActor,id:string,status:'ACTIVE'|'SUSPENDED'){
    if(actor.role!=='PLATFORM_OWNER')throw fail(403,'AGENCY_FORBIDDEN','Only a platform owner can manage agency users.');
    const[target]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.publicReference,id)).limit(1);if(!target)throw fail(404,'AGENCY_USER_NOT_FOUND','Agency user not found.');
    if(target.id===actor.agencyUserId&&status==='SUSPENDED')throw fail(409,'LAST_OWNER_PROTECTION','You cannot suspend your own platform-owner identity.');
    const now=new Date();
    const [record]=await this.db.update(agencyUsers).set({status,suspendedAt:status==='SUSPENDED'?now:null,...(status==='SUSPENDED'?{sessionsValidAfter:now}:{}),securityVersion:sql`${agencyUsers.securityVersion}+1`,updatedAt:now}).where(eq(agencyUsers.id,target.id)).returning();
    if(status==='SUSPENDED')await this.db.update(agencySessions).set({revokedAt:now,revokeReason:'AGENCY_USER_SUSPENDED'}).where(and(eq(agencySessions.agencyUserId,target.id),isNull(agencySessions.revokedAt)));
    if(target.authUserId&&status==='SUSPENDED')await this.db.update(applicationSessions).set({revokedAt:now,revokeReason:'AGENCY_USER_SUSPENDED'}).where(and(eq(applicationSessions.authUserId,target.authUserId),eq(applicationSessions.applicationContext,'AGENCY'),isNull(applicationSessions.revokedAt)));
    await this.audit.write(actor,`AGENCY_USER_${status}`,'AGENCY_USER',target.id);return{...record,id:record.publicReference};
  }
  async listSessions(actor:AgencyActor,userReference?:string){let target=actor.agencyUserId;if(userReference){const[user]=await this.db.select({id:agencyUsers.id}).from(agencyUsers).where(eq(agencyUsers.publicReference,userReference)).limit(1);if(!user)throw fail(404,'AGENCY_USER_NOT_FOUND','Agency user not found.');target=user.id;}if(target!==actor.agencyUserId&&actor.role!=='PLATFORM_OWNER'&&actor.role!=='SUPPORT_ADMINISTRATOR')throw fail(403,'AGENCY_FORBIDDEN','Cannot inspect these sessions.');return this.db.select({id:agencySessions.publicReference,assuranceLevel:agencySessions.assuranceLevel,expiresAt:agencySessions.expiresAt,lastSeenAt:agencySessions.lastSeenAt,revokedAt:agencySessions.revokedAt,createdAt:agencySessions.createdAt}).from(agencySessions).where(eq(agencySessions.agencyUserId,target)).orderBy(desc(agencySessions.createdAt)).limit(50);}
  async revokeSession(actor:AgencyActor,sessionReference:string){const [session]=await this.db.select().from(agencySessions).where(eq(agencySessions.publicReference,sessionReference)).limit(1);if(!session)throw fail(404,'SESSION_NOT_FOUND','Agency session not found.');if(actor.role!=='PLATFORM_OWNER'&&session.agencyUserId!==actor.agencyUserId){if(actor.role!=='SUPPORT_ADMINISTRATOR')throw fail(403,'AGENCY_FORBIDDEN','Cannot revoke this session.');const[target]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.id,session.agencyUserId)).limit(1);if(target?.role==='PLATFORM_OWNER')throw fail(403,'AGENCY_FORBIDDEN','Support administrators cannot revoke platform-owner sessions.');}await this.db.update(agencySessions).set({revokedAt:new Date(),revokeReason:'MANUAL_REVOCATION'}).where(eq(agencySessions.id,session.id));await this.db.update(applicationSessions).set({revokedAt:new Date(),revokeReason:'MANUAL_REVOCATION'}).where(and(eq(applicationSessions.authSessionId,session.authSessionId),eq(applicationSessions.applicationContext,'AGENCY'),isNull(applicationSessions.revokedAt)));await this.audit.write(actor,'AGENCY_SESSION_REVOKED','AGENCY_SESSION',session.id);}
  async revokeAllSessions(actor:AgencyActor,userReference:string){const[target]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.publicReference,userReference)).limit(1);if(!target)throw fail(404,'AGENCY_USER_NOT_FOUND','Agency user not found.');if(actor.role!=='PLATFORM_OWNER'&&actor.agencyUserId!==target.id)throw fail(403,'AGENCY_FORBIDDEN','Cannot revoke all sessions for this identity.');const now=new Date();await this.db.transaction(async tx=>{await tx.update(agencySessions).set({revokedAt:now,revokeReason:'ALL_SESSIONS_REVOKED'}).where(and(eq(agencySessions.agencyUserId,target.id),isNull(agencySessions.revokedAt)));if(target.authUserId)await tx.update(applicationSessions).set({revokedAt:now,revokeReason:'ALL_SESSIONS_REVOKED'}).where(and(eq(applicationSessions.authUserId,target.authUserId),eq(applicationSessions.applicationContext,'AGENCY'),isNull(applicationSessions.revokedAt)));await tx.update(agencyUsers).set({securityVersion:sql`${agencyUsers.securityVersion}+1`,sessionsValidAfter:now,updatedAt:now}).where(eq(agencyUsers.id,target.id));});await this.audit.write(actor,'AGENCY_ALL_SESSIONS_REVOKED','AGENCY_USER',target.id);}
  async resetMfa(actor:AgencyActor,userReference:string,factorId:string,reason:string){if(actor.role!=='PLATFORM_OWNER')throw fail(403,'AGENCY_FORBIDDEN','Only a platform owner can perform verified MFA recovery.');const[target]=await this.db.select().from(agencyUsers).where(eq(agencyUsers.publicReference,userReference)).limit(1);if(!target?.authUserId)throw fail(404,'AGENCY_USER_NOT_FOUND','Agency user not found.');if(target.id===actor.agencyUserId)throw fail(409,'MFA_RECOVERY_SELF_SERVICE_BLOCKED','MFA recovery requires a different verified platform owner.');const{error}=await getSupabaseAdmin().auth.admin.mfa.deleteFactor({id:factorId,userId:target.authUserId});if(error)throw fail(502,'AGENCY_MFA_RECOVERY_FAILED','The authenticator could not be reset.');const now=new Date();await this.db.transaction(async tx=>{await tx.update(agencySessions).set({revokedAt:now,revokeReason:'MFA_RECOVERY'}).where(and(eq(agencySessions.agencyUserId,target.id),isNull(agencySessions.revokedAt)));await tx.update(applicationSessions).set({revokedAt:now,revokeReason:'MFA_RECOVERY'}).where(and(eq(applicationSessions.authUserId,target.authUserId!),eq(applicationSessions.applicationContext,'AGENCY'),isNull(applicationSessions.revokedAt)));await tx.update(agencyUsers).set({securityVersion:sql`${agencyUsers.securityVersion}+1`,sessionsValidAfter:now,updatedAt:now}).where(eq(agencyUsers.id,target.id));});await this.audit.write(actor,'AGENCY_MFA_RESET','AGENCY_USER',target.id,{reason});}

  async listTenants(){
    return this.db.select({id:tenants.id,agencyReference:tenants.agencyReference,name:tenants.name,legalBusinessName:tenants.legalBusinessName,subdomain:tenants.subdomain,lifecycleStatus:tenants.lifecycleStatus,primaryContactName:tenants.primaryContactName,primaryContactEmail:tenants.primaryContactEmail,planKey:platformPlans.key,planName:platformPlanVersions.name,createdAt:tenants.createdAt})
      .from(tenants).leftJoin(tenantPlanAssignments,and(eq(tenantPlanAssignments.tenantId,tenants.id),eq(tenantPlanAssignments.status,'ACTIVE'))).leftJoin(platformPlanVersions,eq(tenantPlanAssignments.planVersionId,platformPlanVersions.id)).leftJoin(platformPlans,eq(platformPlanVersions.planId,platformPlans.id)).orderBy(desc(tenants.createdAt));
  }
  async getTenant(id:string){const [tenant]=await this.db.select().from(tenants).where(eq(tenants.id,id)).limit(1);if(!tenant)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');const [plan,onboarding,billing,deliverables,subscription]=await Promise.all([this.entitlements.resolve(id),this.db.select().from(tenantOnboardingStages).where(eq(tenantOnboardingStages.tenantId,id)).orderBy(asc(tenantOnboardingStages.sequence)),this.db.select().from(tenantBillingAccounts).where(eq(tenantBillingAccounts.tenantId,id)).limit(1),this.db.select().from(managedDeliverables).where(eq(managedDeliverables.tenantId,id)).orderBy(desc(managedDeliverables.createdAt)),this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,id)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1)]);return{tenant,plan,onboarding,billing:billing[0]||null,subscription:subscription[0]||null,deliverables};}
  async createTenant(actor:AgencyActor,input:z.infer<typeof CreateAgencyTenantSchema>){
    const result=await this.db.transaction(async tx=>{const [version]=await tx.select().from(platformPlanVersions).where(and(eq(platformPlanVersions.id,input.planVersionId),eq(platformPlanVersions.status,'ACTIVE'))).limit(1);if(!version)throw fail(400,'PLAN_VERSION_INVALID','An active plan version is required.');
      const [tenant]=await tx.insert(tenants).values({name:input.name,legalBusinessName:input.legalBusinessName,subdomain:input.subdomain,businessType:input.businessType,timezone:input.timezone,currency:input.currency,primaryContactName:input.primaryContactName,primaryContactEmail:input.primaryContactEmail,contractStartAt:input.contractStartAt||new Date(),minimumTermEndsAt:input.minimumTermEndsAt,foundingClient:input.foundingClient,commercialNotes:input.commercialNotes,lifecycleStatus:'ONBOARDING',isActive:false}).returning();
      await tx.insert(tenantPlanAssignments).values({tenantId:tenant.id,planVersionId:version.id,status:'ACTIVE',startsAt:input.contractStartAt||new Date(),assignedByAgencyUserId:actor.agencyUserId,reason:'INITIAL_CONTRACT'});
      const [onboarding]=await tx.insert(tenantOnboarding).values({tenantId:tenant.id,ownerAgencyUserId:actor.agencyUserId}).returning();
      await tx.insert(tenantOnboardingStages).values(STAGES.map((stageKey,sequence)=>({onboardingId:onboarding.id,tenantId:tenant.id,stageKey,sequence:sequence+1,status:sequence===0?'IN_PROGRESS':'NOT_STARTED',updatedByAgencyUserId:actor.agencyUserId})));
      await tx.insert(tenantBillingAccounts).values({tenantId:tenant.id});await tx.insert(tenantActivationMilestones).values({tenantId:tenant.id,milestoneKey:'TENANT_CREATED',sourceType:'TENANT',sourceId:tenant.id});return tenant;});
    await this.audit.write(actor,'TENANT_CREATED','TENANT',result.id,{tenantId:result.id,metadata:{planVersionId:input.planVersionId}});return result;
  }
  async updateTenant(actor:AgencyActor,id:string,input:Record<string,unknown>){const [record]=await this.db.update(tenants).set({...input,updatedAt:new Date()}).where(eq(tenants.id,id)).returning();if(!record)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');await this.audit.write(actor,'TENANT_UPDATED','TENANT',id,{tenantId:id,metadata:{fields:Object.keys(input)}});return record;}
  async changeLifecycle(actor:AgencyActor,id:string,action:'SUSPEND'|'REACTIVATE'|'OFFBOARD',reason:string){
    const[before]=await this.db.select().from(tenants).where(eq(tenants.id,id)).limit(1);if(!before)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');if(action==='OFFBOARD'&&['OFFBOARDING','OFFBOARDED'].includes(before.lifecycleStatus))throw fail(409,'TENANT_ALREADY_OFFBOARDING','Tenant is already offboarding.');
    const update=action==='SUSPEND'?{lifecycleStatus:'SUSPENDED',isActive:false,suspendedAt:new Date()}:action==='REACTIVATE'?{lifecycleStatus:'ACTIVE',isActive:true,suspendedAt:null}:{lifecycleStatus:'OFFBOARDING',isActive:false};
    const [record]=await this.db.update(tenants).set({...update,updatedAt:new Date()}).where(eq(tenants.id,id)).returning();if(!record)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');
    if(action==='OFFBOARD'){const[sub]=await this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,id)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);const[assignment]=await this.db.select().from(tenantPlanAssignments).where(and(eq(tenantPlanAssignments.tenantId,id),eq(tenantPlanAssignments.status,'ACTIVE'))).limit(1);const cancellationAt=sub?.minimumTermEndsAt&&sub.minimumTermEndsAt>new Date()?sub.minimumTermEndsAt:new Date();if(sub?.providerSubscriptionId)await this.db.update(tenantSubscriptions).set({status:'CANCELLATION_SCHEDULED',cancellationScheduledAt:cancellationAt,updatedAt:new Date()}).where(eq(tenantSubscriptions.id,sub.id));else await this.db.update(tenants).set({lifecycleStatus:'OFFBOARDED',offboardedAt:new Date(),updatedAt:new Date()}).where(eq(tenants.id,id));await this.db.insert(tenantChurnRecords).values({tenantId:id,planVersionId:assignment?.planVersionId,cancellationAt,lifetimeDays:Math.max(0,Math.floor((Date.now()-before.createdAt.getTime())/86400000)),monthlyValueMinor:sub?.amountMinor||0,reason,failedPayment:['PAYMENT_OVERDUE','GRACE_PERIOD','RESTRICTED','WRITTEN_OFF'].includes(sub?.status||''),createdByAgencyUserId:actor.agencyUserId});}
    await this.audit.write(actor,`TENANT_${action}`,'TENANT',id,{tenantId:id,reason});return record;
  }

  async listPlans(){return this.db.select({plan:platformPlans,version:platformPlanVersions}).from(platformPlans).leftJoin(platformPlanVersions,eq(platformPlanVersions.planId,platformPlans.id)).orderBy(asc(platformPlans.key),desc(platformPlanVersions.version));}
  async createPlanVersion(actor:AgencyActor,input:any){
    if(actor.role!=='PLATFORM_OWNER')throw fail(403,'AGENCY_FORBIDDEN','Only the platform owner can publish commercial plan versions.');
    const record=await this.db.transaction(async tx=>{const[plan]=await tx.select().from(platformPlans).where(eq(platformPlans.key,input.planKey)).limit(1);if(!plan)throw fail(404,'PLAN_NOT_FOUND','Plan not found.');const[version]=await tx.insert(platformPlanVersions).values({planId:plan.id,version:input.version,name:input.name,status:input.status,monthlyPriceMinor:input.monthlyPriceMinor,setupFeeAmountMinor:input.setupFeeAmountMinor,currency:input.currency,effectiveFrom:input.effectiveFrom,publishedAt:input.status==='ACTIVE'?new Date():undefined,createdByAgencyUserId:actor.agencyUserId}).returning();await tx.insert(platformPlanEntitlements).values(input.entitlements.map((item:any)=>({planVersionId:version.id,entitlementKey:item.key,name:item.name,entitlementType:item.type,availability:item.availability,valueJson:item.value})));return version;});
    await this.audit.write(actor,'PLAN_VERSION_CREATED','PLAN_VERSION',record.id,{metadata:{planKey:input.planKey,version:input.version,status:input.status}});return record;
  }
  async entitlementsForTenant(tenantId:string){return this.entitlements.resolve(tenantId);}
  async addOverride(actor:AgencyActor,tenantId:string,input:z.infer<typeof CreateEntitlementOverrideSchema>){const current=await this.entitlements.resolve(tenantId,input.startsAt);const [record]=await this.db.insert(tenantEntitlementOverrides).values({tenantId,entitlementKey:input.entitlementKey,previousValueJson:current.entitlements[input.entitlementKey]??null,valueJson:input.value,reason:input.reason,startsAt:input.startsAt,expiresAt:input.expiresAt,createdByAgencyUserId:actor.agencyUserId,approvedByAgencyUserId:actor.agencyUserId}).returning();await this.audit.write(actor,'ENTITLEMENT_OVERRIDE_CREATED','ENTITLEMENT_OVERRIDE',record.id,{tenantId,reason:input.reason});return record;}
  async changePlan(actor:AgencyActor,tenantId:string,planVersionId:string,effective:'IMMEDIATE'|'NEXT_BILLING_BOUNDARY',reason:string){
    const [target]=await this.db.select().from(platformPlanVersions).where(and(eq(platformPlanVersions.id,planVersionId),eq(platformPlanVersions.status,'ACTIVE'))).limit(1);if(!target)throw fail(404,'PLAN_VERSION_NOT_FOUND','Active plan version not found.');
    const [counts]=await this.db.select({staff:sql<number>`count(distinct ${users.id})::int`,locations:sql<number>`count(distinct ${locations.id})::int`}).from(tenants).leftJoin(users,and(eq(users.tenantId,tenants.id),eq(users.accountStatus,'ACTIVE'))).leftJoin(locations,and(eq(locations.tenantId,tenants.id),eq(locations.isActive,true))).where(eq(tenants.id,tenantId));
    const targetEnts=await this.db.select().from(platformPlanEntitlements).where(eq(platformPlanEntitlements.planVersionId,planVersionId));const staffLimit=(targetEnts.find(x=>x.entitlementKey==='staff.limit')?.valueJson as any)?.limit??null;const locationLimit=(targetEnts.find(x=>x.entitlementKey==='locations.limit')?.valueJson as any)?.limit??null;
    const safety=evaluateDowngrade({currentStaff:Number(counts?.staff||0),currentLocations:Number(counts?.locations||0),targetStaffLimit:staffLimit,targetLocationLimit:locationLimit});if(!safety.safe)throw Object.assign(fail(409,'DOWNGRADE_BLOCKED','Resolve plan-limit blockers before downgrading.'),{details:safety});
    const [current]=await this.db.select().from(tenantPlanAssignments).where(and(eq(tenantPlanAssignments.tenantId,tenantId),eq(tenantPlanAssignments.status,'ACTIVE'))).orderBy(desc(tenantPlanAssignments.startsAt)).limit(1);if(!current)throw fail(409,'PLAN_ASSIGNMENT_MISSING','Tenant has no active plan assignment.');
    if(effective==='NEXT_BILLING_BOUNDARY'){const [sub]=await this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,tenantId)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);if(!sub?.nextChargeAt)throw fail(409,'BILLING_BOUNDARY_UNKNOWN','A billing boundary is required.');await this.db.update(tenantPlanAssignments).set({scheduledReplacementPlanVersionId:planVersionId,scheduledReplacementAt:sub.nextChargeAt,reason}).where(eq(tenantPlanAssignments.id,current.id));}
    else {
      const [sub]=await this.db.select().from(tenantSubscriptions).where(and(eq(tenantSubscriptions.tenantId,tenantId),inArray(tenantSubscriptions.status,['ACTIVE','TRIALLING','GRACE_PERIOD']))).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);
      if(sub?.providerSubscriptionId)await this.gc.request<any>(`/subscriptions/${encodeURIComponent(sub.providerSubscriptionId)}`,'PUT',{subscriptions:{amount:target.monthlyPriceMinor,name:`KS OS ${target.name}`}},createHash('sha256').update(`immediate-plan-change:${current.id}:${target.id}`).digest('hex'));
      await this.db.transaction(async tx=>{await tx.update(tenantPlanAssignments).set({status:'ENDED',endsAt:new Date(),reason}).where(eq(tenantPlanAssignments.id,current.id));await tx.insert(tenantPlanAssignments).values({tenantId,planVersionId,status:'ACTIVE',startsAt:new Date(),assignedByAgencyUserId:actor.agencyUserId,reason});if(sub)await tx.update(tenantSubscriptions).set({planVersionId,amountMinor:target.monthlyPriceMinor,updatedAt:new Date()}).where(eq(tenantSubscriptions.id,sub.id));});
    }
    await this.audit.write(actor,effective==='IMMEDIATE'?'TENANT_PLAN_CHANGED':'TENANT_PLAN_CHANGE_SCHEDULED','TENANT_PLAN',current.id,{tenantId,reason,metadata:{planVersionId,effective}});return{effective,safety};
  }

  async updateStage(actor:AgencyActor,tenantId:string,stageKey:string,input:any){const [record]=await this.db.update(tenantOnboardingStages).set({...input,completedAt:input.status==='COMPLETE'?new Date():null,updatedByAgencyUserId:actor.agencyUserId,updatedAt:new Date()}).where(and(eq(tenantOnboardingStages.tenantId,tenantId),eq(tenantOnboardingStages.stageKey,stageKey))).returning();if(!record)throw fail(404,'ONBOARDING_STAGE_NOT_FOUND','Onboarding stage not found.');const stages=await this.db.select().from(tenantOnboardingStages).where(eq(tenantOnboardingStages.tenantId,tenantId)).orderBy(asc(tenantOnboardingStages.sequence));const complete=stages.filter(stage=>['COMPLETE','SKIPPED'].includes(stage.status)).length;const blockers=stages.filter(stage=>stage.status==='BLOCKED').map(stage=>({stageKey:stage.stageKey,note:stage.blockerNote}));const current=stages.find(stage=>!['COMPLETE','SKIPPED'].includes(stage.status))?.stageKey||'LAUNCH';await this.db.update(tenantOnboarding).set({completionPercentage:Math.round(complete/stages.length*100),currentStage:current,blockers,status:blockers.length?'BLOCKED':complete===stages.length?'READY_TO_LAUNCH':'IN_PROGRESS',updatedAt:new Date()}).where(eq(tenantOnboarding.tenantId,tenantId));await this.audit.write(actor,'ONBOARDING_STAGE_UPDATED','ONBOARDING_STAGE',record.id,{tenantId,metadata:{stageKey,status:input.status}});return record;}
  async onboarding(tenantId:string){const[record]=await this.db.select().from(tenantOnboarding).where(eq(tenantOnboarding.tenantId,tenantId)).limit(1);if(!record)throw fail(404,'ONBOARDING_NOT_FOUND','Tenant onboarding not found.');return{...record,stages:await this.db.select().from(tenantOnboardingStages).where(eq(tenantOnboardingStages.tenantId,tenantId)).orderBy(asc(tenantOnboardingStages.sequence)),checks:await this.db.select().from(tenantLaunchChecks).where(eq(tenantLaunchChecks.tenantId,tenantId)).orderBy(asc(tenantLaunchChecks.checkKey))};}
  async updateOnboarding(actor:AgencyActor,tenantId:string,input:any){const[record]=await this.db.update(tenantOnboarding).set({...input,updatedAt:new Date()}).where(eq(tenantOnboarding.tenantId,tenantId)).returning();if(!record)throw fail(404,'ONBOARDING_NOT_FOUND','Tenant onboarding not found.');await this.audit.write(actor,'TENANT_ONBOARDING_UPDATED','TENANT_ONBOARDING',record.id,{tenantId,metadata:{fields:Object.keys(input)}});return record;}
  async runLaunchChecks(actor:AgencyActor,tenantId:string){
    const [ownerCount,locationCount,serviceCount,billing,setup,subscription,stripe,stages]=await Promise.all([
      this.db.select({count:sql<number>`count(*)::int`}).from(users).where(and(eq(users.tenantId,tenantId),eq(users.role,'owner'),eq(users.accountStatus,'ACTIVE'))),
      this.db.select({count:sql<number>`count(*)::int`}).from(locations).where(and(eq(locations.tenantId,tenantId),eq(locations.isActive,true))),
      this.db.select({count:sql<number>`count(*)::int`}).from(services).where(and(eq(services.tenantId,tenantId),eq(services.isActive,true))),
      this.db.select().from(tenantBillingAccounts).where(eq(tenantBillingAccounts.tenantId,tenantId)).limit(1),
      this.db.select().from(tenantSetupPayments).where(eq(tenantSetupPayments.tenantId,tenantId)).orderBy(desc(tenantSetupPayments.createdAt)).limit(1),
      this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,tenantId)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1),
      this.db.select().from(stripeConnections).where(eq(stripeConnections.tenantId,tenantId)).limit(1),
      this.db.select().from(tenantOnboardingStages).where(eq(tenantOnboardingStages.tenantId,tenantId)),
    ]);
    const checks=[
      {key:'OWNER_ACTIVE',ok:Number(ownerCount[0]?.count||0)>0,detail:'An active owner account is required.'},
      {key:'LOCATION_ACTIVE',ok:Number(locationCount[0]?.count||0)>0,detail:'At least one active location is required.'},
      {key:'SERVICE_ACTIVE',ok:Number(serviceCount[0]?.count||0)>0,detail:'At least one active service is required.'},
      {key:'DIRECT_DEBIT_MANDATE',ok:billing[0]?.mandateStatus==='ACTIVE',detail:'An active GoCardless mandate is required.'},
      {key:'SETUP_FEE',ok:['CONFIRMED','WAIVED'].includes(setup[0]?.status||''),detail:'The setup fee must be confirmed or formally waived.'},
      {key:'SUBSCRIPTION',ok:['ACTIVE','TRIALLING'].includes(subscription[0]?.status||''),detail:'An active or trialling subscription is required.'},
      {key:'STRIPE_CONNECT',ok:stripe[0]?.connectionStatus==='READY',detail:'Stripe Connect must be ready for appointment payments.'},
      {key:'ONBOARDING_STAGES',ok:stages.filter(s=>s.stageKey!=='LAUNCH').every(s=>['COMPLETE','SKIPPED'].includes(s.status)),detail:'All pre-launch stages must be complete.'},
    ];
    await this.db.transaction(async tx=>{for(const check of checks)await tx.insert(tenantLaunchChecks).values({tenantId,checkKey:check.key,status:check.ok?'PASS':'FAIL',blocking:true,detail:check.detail}).onConflictDoUpdate({target:[tenantLaunchChecks.tenantId,tenantLaunchChecks.checkKey],set:{status:check.ok?'PASS':'FAIL',detail:check.detail,checkedAt:new Date()}});});
    await this.audit.write(actor,'TENANT_LAUNCH_CHECKS_RUN','TENANT',tenantId,{tenantId,metadata:{passed:checks.filter(c=>c.ok).length,total:checks.length}});return{ready:checks.every(c=>c.ok),checks};
  }
  async launch(actor:AgencyActor,tenantId:string){const result=await this.runLaunchChecks(actor,tenantId);if(!result.ready)throw Object.assign(fail(409,'LAUNCH_BLOCKED','Tenant is not ready to launch.'),{details:result.checks});await this.db.transaction(async tx=>{await tx.update(tenants).set({lifecycleStatus:'ACTIVE',isActive:true,launchedAt:new Date(),updatedAt:new Date()}).where(eq(tenants.id,tenantId));await tx.update(tenantOnboarding).set({status:'COMPLETE',completionPercentage:100,currentStage:'LAUNCH',launchedAt:new Date(),updatedAt:new Date()}).where(eq(tenantOnboarding.tenantId,tenantId));await tx.update(tenantOnboardingStages).set({status:'COMPLETE',completedAt:new Date(),updatedAt:new Date()}).where(and(eq(tenantOnboardingStages.tenantId,tenantId),eq(tenantOnboardingStages.stageKey,'LAUNCH')));await tx.insert(tenantActivationMilestones).values({tenantId,milestoneKey:'TENANT_LAUNCHED',sourceType:'ONBOARDING'}).onConflictDoNothing({target:[tenantActivationMilestones.tenantId,tenantActivationMilestones.milestoneKey]});});await this.audit.write(actor,'TENANT_LAUNCHED','TENANT',tenantId,{tenantId});return{launched:true};}

  async startBillingRequest(actor:AgencyActor,tenantId:string,input:z.infer<typeof CreateBillingRequestSchema>){
    const [account]=await this.db.select().from(tenantBillingAccounts).where(eq(tenantBillingAccounts.tenantId,tenantId)).limit(1);if(!account)throw fail(409,'BILLING_ACCOUNT_MISSING','Tenant billing account is missing.');
    const [commercial]=await this.db.select({setupFeeAmountMinor:platformPlanVersions.setupFeeAmountMinor,currency:platformPlanVersions.currency}).from(tenantPlanAssignments).innerJoin(platformPlanVersions,eq(tenantPlanAssignments.planVersionId,platformPlanVersions.id)).where(and(eq(tenantPlanAssignments.tenantId,tenantId),eq(tenantPlanAssignments.status,'ACTIVE'))).orderBy(desc(tenantPlanAssignments.startsAt)).limit(1);if(!commercial)throw fail(409,'PLAN_ASSIGNMENT_MISSING','Tenant has no active commercial plan.');
    const idempotencyKey=createHash('sha256').update(`setup:${tenantId}:${commercial.setupFeeAmountMinor}:${commercial.currency}`).digest('hex');
    const request=await this.gc.request<any>('/billing_requests','POST',{billing_requests:{mandate_request:{currency:commercial.currency,scheme:'bacs'},...(commercial.setupFeeAmountMinor>0?{payment_request:{amount:commercial.setupFeeAmountMinor,currency:commercial.currency,description:input.description}}:{}),metadata:{tenant_reference:tenantId}}},idempotencyKey);
    const billingRequest=request.billing_requests;const flow=await this.gc.request<any>('/billing_request_flows','POST',{billing_request_flows:{redirect_uri:input.successRedirectUrl,exit_uri:input.exitRedirectUrl,links:{billing_request:billingRequest.id}}},`${idempotencyKey}:flow`);
    const [payment]=await this.db.insert(tenantSetupPayments).values({tenantId,billingAccountId:account.id,providerBillingRequestId:billingRequest.id,providerPaymentId:billingRequest.links?.payment_request,amountMinor:commercial.setupFeeAmountMinor,currency:commercial.currency,status:commercial.setupFeeAmountMinor===0?'WAIVED':'PENDING',waivedReason:commercial.setupFeeAmountMinor===0?'NO_SETUP_FEE_CONTRACT':undefined}).onConflictDoUpdate({target:tenantSetupPayments.providerBillingRequestId,set:{updatedAt:new Date()}}).returning();
    await this.audit.write(actor,'GOCARDLESS_BILLING_REQUEST_CREATED','SETUP_PAYMENT',payment.id,{tenantId,metadata:{amountMinor:commercial.setupFeeAmountMinor,currency:commercial.currency}});return{setupPayment:payment,authorisationUrl:flow.billing_request_flows.authorisation_url};
  }
  async activateSubscription(actor:AgencyActor,tenantId:string,planVersionId:string){const [account]=await this.db.select().from(tenantBillingAccounts).where(eq(tenantBillingAccounts.tenantId,tenantId)).limit(1);if(!account?.providerMandateId||account.mandateStatus!=='ACTIVE')throw fail(409,'MANDATE_REQUIRED','An active GoCardless mandate is required.');const [version]=await this.db.select().from(platformPlanVersions).where(and(eq(platformPlanVersions.id,planVersionId),eq(platformPlanVersions.status,'ACTIVE'))).limit(1);if(!version)throw fail(404,'PLAN_VERSION_NOT_FOUND','Active plan version not found.');const [tenant]=await this.db.select({minimumTermEndsAt:tenants.minimumTermEndsAt}).from(tenants).where(eq(tenants.id,tenantId)).limit(1);const key=createHash('sha256').update(`subscription:${tenantId}:${planVersionId}`).digest('hex');const result=await this.gc.request<any>('/subscriptions','POST',{subscriptions:{amount:version.monthlyPriceMinor,currency:version.currency,name:`KS OS ${version.name}`,interval_unit:'monthly',links:{mandate:account.providerMandateId},metadata:{tenant_reference:tenantId,plan_version_id:planVersionId}}},key);const provider=result.subscriptions;const [record]=await this.db.insert(tenantSubscriptions).values({tenantId,billingAccountId:account.id,planVersionId,providerSubscriptionId:provider.id,status:'PENDING',amountMinor:version.monthlyPriceMinor,currency:version.currency,nextChargeAt:provider.upcoming_payments?.[0]?.charge_date?new Date(provider.upcoming_payments[0].charge_date):undefined,minimumTermEndsAt:tenant?.minimumTermEndsAt}).returning();await this.audit.write(actor,'GOCARDLESS_SUBSCRIPTION_CREATED','SUBSCRIPTION',record.id,{tenantId,metadata:{amountMinor:record.amountMinor}});return record;}
  async waiveSetupFee(actor:AgencyActor,tenantId:string,reason:string){const [record]=await this.db.update(tenantSetupPayments).set({status:'WAIVED',waivedReason:reason,updatedAt:new Date()}).where(and(eq(tenantSetupPayments.tenantId,tenantId),eq(tenantSetupPayments.status,'PENDING'))).returning();if(!record)throw fail(404,'SETUP_PAYMENT_NOT_FOUND','Pending setup payment not found.');await this.audit.write(actor,'SETUP_FEE_WAIVED','SETUP_PAYMENT',record.id,{tenantId,reason});return record;}
  async addPriceException(actor:AgencyActor,tenantId:string,input:any){const [sub]=await this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,tenantId)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);const [record]=await this.db.insert(tenantPriceExceptions).values({...input,tenantId,subscriptionId:sub?.id,createdByAgencyUserId:actor.agencyUserId}).returning();await this.audit.write(actor,'PRICE_EXCEPTION_CREATED','PRICE_EXCEPTION',record.id,{tenantId,reason:input.reason});return record;}
  async billing(tenantId:string){const[account,setup,subscription,exceptions,events]=await Promise.all([this.db.select().from(tenantBillingAccounts).where(eq(tenantBillingAccounts.tenantId,tenantId)).limit(1),this.db.select().from(tenantSetupPayments).where(eq(tenantSetupPayments.tenantId,tenantId)).orderBy(desc(tenantSetupPayments.createdAt)).limit(20),this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,tenantId)).orderBy(desc(tenantSubscriptions.createdAt)).limit(20),this.db.select().from(tenantPriceExceptions).where(eq(tenantPriceExceptions.tenantId,tenantId)).orderBy(desc(tenantPriceExceptions.createdAt)).limit(20),this.db.select({id:tenantSubscriptionEvents.id,resourceType:tenantSubscriptionEvents.resourceType,action:tenantSubscriptionEvents.action,processedAt:tenantSubscriptionEvents.processedAt,failureCode:tenantSubscriptionEvents.failureCode,receivedAt:tenantSubscriptionEvents.receivedAt}).from(tenantSubscriptionEvents).where(eq(tenantSubscriptionEvents.tenantId,tenantId)).orderBy(desc(tenantSubscriptionEvents.receivedAt)).limit(50)]);return{account:account[0]||null,setupPayments:setup,subscriptions:subscription,priceExceptions:exceptions,events};}
  async subscriptionAction(actor:AgencyActor,tenantId:string,action:'PAUSE'|'RESUME'|'CANCEL',reason:string){const[sub]=await this.db.select().from(tenantSubscriptions).where(eq(tenantSubscriptions.tenantId,tenantId)).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);if(!sub?.providerSubscriptionId)throw fail(404,'SUBSCRIPTION_NOT_FOUND','Provider subscription not found.');const providerAction=action.toLowerCase();await this.gc.request<any>(`/subscriptions/${encodeURIComponent(sub.providerSubscriptionId)}/actions/${providerAction}`,'POST',{subscriptions:{metadata:{agency_reason:reason.slice(0,100)}}},createHash('sha256').update(`${sub.id}:${action}`).digest('hex'));const status=action==='PAUSE'?'PAUSED':action==='RESUME'?'ACTIVE':'CANCELLATION_SCHEDULED';const[updated]=await this.db.update(tenantSubscriptions).set({status,cancellationScheduledAt:action==='CANCEL'?new Date():sub.cancellationScheduledAt,updatedAt:new Date()}).where(eq(tenantSubscriptions.id,sub.id)).returning();await this.audit.write(actor,`SUBSCRIPTION_${action}`,'SUBSCRIPTION',sub.id,{tenantId,reason});return updated;}

  async createDeliverable(actor:AgencyActor,tenantId:string,input:any){const [record]=await this.db.insert(managedDeliverables).values({...input,tenantId}).returning();await this.db.insert(managedDeliverableActivity).values({deliverableId:record.id,tenantId,agencyUserId:actor.agencyUserId,action:'CREATED',toStatus:record.status});await this.audit.write(actor,'DELIVERABLE_CREATED','DELIVERABLE',record.id,{tenantId});return record;}
  async updateDeliverable(actor:AgencyActor,id:string,input:any){const [before]=await this.db.select().from(managedDeliverables).where(eq(managedDeliverables.id,id)).limit(1);if(!before)throw fail(404,'DELIVERABLE_NOT_FOUND','Deliverable not found.');const [record]=await this.db.update(managedDeliverables).set({...input,completedAt:['APPROVED','DELIVERED'].includes(input.status)?new Date():before.completedAt,updatedAt:new Date()}).where(eq(managedDeliverables.id,id)).returning();await this.db.insert(managedDeliverableActivity).values({deliverableId:id,tenantId:before.tenantId,agencyUserId:actor.agencyUserId,action:'UPDATED',fromStatus:before.status,toStatus:record.status});if(before.type==='WEBSITE'&&record.status==='DELIVERED')await this.db.insert(tenantActivationMilestones).values({tenantId:before.tenantId,milestoneKey:'WEBSITE_LIVE',sourceType:'DELIVERABLE',sourceId:id}).onConflictDoNothing({target:[tenantActivationMilestones.tenantId,tenantActivationMilestones.milestoneKey]});await this.audit.write(actor,'DELIVERABLE_UPDATED','DELIVERABLE',id,{tenantId:before.tenantId,metadata:{fields:Object.keys(input)}});return record;}
  async requestDeliverableApproval(actor:AgencyActor,id:string){const[item]=await this.db.select().from(managedDeliverables).where(eq(managedDeliverables.id,id)).limit(1);if(!item)throw fail(404,'DELIVERABLE_NOT_FOUND','Deliverable not found.');const[approval]=await this.db.insert(managedDeliverableApprovals).values({deliverableId:id,tenantId:item.tenantId,requestedByAgencyUserId:actor.agencyUserId}).returning();await this.db.update(managedDeliverables).set({status:'READY_FOR_APPROVAL',updatedAt:new Date()}).where(eq(managedDeliverables.id,id));await this.audit.write(actor,'DELIVERABLE_APPROVAL_REQUESTED','DELIVERABLE_APPROVAL',approval.id,{tenantId:item.tenantId});return approval;}
  async recordDeliverableTime(actor:AgencyActor,id:string,input:{minutes:number;costMinor:number;note?:string;workedAt:Date}){const[item]=await this.db.select().from(managedDeliverables).where(eq(managedDeliverables.id,id)).limit(1);if(!item)throw fail(404,'DELIVERABLE_NOT_FOUND','Deliverable not found.');const[entry]=await this.db.insert(managedServiceTimeEntries).values({deliverableId:id,tenantId:item.tenantId,agencyUserId:actor.agencyUserId,...input}).returning();await this.db.update(managedDeliverables).set({actualMinutes:sql`${managedDeliverables.actualMinutes} + ${input.minutes}`,costMinor:sql`${managedDeliverables.costMinor} + ${input.costMinor}`,updatedAt:new Date()}).where(eq(managedDeliverables.id,id));await this.audit.write(actor,'DELIVERABLE_TIME_RECORDED','TIME_ENTRY',entry.id,{tenantId:item.tenantId,metadata:{minutes:input.minutes,costMinor:input.costMinor}});return entry;}
  async respondDeliverableApproval(tenantId:string,approvalId:string,input:{status:'APPROVED'|'REJECTED';note?:string}){const[approval]=await this.db.update(managedDeliverableApprovals).set({status:input.status,responseNote:input.note,respondedAt:new Date()}).where(and(eq(managedDeliverableApprovals.id,approvalId),eq(managedDeliverableApprovals.tenantId,tenantId),eq(managedDeliverableApprovals.status,'PENDING'))).returning();if(!approval)throw fail(404,'DELIVERABLE_APPROVAL_NOT_FOUND','Pending approval not found.');await this.db.update(managedDeliverables).set({status:input.status==='APPROVED'?'APPROVED':'IN_PROGRESS',completedAt:input.status==='APPROVED'?new Date():null,updatedAt:new Date()}).where(and(eq(managedDeliverables.id,approval.deliverableId),eq(managedDeliverables.tenantId,tenantId)));return approval;}

  async startSupportSession(actor:AgencyActor,input:z.infer<typeof StartSupportSessionSchema>){if(!capabilitiesForAgencyRole(actor.role).includes('support.session.start'))throw fail(403,'AGENCY_FORBIDDEN','Support-session capability required.');const token=randomBytes(32).toString('base64url');const tokenHash=createHash('sha256').update(token).digest('hex');const [record]=await this.db.insert(agencySupportSessions).values({agencyUserId:actor.agencyUserId,tenantId:input.tenantId,tokenHash,scope:input.scope,reason:input.reason,expiresAt:new Date(Date.now()+input.durationMinutes*60000)}).returning();await this.audit.write(actor,'SUPPORT_SESSION_STARTED','SUPPORT_SESSION',record.id,{tenantId:input.tenantId,reason:input.reason,metadata:{durationMinutes:input.durationMinutes,scope:input.scope}});return{id:record.id,token,tenantId:record.tenantId,scope:record.scope,reason:record.reason,expiresAt:record.expiresAt};}
  async getSupportSession(actor:AgencyActor,id:string){const[record]=await this.db.select({id:agencySupportSessions.id,agencyUserId:agencySupportSessions.agencyUserId,tenantId:agencySupportSessions.tenantId,scope:agencySupportSessions.scope,reason:agencySupportSessions.reason,expiresAt:agencySupportSessions.expiresAt,lastUsedAt:agencySupportSessions.lastUsedAt,revokedAt:agencySupportSessions.revokedAt,createdAt:agencySupportSessions.createdAt}).from(agencySupportSessions).where(eq(agencySupportSessions.id,id)).limit(1);if(!record)throw fail(404,'SUPPORT_SESSION_NOT_FOUND','Support session not found.');if(actor.role!=='PLATFORM_OWNER'&&record.agencyUserId!==actor.agencyUserId)throw fail(403,'AGENCY_FORBIDDEN','Cannot inspect this support session.');return record;}
  async revokeSupportSession(actor:AgencyActor,id:string){const [record]=await this.db.update(agencySupportSessions).set({revokedAt:new Date()}).where(and(eq(agencySupportSessions.id,id),or(eq(agencySupportSessions.agencyUserId,actor.agencyUserId),sql`${actor.role} = 'PLATFORM_OWNER'`))).returning();if(!record)throw fail(404,'SUPPORT_SESSION_NOT_FOUND','Support session not found.');await this.audit.write(actor,'SUPPORT_SESSION_REVOKED','SUPPORT_SESSION',id,{tenantId:record.tenantId});}
  async supportOverview(){const [tenantStates,failedJobs,incidents,webhooks,communications]=await Promise.all([this.db.select({status:tenants.lifecycleStatus,count:sql<number>`count(*)::int`}).from(tenants).groupBy(tenants.lifecycleStatus),this.db.select().from(platformFailedJobs).where(eq(platformFailedJobs.status,'FAILED')).orderBy(desc(platformFailedJobs.lastFailedAt)).limit(100),this.db.select().from(platformIncidents).where(eq(platformIncidents.status,'OPEN')).orderBy(desc(platformIncidents.startedAt)).limit(50),this.db.select({failed:sql<number>`count(*) filter (where ${tenantSubscriptionEvents.failureCode} is not null)::int`,pending:sql<number>`count(*) filter (where ${tenantSubscriptionEvents.processedAt} is null)::int`}).from(tenantSubscriptionEvents),this.db.execute(sql`select (select count(*) from email_outbox where status in ('FAILED','DEAD_LETTER'))::int as email_failed, (select count(*) from sms_outbox where status in ('FAILED','DEAD_LETTER'))::int as sms_failed`)]);return{tenantStates,failedJobs,incidents,webhooks:webhooks[0],communications:(communications as any).rows?.[0]||{}};}
  async tenantHealth(tenantId:string){const[tenant]=await this.db.select({id:tenants.id,name:tenants.name,lifecycleStatus:tenants.lifecycleStatus,isActive:tenants.isActive}).from(tenants).where(eq(tenants.id,tenantId)).limit(1);if(!tenant)throw fail(404,'TENANT_NOT_FOUND','Tenant not found.');const[billing,failedJobs,communications,stripe]=await Promise.all([this.billing(tenantId),this.db.select().from(platformFailedJobs).where(and(eq(platformFailedJobs.tenantId,tenantId),eq(platformFailedJobs.status,'FAILED'))).limit(50),this.db.execute(sql`select (select count(*) from email_outbox where tenant_id=${tenantId}::uuid and status in ('FAILED','DEAD_LETTER'))::int email_failed,(select count(*) from sms_outbox where tenant_id=${tenantId}::uuid and status in ('FAILED','DEAD_LETTER'))::int sms_failed`),this.db.select({status:stripeConnections.connectionStatus,lastSyncedAt:stripeConnections.lastSyncedAt}).from(stripeConnections).where(eq(stripeConnections.tenantId,tenantId)).limit(1)]);return{tenant,billing:{mandateStatus:billing.account?.mandateStatus||'NOT_CREATED',subscriptionStatus:billing.subscriptions[0]?.status||'NONE'},stripe:stripe[0]||null,failedJobs,communications:(communications as any).rows?.[0]||{}};}
  async webhookEvents(){const[goCardless,stripe]=await Promise.all([this.db.select({id:tenantSubscriptionEvents.id,tenantId:tenantSubscriptionEvents.tenantId,provider:sql<string>`'GOCARDLESS'`,eventType:tenantSubscriptionEvents.resourceType,action:tenantSubscriptionEvents.action,status:sql<string>`case when ${tenantSubscriptionEvents.failureCode} is not null then 'FAILED' when ${tenantSubscriptionEvents.processedAt} is null then 'PENDING' else 'PROCESSED' end`,receivedAt:tenantSubscriptionEvents.receivedAt}).from(tenantSubscriptionEvents).orderBy(desc(tenantSubscriptionEvents.receivedAt)).limit(100),this.db.select({id:stripeWebhookEvents.stripeEventId,provider:sql<string>`'STRIPE_CONNECT'`,eventType:stripeWebhookEvents.eventType,status:stripeWebhookEvents.processingStatus,receivedAt:stripeWebhookEvents.receivedAt}).from(stripeWebhookEvents).orderBy(desc(stripeWebhookEvents.receivedAt)).limit(100)]);return[...goCardless,...stripe].sort((a:any,b:any)=>new Date(b.receivedAt).getTime()-new Date(a.receivedAt).getTime()).slice(0,150);}
  async replayWebhook(actor:AgencyActor,id:string,reason:string){const[event]=await this.db.update(tenantSubscriptionEvents).set({processedAt:null,failureCode:null}).where(and(eq(tenantSubscriptionEvents.id,id),sql`${tenantSubscriptionEvents.failureCode} is not null`)).returning();if(!event)throw fail(409,'WEBHOOK_NOT_REPLAYABLE','Only a failed, known GoCardless event can be requeued safely.');await this.audit.write(actor,'WEBHOOK_REPLAY_QUEUED','GOCARDLESS_EVENT',id,{tenantId:event.tenantId,reason});return{id,status:'PENDING'};}
  async failedJobs(){return this.db.select().from(platformFailedJobs).orderBy(desc(platformFailedJobs.lastFailedAt)).limit(200);}
  async fulfilment(){return this.db.select({deliverable:managedDeliverables,tenantName:tenants.name,tenantReference:tenants.agencyReference}).from(managedDeliverables).innerJoin(tenants,eq(managedDeliverables.tenantId,tenants.id)).orderBy(desc(managedDeliverables.updatedAt)).limit(200);}
  async retryJob(actor:AgencyActor,id:string,reason:string){const allow=['AUTOMATION_ACTION','EMAIL_DELIVERY','SMS_DELIVERY','REPORT_EXPORT','REPUTATION_SYNC','GOCARDLESS_EVENT'];const [job]=await this.db.select().from(platformFailedJobs).where(eq(platformFailedJobs.id,id)).limit(1);if(!job||!job.safeRetryKind||!allow.includes(job.safeRetryKind))throw fail(409,'JOB_NOT_SAFE_TO_RETRY','This job cannot be retried from the support console.');const [updated]=await this.db.update(platformFailedJobs).set({status:'QUEUED',attemptCount:sql`${platformFailedJobs.attemptCount} + 1`,nextAttemptAt:new Date(),updatedAt:new Date()}).where(and(eq(platformFailedJobs.id,id),eq(platformFailedJobs.status,'FAILED'))).returning();if(!updated)throw fail(409,'JOB_RETRY_CONFLICT','The job state changed; refresh before retrying.');await this.audit.write(actor,'FAILED_JOB_RETRIED','FAILED_JOB',id,{tenantId:job.tenantId,reason,metadata:{safeRetryKind:job.safeRetryKind}});return updated;}
  async addSupportNote(actor:AgencyActor,input:any){const [record]=await this.db.insert(platformSupportNotes).values({...input,agencyUserId:actor.agencyUserId}).returning();await this.audit.write(actor,'SUPPORT_NOTE_CREATED','SUPPORT_NOTE',record.id,{tenantId:record.tenantId,metadata:{category:record.category}});return record;}
  async auditLog(){return this.db.select().from(platformAuditEvents).orderBy(desc(platformAuditEvents.occurredAt)).limit(200);}

  async analytics(){
    const [revenue,tenantsByStatus,activation,usage,workload,churn]=await Promise.all([
      this.db.execute(sql`select coalesce(sum(amount_minor) filter (where status in ('ACTIVE','TRIALLING')),0)::bigint as mrr_minor, (coalesce(sum(amount_minor) filter (where status in ('ACTIVE','TRIALLING')),0)*12)::bigint as arr_minor, coalesce(sum(amount_minor) filter (where status='GRACE_PERIOD'),0)::bigint as at_risk_mrr_minor, count(*) filter (where status in ('ACTIVE','TRIALLING'))::int as active_subscriptions, coalesce(avg(amount_minor) filter (where status in ('ACTIVE','TRIALLING')),0)::bigint as average_revenue_per_tenant_minor, count(*) filter (where created_at>=now()-interval '30 days')::int as new_subscriptions_30d, (select coalesce(sum(amount_minor),0)::bigint from tenant_setup_payments where status='CONFIRMED') as setup_fee_revenue_minor, (select count(*)::int from tenant_subscription_events where action='failed') as failed_payments, (select count(*)::int from tenant_subscription_events where action in ('confirmed','paid_out') and resource_type='payments') as recovered_or_confirmed_payments from tenant_subscriptions`),
      this.db.select({status:tenants.lifecycleStatus,count:sql<number>`count(*)::int`}).from(tenants).groupBy(tenants.lifecycleStatus),
      this.db.execute(sql`select count(*) filter (where launched_at is not null)::int as launched, percentile_cont(0.5) within group (order by extract(epoch from (launched_at-created_at))/86400) filter (where launched_at is not null) as median_days_to_launch, (select count(*)::int from tenant_activation_milestones where milestone_key='FIRST_REAL_BOOKING') first_real_booking, (select count(*)::int from tenant_activation_milestones where milestone_key='WEBSITE_LIVE') website_live, (select count(*)::int from tenant_activation_milestones where milestone_key='SETUP_FEE_CONFIRMED') setup_fee_confirmed from tenants`),
      this.db.execute(sql`select count(*)::int as appointments_30d, count(distinct tenant_id)::int as active_tenants_30d from appointments where created_at >= now()-interval '30 days'`),
      this.db.execute(sql`select count(*) filter (where status not in ('APPROVED','DELIVERED','CANCELLED'))::int as open_deliverables, coalesce(sum(actual_minutes),0)::bigint as actual_minutes, coalesce(sum(cost_minor),0)::bigint as cost_minor from managed_deliverables`),
      this.db.execute(sql`select count(*)::int as churned_tenants,coalesce(sum(monthly_value_minor),0)::bigint as churned_mrr_minor,coalesce(avg(lifetime_days),0)::int as average_lifetime_days,count(*) filter(where failed_payment)::int failed_payment_churn,count(*) filter(where price_issue)::int price_churn,count(*) filter(where service_issue)::int service_churn from tenant_churn_records`),
    ]);
    const row=(r:any)=>r.rows?.[0]||{};return{revenue:row(revenue),tenantsByStatus,activation:row(activation),usage:row(usage),workload:row(workload),churn:row(churn),revenueSource:'GOCARDLESS_TENANT_SUBSCRIPTIONS_ONLY'};
  }
  async requestExport(actor:AgencyActor,exportType:string,filters:Record<string,unknown>){const allowed=['TENANTS','SUBSCRIPTIONS','ONBOARDING','FULFILMENT','AUDIT'];if(!allowed.includes(exportType))throw fail(400,'EXPORT_TYPE_INVALID','Unsupported agency export.');const [job]=await this.db.insert(agencyExportJobs).values({requestedByAgencyUserId:actor.agencyUserId,exportType,filtersJson:filters}).returning();await this.audit.write(actor,'AGENCY_EXPORT_REQUESTED','AGENCY_EXPORT',job.id,{metadata:{exportType}});return job;}
  async processDueOffboarding(){const due=await this.db.select().from(tenantSubscriptions).where(and(eq(tenantSubscriptions.status,'CANCELLATION_SCHEDULED'),lte(tenantSubscriptions.cancellationScheduledAt,new Date()))).orderBy(asc(tenantSubscriptions.cancellationScheduledAt)).limit(25);let applied=0;for(const sub of due){if(!sub.providerSubscriptionId)continue;await this.gc.request<any>(`/subscriptions/${encodeURIComponent(sub.providerSubscriptionId)}/actions/cancel`,'POST',{subscriptions:{metadata:{agency_reason:'scheduled_offboarding'}}},createHash('sha256').update(`offboard:${sub.id}`).digest('hex'));const changed=await this.db.transaction(async tx=>{const[ended]=await tx.update(tenantSubscriptions).set({status:'CANCELLED',cancelledAt:new Date(),updatedAt:new Date()}).where(and(eq(tenantSubscriptions.id,sub.id),eq(tenantSubscriptions.status,'CANCELLATION_SCHEDULED'))).returning();if(!ended)return false;await tx.update(tenants).set({lifecycleStatus:'OFFBOARDED',isActive:false,offboardedAt:new Date(),updatedAt:new Date()}).where(eq(tenants.id,sub.tenantId));await tx.update(tenantPlanAssignments).set({status:'ENDED',endsAt:new Date()}).where(and(eq(tenantPlanAssignments.tenantId,sub.tenantId),eq(tenantPlanAssignments.status,'ACTIVE')));return true;});if(changed){applied++;await this.audit.write(null,'TENANT_OFFBOARDED','TENANT',sub.tenantId,{tenantId:sub.tenantId,metadata:{subscriptionId:sub.id}});}}return{claimed:due.length,applied};}
  async applyDuePlanChanges(){const due=await this.db.select().from(tenantPlanAssignments).where(and(eq(tenantPlanAssignments.status,'ACTIVE'),lte(tenantPlanAssignments.scheduledReplacementAt,new Date()))).orderBy(asc(tenantPlanAssignments.scheduledReplacementAt)).limit(25);let applied=0;for(const assignment of due){if(!assignment.scheduledReplacementPlanVersionId)continue;const[target]=await this.db.select().from(platformPlanVersions).where(eq(platformPlanVersions.id,assignment.scheduledReplacementPlanVersionId)).limit(1);const[sub]=await this.db.select().from(tenantSubscriptions).where(and(eq(tenantSubscriptions.tenantId,assignment.tenantId),inArray(tenantSubscriptions.status,['ACTIVE','TRIALLING','GRACE_PERIOD']))).orderBy(desc(tenantSubscriptions.createdAt)).limit(1);if(!target||!sub?.providerSubscriptionId)continue;await this.gc.request<any>(`/subscriptions/${encodeURIComponent(sub.providerSubscriptionId)}`,'PUT',{subscriptions:{amount:target.monthlyPriceMinor,name:`KS OS ${target.name}`}},createHash('sha256').update(`plan-change:${assignment.id}:${target.id}`).digest('hex'));const changed=await this.db.transaction(async tx=>{const[ended]=await tx.update(tenantPlanAssignments).set({status:'ENDED',endsAt:new Date(),scheduledReplacementPlanVersionId:null,scheduledReplacementAt:null}).where(and(eq(tenantPlanAssignments.id,assignment.id),eq(tenantPlanAssignments.status,'ACTIVE'),eq(tenantPlanAssignments.scheduledReplacementPlanVersionId,target.id))).returning();if(!ended)return false;await tx.insert(tenantPlanAssignments).values({tenantId:assignment.tenantId,planVersionId:target.id,status:'ACTIVE',startsAt:new Date(),reason:'SCHEDULED_BILLING_BOUNDARY_CHANGE'});await tx.update(tenantSubscriptions).set({planVersionId:target.id,amountMinor:target.monthlyPriceMinor,updatedAt:new Date()}).where(eq(tenantSubscriptions.id,sub.id));return true;});if(changed)applied++;}return{claimed:due.length,applied};}
}
