import { createHash, randomUUID } from 'node:crypto';
import { and, asc, desc, eq, gt, isNull, lt, lte, or, sql } from 'drizzle-orm';
import {
  applicationSessions, clients, consentRecords, getDatabase, legalHolds, platformAuditEvents,
  privacyExportArtifacts, privacyRequests, retentionPolicies, retentionPolicyVersions, retentionRuns, users,
} from '@ks-os/database';
import type { z } from 'zod';
import type { AuditQuerySchema, CreateConsentRecordSchema, CreateLegalHoldSchema, CreatePrivacyRequestSchema, CreateRetentionPolicySchema, UpdatePrivacyRequestSchema } from '@ks-os/contracts';
import { SupabaseReportStorage } from '../reporting/report-storage.js';
import { AgencyAuditService, type AgencyActor } from './agency.service.js';

const fail=(statusCode:number,code:string,message:string)=>Object.assign(new Error(message),{statusCode,code});
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');

export class ComplianceService {
  private db=getDatabase();private audit=new AgencyAuditService();private storage=new SupabaseReportStorage();

  async listAudit(query:z.infer<typeof AuditQuerySchema>){
    const clauses=[] as any[];
    if(query.cursor)clauses.push(lt(platformAuditEvents.id,query.cursor));if(query.from)clauses.push(gt(platformAuditEvents.occurredAt,query.from));if(query.to)clauses.push(lte(platformAuditEvents.occurredAt,query.to));
    if(query.agencyUserId)clauses.push(eq(platformAuditEvents.agencyUserId,query.agencyUserId));if(query.tenantId)clauses.push(eq(platformAuditEvents.tenantId,query.tenantId));if(query.category)clauses.push(eq(platformAuditEvents.eventCategory,query.category));if(query.eventType)clauses.push(eq(platformAuditEvents.action,query.eventType));if(query.targetType)clauses.push(eq(platformAuditEvents.targetType,query.targetType));if(query.targetId)clauses.push(eq(platformAuditEvents.targetId,query.targetId));if(query.outcome)clauses.push(eq(platformAuditEvents.outcome,query.outcome));
    if(query.search)clauses.push(sql`(${platformAuditEvents.id}::text ilike ${`%${query.search}%`} or ${platformAuditEvents.targetId} ilike ${`%${query.search}%`} or ${platformAuditEvents.description} ilike ${`%${query.search}%`} or ${platformAuditEvents.action} ilike ${`%${query.search}%`})`);
    const rows=await this.db.select().from(platformAuditEvents).where(clauses.length?and(...clauses):undefined).orderBy(desc(platformAuditEvents.occurredAt),desc(platformAuditEvents.id)).limit(query.limit+1);
    const hasMore=rows.length>query.limit;const page=rows.slice(0,query.limit);return{rows:page,nextCursor:hasMore?page.at(-1)?.id:null};
  }
  async getAudit(id:string){const[row]=await this.db.select().from(platformAuditEvents).where(eq(platformAuditEvents.id,id)).limit(1);if(!row)throw fail(404,'AUDIT_EVENT_NOT_FOUND','Audit event not found.');return row;}

  async createConsent(actor:AgencyActor,input:z.infer<typeof CreateConsentRecordSchema>){
    const[record]=await this.db.insert(consentRecords).values({...input,grantedAt:input.status==='GRANTED'?new Date():undefined,withdrawnAt:input.status==='WITHDRAWN'?new Date():undefined,ipHash:actor.ipHash,userAgent:actor.userAgent}).returning();
    await this.audit.write(actor,input.status==='GRANTED'?'CONSENT_GRANTED':'CONSENT_WITHDRAWN','CONSENT_RECORD',record.id,{tenantId:input.tenantId,category:'CONSENT',description:`${input.consentType} consent ${input.status.toLowerCase()}`,metadata:{consentType:input.consentType,consentVersion:input.consentVersion,subjectClientId:input.clientId,subjectAuthUserId:input.authUserId}});return record;
  }
  async consentHistory(tenantId?:string,authUserId?:string,clientId?:string){const clauses=[] as any[];if(tenantId)clauses.push(eq(consentRecords.tenantId,tenantId));if(authUserId)clauses.push(eq(consentRecords.authUserId,authUserId));if(clientId)clauses.push(eq(consentRecords.clientId,clientId));if(!authUserId&&!clientId)throw fail(400,'CONSENT_SUBJECT_REQUIRED','A consent subject is required.');return this.db.select().from(consentRecords).where(and(...clauses)).orderBy(desc(consentRecords.createdAt)).limit(200);}

  async createPrivacyRequest(actor:AgencyActor,input:z.infer<typeof CreatePrivacyRequestSchema>){const dueAt=input.dueAt||new Date(Date.now()+30*86400000);const[record]=await this.db.insert(privacyRequests).values({tenantId:input.tenantId,requestType:input.requestType,subjectAuthUserId:input.subjectAuthUserId,subjectClientId:input.subjectClientId,subjectEmailHash:input.subjectEmail?sha(input.subjectEmail.trim().toLowerCase()):undefined,requestNotes:input.requestNotes,dueAt,createdByAgencyUserId:actor.agencyUserId,status:'IDENTITY_VERIFICATION_REQUIRED'}).returning();await this.audit.write(actor,'PRIVACY_REQUEST_CREATED','PRIVACY_REQUEST',record.id,{tenantId:input.tenantId,category:'PRIVACY',description:`${input.requestType} request received`,metadata:{publicReference:record.publicReference,requestType:input.requestType}});return record;}
  async listPrivacyRequests(){return this.db.select().from(privacyRequests).orderBy(asc(privacyRequests.dueAt),desc(privacyRequests.createdAt)).limit(200);}
  async updatePrivacyRequest(actor:AgencyActor,id:string,input:z.infer<typeof UpdatePrivacyRequestSchema>){const[before]=await this.db.select().from(privacyRequests).where(eq(privacyRequests.id,id)).limit(1);if(!before)throw fail(404,'PRIVACY_REQUEST_NOT_FOUND','Privacy request not found.');if(input.status==='READY_FOR_DOWNLOAD'&&before.requestType!=='ACCESS')throw fail(409,'PRIVACY_STATUS_INVALID','Only access requests can become ready for download.');const[record]=await this.db.update(privacyRequests).set({...input,completedAt:input.status==='COMPLETED'?new Date():before.completedAt,updatedAt:new Date()}).where(eq(privacyRequests.id,id)).returning();await this.audit.write(actor,'PRIVACY_REQUEST_UPDATED','PRIVACY_REQUEST',id,{tenantId:record.tenantId,category:'PRIVACY',description:'Privacy request workflow updated',previousValues:{status:before.status,identityVerificationStatus:before.identityVerificationStatus,deletionStrategy:before.deletionStrategy},newValues:{status:record.status,identityVerificationStatus:record.identityVerificationStatus,deletionStrategy:record.deletionStrategy}});return record;}

  async createLegalHold(actor:AgencyActor,input:z.infer<typeof CreateLegalHoldSchema>){const[record]=await this.db.insert(legalHolds).values({...input,createdByAgencyUserId:actor.agencyUserId}).returning();await this.audit.write(actor,'LEGAL_HOLD_CREATED','LEGAL_HOLD',record.id,{tenantId:record.tenantId,category:'PRIVACY',reason:input.reason,metadata:{legalBasis:input.legalBasis}});return record;}
  async releaseLegalHold(actor:AgencyActor,id:string,reason:string){const[record]=await this.db.update(legalHolds).set({status:'RELEASED',releasedAt:new Date(),releasedByAgencyUserId:actor.agencyUserId}).where(and(eq(legalHolds.id,id),eq(legalHolds.status,'ACTIVE'))).returning();if(!record)throw fail(404,'LEGAL_HOLD_NOT_FOUND','Active legal hold not found.');await this.audit.write(actor,'LEGAL_HOLD_RELEASED','LEGAL_HOLD',id,{tenantId:record.tenantId,category:'PRIVACY',reason});return record;}

  async createRetentionPolicy(actor:AgencyActor,input:z.infer<typeof CreateRetentionPolicySchema>){return this.db.transaction(async tx=>{const[record]=await tx.insert(retentionPolicies).values({...input,createdByAgencyUserId:actor.agencyUserId,approvedByAgencyUserId:input.enabled?actor.agencyUserId:undefined}).returning();await tx.insert(retentionPolicyVersions).values({policyId:record.id,version:record.version,snapshot:record,approvedByAgencyUserId:record.approvedByAgencyUserId});await this.audit.write(actor,'RETENTION_POLICY_CREATED','RETENTION_POLICY',record.id,{tenantId:record.tenantId,category:'RETENTION',description:'Versioned retention policy created',newValues:record,tx});return record;});}
  async listRetentionPolicies(){return this.db.select().from(retentionPolicies).orderBy(asc(retentionPolicies.dataCategory),desc(retentionPolicies.version)).limit(200);}
  async queueRetention(actor:AgencyActor,policyId:string,dryRun=true){const[policy]=await this.db.select().from(retentionPolicies).where(eq(retentionPolicies.id,policyId)).limit(1);if(!policy)throw fail(404,'RETENTION_POLICY_NOT_FOUND','Retention policy not found.');if(!dryRun&&!policy.enabled)throw fail(409,'RETENTION_POLICY_DISABLED','Enable and approve the policy before live execution.');const key=`${policy.id}:${new Date().toISOString().slice(0,10)}:${dryRun?'dry':'live'}`;const[run]=await this.db.insert(retentionRuns).values({policyId:policy.id,idempotencyKey:key,dryRun}).onConflictDoNothing({target:retentionRuns.idempotencyKey}).returning();await this.audit.write(actor,'RETENTION_RUN_QUEUED','RETENTION_RUN',run?.id||key,{tenantId:policy.tenantId,category:'RETENTION',metadata:{policyId,dryRun}});return run||{idempotencyKey:key,status:'ALREADY_QUEUED'};}

  async processAccessExports(limit=3){const claimed=await this.db.execute(sql`with candidates as (select id from privacy_requests where request_type='ACCESS' and status='PROCESSING' and identity_verification_status='VERIFIED' order by due_at,id for update skip locked limit ${Math.min(10,Math.max(1,limit))}) select * from privacy_requests where id in(select id from candidates)`);let ready=0,failed=0;for(const request of claimed.rows as any[]){try{const data=await this.subjectExport(request.tenant_id,request.subject_auth_user_id,request.subject_client_id);const body=Buffer.from(JSON.stringify({schemaVersion:1,generatedAt:new Date().toISOString(),requestReference:request.public_reference,data},null,2));if(body.byteLength>20_971_520)throw fail(413,'PRIVACY_EXPORT_TOO_LARGE','Privacy export exceeded the safe size limit.');const path=`privacy/${request.id}/${randomUUID()}.json`;await this.storage.upload(path,body,'application/json');const expiresAt=new Date(Date.now()+72*3600000);await this.db.transaction(async tx=>{await tx.insert(privacyExportArtifacts).values({requestId:request.id,storagePath:path,format:'JSON',byteSize:body.byteLength,checksumSha256:sha(body.toString('utf8')),expiresAt}).onConflictDoNothing({target:privacyExportArtifacts.requestId});await tx.update(privacyRequests).set({status:'READY_FOR_DOWNLOAD',updatedAt:new Date()}).where(eq(privacyRequests.id,request.id));});await this.audit.write(null,'PRIVACY_EXPORT_READY','PRIVACY_REQUEST',request.id,{tenantId:request.tenant_id,category:'PRIVACY',description:'Isolated personal-data export generated',metadata:{byteSize:body.byteLength,expiresAt}});ready++;}catch(error:any){await this.db.update(privacyRequests).set({status:'FAILED',failureReason:String(error?.code||'EXPORT_GENERATION_FAILED'),updatedAt:new Date()}).where(eq(privacyRequests.id,request.id));await this.audit.write(null,'PRIVACY_EXPORT_FAILED','PRIVACY_REQUEST',request.id,{tenantId:request.tenant_id,category:'PRIVACY',outcome:'FAILED',reason:String(error?.code||'EXPORT_GENERATION_FAILED')});failed++;}}return{claimed:claimed.rows.length,ready,failed};}
  async privacyDownload(actor:AgencyActor,id:string){const[artifact]=await this.db.select().from(privacyExportArtifacts).where(eq(privacyExportArtifacts.requestId,id)).limit(1);if(!artifact)throw fail(404,'PRIVACY_EXPORT_NOT_FOUND','Privacy export not found.');if(artifact.expiresAt<=new Date())throw fail(410,'PRIVACY_EXPORT_EXPIRED','Privacy export has expired.');await this.audit.write(actor,'PRIVACY_EXPORT_DOWNLOADED','PRIVACY_REQUEST',id,{category:'PRIVACY'});return{url:await this.storage.signedUrl(artifact.storagePath,120,`personal-data-${id}.json`),expiresAt:new Date(Date.now()+120000).toISOString(),checksumSha256:artifact.checksumSha256};}

  private async subjectExport(tenantId?:string,authUserId?:string,clientId?:string){if(!tenantId)throw fail(400,'PRIVACY_TENANT_REQUIRED','Tenant scope is required for export isolation.');let resolvedClientId=clientId;if(!resolvedClientId&&authUserId){const membership=await this.db.execute(sql`select c.id from customer_client_links l join clients c on c.id=l.client_id and c.tenant_id=l.tenant_id where l.tenant_id=${tenantId}::uuid and l.auth_user_id=${authUserId}::uuid and l.status='ACTIVE' limit 1`);resolvedClientId=(membership.rows[0] as any)?.id;}const profile=resolvedClientId?await this.db.execute(sql`select id,name,email,phone,loyalty_points,created_at,updated_at from clients where tenant_id=${tenantId}::uuid and id=${resolvedClientId}::uuid`):{rows:[]};const bookings=resolvedClientId?await this.db.execute(sql`select id,public_reference,service_id,start_time,end_time,status,payment_status,quoted_amount,created_at from appointments where tenant_id=${tenantId}::uuid and client_id=${resolvedClientId}::uuid order by created_at desc limit 10000`):{rows:[]};const payments=resolvedClientId?await this.db.execute(sql`select ct.id,ct.appointment_id,ct.total_amount,ct.payment_status,ct.payment_method,ct.created_at from checkout_transactions ct join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id where ct.tenant_id=${tenantId}::uuid and a.client_id=${resolvedClientId}::uuid order by ct.created_at desc limit 10000`):{rows:[]};const consent=await this.db.select().from(consentRecords).where(and(eq(consentRecords.tenantId,tenantId),or(resolvedClientId?eq(consentRecords.clientId,resolvedClientId):undefined,authUserId?eq(consentRecords.authUserId,authUserId):undefined))).orderBy(desc(consentRecords.createdAt)).limit(1000);return{profile:profile.rows[0]||null,bookings:bookings.rows,payments:payments.rows,consentHistory:consent};}

  async processDeletionRequests(limit=10){const rows=await this.db.select().from(privacyRequests).where(and(eq(privacyRequests.requestType,'DELETION'),eq(privacyRequests.status,'SCHEDULED'),lte(privacyRequests.scheduledFor,new Date()))).orderBy(asc(privacyRequests.scheduledFor)).limit(Math.min(50,Math.max(1,limit)));let completed=0,blocked=0;for(const request of rows){const[hold]=await this.db.select().from(legalHolds).where(and(eq(legalHolds.status,'ACTIVE'),or(request.tenantId?eq(legalHolds.tenantId,request.tenantId):undefined,request.subjectAuthUserId?eq(legalHolds.subjectAuthUserId,request.subjectAuthUserId):undefined,request.subjectClientId?eq(legalHolds.subjectClientId,request.subjectClientId):undefined),or(isNull(legalHolds.endsAt),gt(legalHolds.endsAt,new Date())))).limit(1);if(hold){await this.db.update(privacyRequests).set({status:'IN_REVIEW',decisionReason:'Blocked by active legal hold',legalHoldCheckedAt:new Date(),updatedAt:new Date()}).where(eq(privacyRequests.id,request.id));blocked++;continue;}if(request.deletionStrategy!=='ANONYMISE'&&request.deletionStrategy!=='DEACTIVATE'){await this.db.update(privacyRequests).set({status:'IN_REVIEW',decisionReason:'Manual compliance execution required for this deletion strategy',legalHoldCheckedAt:new Date(),updatedAt:new Date()}).where(eq(privacyRequests.id,request.id));blocked++;continue;}await this.db.transaction(async tx=>{if(request.subjectClientId&&request.deletionStrategy==='ANONYMISE')await tx.update(clients).set({name:`Anonymised ${request.subjectClientId.slice(0,8)}`,email:null,phone:null,phoneE164:null,medicalNotes:null,updatedAt:new Date()}).where(and(eq(clients.id,request.subjectClientId),request.tenantId?eq(clients.tenantId,request.tenantId):undefined));if(request.subjectAuthUserId){await tx.update(applicationSessions).set({revokedAt:new Date(),revokeReason:'PRIVACY_DELETION'}).where(and(eq(applicationSessions.authUserId,request.subjectAuthUserId),isNull(applicationSessions.revokedAt)));if(request.deletionStrategy==='DEACTIVATE')await tx.update(users).set({accountStatus:'DEACTIVATED',authUserId:null,updatedAt:new Date()}).where(eq(users.authUserId,request.subjectAuthUserId));}await tx.update(privacyRequests).set({status:'COMPLETED',completedAt:new Date(),legalHoldCheckedAt:new Date(),updatedAt:new Date()}).where(eq(privacyRequests.id,request.id));});await this.audit.write(null,'PRIVACY_DELETION_COMPLETED','PRIVACY_REQUEST',request.id,{tenantId:request.tenantId,category:'PRIVACY',description:'Privacy deletion strategy completed',metadata:{strategy:request.deletionStrategy,proof:sha(`${request.id}:${request.updatedAt.toISOString()}`)}});completed++;}return{claimed:rows.length,completed,blocked};}
}
