import React, { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { agencyFetch } from './AgencyAuth';

const badge = (value: string) => <span className="rounded-full border border-slate-700 bg-slate-950 px-2 py-1 text-[10px] font-black">{value.replaceAll('_', ' ')}</span>;

export function AgencyFactFindingPage() {
  const [templates, setTemplates] = useState<any[]>([]);
  const [questionnaire, setQuestionnaire] = useState<any>(null);
  const [responses, setResponses] = useState<any[]>([]);
  const [brief, setBrief] = useState<any>(null);
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [refs, setRefs] = useState({ tenantReference: '', templateReference: '', questionnaireReference: '', briefReference: '', participantName: '', participantEmail: '' });

  useEffect(() => { void agencyFetch('/fact-finding/templates').then(setTemplates).catch(error => setError(error.message)); }, []);
  const run = async (operation: () => Promise<any>, after?: (value: any) => void) => {
    setError(''); setNotice('');
    try { const value = await operation(); after?.(value); return value; } catch (caught: any) { setError(caught.message); return null; }
  };
  const load = async (reference = refs.questionnaireReference) => {
    if (!reference) return;
    setRefs(value => ({ ...value, questionnaireReference: reference }));
    await run(async () => {
      const [detail, responseRows] = await Promise.all([
        agencyFetch(`/fact-finding/questionnaires/${reference}`),
        agencyFetch(`/fact-finding/questionnaires/${reference}/responses`),
      ]);
      setQuestionnaire(detail); setResponses(responseRows); return detail;
    });
  };
  const loadBrief = async (reference = refs.briefReference) => {
    if (!reference) return;
    setRefs(value => ({ ...value, briefReference: reference }));
    await run(() => agencyFetch(`/production-briefs/${reference}`), setBrief);
  };

  return <div className="space-y-5">
    <header className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-black uppercase tracking-widest text-violet-300">Controlled intake</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Client fact-finding</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Prequalify the questionnaire, verify each usable fact, resolve clarification, then approve and lock a versioned production brief.</p></div><Link to="/agency/provisioning" className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-black">Open provisioning</Link></div></header>
    {error && <p role="alert" className="rounded-xl border border-rose-900 bg-rose-950/40 p-4 text-sm text-rose-200">{error}</p>}{notice && <p role="status" className="rounded-xl border border-emerald-900 bg-emerald-950/40 p-4 text-sm text-emerald-200">{notice}</p>}

    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xs font-black uppercase tracking-widest text-slate-400">Questionnaire templates</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{templates.map(template => <button key={template.reference} onClick={() => setRefs(value => ({ ...value, templateReference: template.reference }))} className={`rounded-xl border p-4 text-left ${refs.templateReference === template.reference ? 'border-violet-500 bg-violet-950/30' : 'border-slate-800 bg-slate-950'}`}><strong>{template.name}</strong><p className="mt-1 text-xs text-slate-500">{template.key} · version {template.version}</p><div className="mt-2">{badge(template.status)}</div></button>)}</div></section>

    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xs font-black uppercase tracking-widest text-slate-400">Create and track questionnaire</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input aria-label="Tenant reference" placeholder="Tenant public reference" value={refs.tenantReference} onChange={event => setRefs(value => ({ ...value, tenantReference: event.target.value }))} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input aria-label="Template reference" placeholder="Template public reference" value={refs.templateReference} onChange={event => setRefs(value => ({ ...value, templateReference: event.target.value }))} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input aria-label="Participant name" placeholder="Client contact name" value={refs.participantName} onChange={event => setRefs(value => ({ ...value, participantName: event.target.value }))} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/><input aria-label="Participant email" placeholder="Client email" type="email" value={refs.participantEmail} onChange={event => setRefs(value => ({ ...value, participantEmail: event.target.value }))} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm"/></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void run(() => agencyFetch('/fact-finding/questionnaires', { method: 'POST', body: JSON.stringify({ tenantReference: refs.tenantReference, questionnaire: { templateReference: refs.templateReference, participant: refs.participantEmail ? { displayName: refs.participantName, email: refs.participantEmail } : undefined } }) }), value => { setQuestionnaire(value); setRefs(current => ({ ...current, questionnaireReference: value.reference })); setNotice('Questionnaire created. Review every question before inviting the client.'); })} className="rounded-xl bg-violet-600 px-4 py-3 text-xs font-black">Create questionnaire</button><input aria-label="Questionnaire reference" placeholder="Questionnaire reference" value={refs.questionnaireReference} onChange={event => setRefs(value => ({ ...value, questionnaireReference: event.target.value }))} className="min-w-72 rounded-xl border border-slate-700 bg-slate-950 p-3 text-xs"/><button onClick={() => void load()} className="rounded-xl border border-slate-700 px-4 py-3 text-xs font-black">Load</button></div></section>

    {questionnaire && <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-black">{questionnaire.tenantName || 'Questionnaire'}</h2><p className="text-xs text-slate-500">{questionnaire.reference} · version {questionnaire.version || questionnaire.questionnaireVersion}</p></div>{badge(questionnaire.status)}</div><div className="mt-4 grid gap-2 md:grid-cols-2">{questionnaire.questions?.map((question: any) => <div key={question.reference} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-2"><strong className="text-sm">{question.label}</strong>{question.required && badge('REQUIRED')}</div><p className="mt-1 text-xs text-slate-500">{question.fieldMapping || 'PRIVATE INTAKE'} · {question.questionType}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => void run(() => agencyFetch(`/fact-finding/questionnaires/${questionnaire.reference}/prequalify`, { method: 'POST', body: JSON.stringify({ questionOverrides: questionnaire.questions.map((question: any) => ({ questionReference: question.reference, included: true, required: question.required })) }) }), value => { setQuestionnaire(value); setNotice('Questionnaire prequalified.'); })} className="rounded-xl border border-violet-700 px-4 py-2 text-xs font-black">Prequalify questionnaire</button><button onClick={() => void run(() => agencyFetch(`/fact-finding/questionnaires/${questionnaire.reference}/invite`, { method: 'POST', body: '{}' }), () => setNotice('Secure invitation queued through the existing email outbox.'))} className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-black">Send to client</button><button onClick={() => void load(questionnaire.reference)} className="rounded-xl border border-slate-700 px-4 py-2 text-xs font-black">Refresh completion</button></div></section>}

    {responses.length > 0 && <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xs font-black uppercase tracking-widest text-slate-400">Response review</h2><div className="mt-4 space-y-3">{responses.map(response => <article key={response.reference} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex flex-wrap justify-between gap-2"><div><strong>{response.label || response.fieldMapping}</strong><p className="mt-1 text-xs text-slate-500">{response.source === 'CLIENT_PROVIDED' ? 'CLIENT PROVIDED' : 'AGENCY PROVIDED'} · {response.fieldMapping}</p></div>{badge(response.status)}</div><pre className="mt-3 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-900 p-3 text-xs">{JSON.stringify(response.answer, null, 2)}</pre><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => void run(() => agencyFetch(`/fact-finding/responses/${response.reference}/approve`, { method: 'POST', body: JSON.stringify({ publicUseEligible: true, bookingUseEligible: Boolean(response.bookingUseAllowed ?? true), generationUseEligible: true, note: 'Approved during controlled agency review.' }) }), () => void load())} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black">Approve for booking + website + AI</button><button onClick={() => { const message = prompt('Clarification request'); if (message) void run(() => agencyFetch(`/fact-finding/responses/${response.reference}/request-clarification`, { method: 'POST', body: JSON.stringify({ message, requiredResponseType: 'TEXT', evidenceRequested: false }) }), () => void load()); }} className="rounded-lg border border-amber-700 px-3 py-2 text-xs font-black text-amber-300">Request clarification</button><button onClick={() => { const reason = prompt('Rejection reason'); if (reason) void run(() => agencyFetch(`/fact-finding/responses/${response.reference}/reject`, { method: 'POST', body: JSON.stringify({ reason }) }), () => void load()); }} className="rounded-lg border border-rose-800 px-3 py-2 text-xs font-black text-rose-300">Reject</button></div></article>)}</div><button onClick={() => void run(() => agencyFetch(`/fact-finding/questionnaires/${refs.questionnaireReference}/build-brief`, { method: 'POST', body: '{}' }), value => { setBrief(value); setRefs(current => ({ ...current, briefReference: value.reference })); setNotice('Versioned production brief created from approved responses only.'); })} className="mt-5 rounded-xl bg-violet-600 px-4 py-3 text-xs font-black">Generate production brief</button></section>}

    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap gap-2"><input aria-label="Production brief reference" placeholder="Production brief reference" value={refs.briefReference} onChange={event => setRefs(value => ({ ...value, briefReference: event.target.value }))} className="min-w-80 flex-1 rounded-xl border border-slate-700 bg-slate-950 p-3 text-xs"/><button onClick={() => void loadBrief()} className="rounded-xl border border-slate-700 px-4 py-2 text-xs font-black">Load brief</button></div>{brief && <div className="mt-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-lg font-black">Production brief v{brief.version}</h2><p className="text-xs text-slate-500">Immutable after lock · provenance retained per fact</p></div>{badge(brief.status)}</div><div className="mt-4 grid gap-3 md:grid-cols-4"><div className="rounded-xl bg-slate-950 p-3"><small>Completion</small><strong className="block text-xl">{brief.readiness?.completionPercentage || 0}%</strong></div><div className="rounded-xl bg-slate-950 p-3"><small>Approved facts</small><strong className="block text-xl">{brief.readiness?.approvedFactCount || 0}</strong></div><div className="rounded-xl bg-slate-950 p-3"><small>Clarifications</small><strong className="block text-xl">{brief.readiness?.clarificationCount || 0}</strong></div><div className="rounded-xl bg-slate-950 p-3"><small>Readiness</small><strong className="block text-sm">{brief.readiness?.readyForProvisioning ? 'READY' : 'BLOCKED'}</strong></div></div>{brief.readiness?.blockingIssues?.map((issue: any) => <p key={issue.code} className="mt-2 rounded-lg border border-rose-900 p-3 text-xs text-rose-200">{issue.code} — {issue.message || 'Resolve before provisioning.'}</p>)}<div className="mt-5 flex flex-wrap gap-2"><button disabled={brief.status !== 'REVIEW_REQUIRED'} onClick={() => void run(() => agencyFetch(`/production-briefs/${brief.reference}/approve`, { method: 'POST' }), setBrief)} className="rounded-xl border border-emerald-700 px-4 py-2 text-xs font-black text-emerald-300 disabled:opacity-40">Approve brief</button><button disabled={brief.status !== 'APPROVED'} onClick={() => void run(() => agencyFetch(`/production-briefs/${brief.reference}/lock`, { method: 'POST' }), value => { setBrief(value); setNotice('Brief locked for provisioning. Any change requires a new version.'); })} className="rounded-xl bg-emerald-700 px-4 py-2 text-xs font-black disabled:opacity-40">Lock for provisioning</button></div></div>}</section>
  </div>;
}
