import { z } from 'zod';

export const IntegrationProviderSchema=z.enum(['GOOGLE_CALENDAR','MICROSOFT_OUTLOOK','ICAL','XERO','QUICKBOOKS','CSV','JSON','STRIPE_TERMINAL']);
export const IntegrationStatusSchema=z.enum(['NOT_CONNECTED','CONNECTING','CONNECTED','DEGRADED','REAUTHORISATION_REQUIRED','DISABLED','FAILED','DISCONNECTED']);
export const CreateCalendarFeedSchema=z.object({scope:z.enum(['BUSINESS','STAFF','LOCATION']),staffUserId:z.string().uuid().optional(),locationId:z.string().uuid().optional(),privacyLevel:z.enum(['BUSY_ONLY','BOOKING_SUMMARY']).default('BUSY_ONLY'),bookingStatuses:z.array(z.enum(['CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED','CANCELLED'])).min(1).max(8).default(['CONFIRMED'])}).strict().superRefine((v,c)=>{if(v.scope==='STAFF'&&!v.staffUserId)c.addIssue({code:'custom',path:['staffUserId'],message:'Staff scope requires staffUserId'});if(v.scope==='LOCATION'&&!v.locationId)c.addIssue({code:'custom',path:['locationId'],message:'Location scope requires locationId'});});
export const CreateApiCredentialSchema=z.object({name:z.string().trim().min(3).max(120),scopes:z.array(z.enum(['bookings:read','bookings:write','customers:read','services:read','staff:read','locations:read','availability:read','payments:read','webhooks:manage'])).min(1).max(12),environment:z.enum(['test','live']).default('live'),expiresAt:z.coerce.date().optional()}).strict();
export const CreateWebhookSubscriptionSchema=z.object({name:z.string().trim().min(3).max(120),targetUrl:z.string().url().max(2048),eventTypes:z.array(z.string().regex(/^[a-z]+\.[a-z_]+\.v1$/)).min(1).max(30),description:z.string().trim().max(500).optional(),environment:z.enum(['test','live']).default('live')}).strict();
export const AccountingExportQuerySchema=z.object({from:z.coerce.date(),to:z.coerce.date(),format:z.enum(['csv','json']).default('csv'),locationId:z.string().uuid().optional(),paymentStatus:z.enum(['SUCCEEDED','REFUNDED']).optional()}).strict().refine(v=>v.to>v.from&&v.to.getTime()-v.from.getTime()<=366*86400000,'Date range must be positive and no longer than 366 days');
export const OAuthStartSchema=z.object({provider:z.enum(['GOOGLE_CALENDAR','MICROSOFT_OUTLOOK','XERO','QUICKBOOKS']),returnPath:z.string().regex(/^\/[A-Za-z0-9/_-]*$/).default('/app/settings/integrations')}).strict();
export const TerminalConnectionTokenSchema=z.object({locationId:z.string().uuid()}).strict();
