import {and,asc,desc,eq,getTableColumns,ilike,inArray,lt,or,sql} from 'drizzle-orm';
import {appointments,automationRuns,checkoutTransactions,clients,formAssignments,getDatabase,internalNotifications,operationsIssues,products,stripeRefunds,taskActivity,tasks,tenants,users} from '@ks-os/database';
import type {CreateTaskInput,TaskListQuery,UpdateTaskInput} from '@ks-os/contracts';
import {effectiveCapabilities,type AccessProfile} from '@ks-os/auth';
import {can,canComplete,canUpdate,canViewAll,isFinanceSource,isTaskOverdue,type TaskActor} from './task.permissions.js';
import {taskError} from './task.errors.js';

const iso=(v:Date|string|null)=>v?new Date(v).toISOString():null;
const encodeCursor=(updatedAt:Date|string,id:string)=>Buffer.from(JSON.stringify([iso(updatedAt),id])).toString('base64url');
export function decodeTaskCursor(cursor:string):[Date,string]{try{const value=JSON.parse(Buffer.from(cursor,'base64url').toString('utf8'));if(!Array.isArray(value)||value.length!==2||Number.isNaN(Date.parse(value[0]))||typeof value[1]!=='string')throw 0;return[new Date(value[0]),value[1]];}catch{throw taskError(400,'INVALID_TASK_CURSOR','The task cursor is invalid.');}}
const serialize=(row:any,detail=false)=>{const base={id:row.id,title:row.title,status:row.status,priority:row.priority,dueAt:iso(row.dueAt),overdue:isTaskOverdue(row.status,row.dueAt),tenantTimezone:row.tenantTimezone,assignedUser:row.assignedUserId?{id:row.assignedUserId,name:row.assignedUserName}:null,sourceType:row.sourceType,appointmentId:row.appointmentId,clientId:row.clientId,operationsIssueId:row.operationsIssueId,createdAt:iso(row.createdAt),updatedAt:iso(row.updatedAt)};return detail?{...base,description:row.description,notes:row.notes,sourceId:row.sourceId,formAssignmentId:row.formAssignmentId,automationRunId:row.automationRunId,createdByUserId:row.createdByUserId,completedAt:iso(row.completedAt),completedByUserId:row.completedByUserId,cancelledAt:iso(row.cancelledAt),cancelledByUserId:row.cancelledByUserId}:base;};
const taskSelection={...getTableColumns(tasks),assignedUserName:users.name,tenantTimezone:tenants.timezone};

export class TaskService{
 private db=getDatabase();
 private require(actor:TaskActor,cap:string){if(!can(actor,cap))throw taskError(403,'TASK_FORBIDDEN','You do not have permission to perform this task action.');}
 private visibility(actor:TaskActor){return canViewAll(actor)?undefined:eq(tasks.assignedUserId,actor.userId);}
 private financeVisibility(actor:TaskActor){return can(actor,'FINANCE_VIEW')?undefined:sql`${tasks.sourceType} NOT IN ('PAYMENT','REFUND')`;}
 private async row(actor:TaskActor,id:string){const[row]=await this.db.select(taskSelection).from(tasks).leftJoin(users,and(eq(users.id,tasks.assignedUserId),eq(users.tenantId,actor.tenantId))).innerJoin(tenants,eq(tenants.id,tasks.tenantId)).where(and(eq(tasks.id,id),eq(tasks.tenantId,actor.tenantId),this.visibility(actor),this.financeVisibility(actor))).limit(1);if(!row)throw taskError(404,'TASK_NOT_FOUND','Task not found.');return row;}
 async list(actor:TaskActor,q:TaskListQuery){if(!can(actor,'TASKS_VIEW_OWN')&&!canViewAll(actor))this.require(actor,'TASKS_VIEW_OWN');const conditions:any[]=[eq(tasks.tenantId,actor.tenantId),this.visibility(actor),this.financeVisibility(actor)];if(q.status)conditions.push(eq(tasks.status,q.status));if(q.priority)conditions.push(eq(tasks.priority,q.priority));if(q.assignedTo)conditions.push(eq(tasks.assignedUserId,q.assignedTo==='me'?actor.userId:q.assignedTo));if(q.sourceType)conditions.push(eq(tasks.sourceType,q.sourceType));if(q.overdue!==undefined)conditions.push(q.overdue?and(inArray(tasks.status,['OPEN','IN_PROGRESS']),lt(tasks.dueAt,new Date())):or(sql`${tasks.dueAt} IS NULL`,sql`${tasks.dueAt} >= now()`,sql`${tasks.status} NOT IN ('OPEN','IN_PROGRESS')`));if(q.dueFrom)conditions.push(sql`${tasks.dueAt} >= ${new Date(q.dueFrom)}`);if(q.dueTo)conditions.push(sql`${tasks.dueAt} <= ${new Date(q.dueTo)}`);if(q.search)conditions.push(ilike(tasks.title,`%${q.search.replace(/[%_]/g,'\\$&')}%`));if(q.cursor){const[d,id]=decodeTaskCursor(q.cursor);conditions.push(or(lt(tasks.updatedAt,d),and(eq(tasks.updatedAt,d),lt(tasks.id,id))));}const rows=await this.db.select(taskSelection).from(tasks).leftJoin(users,and(eq(users.id,tasks.assignedUserId),eq(users.tenantId,actor.tenantId))).innerJoin(tenants,eq(tenants.id,tasks.tenantId)).where(and(...conditions)).orderBy(desc(tasks.updatedAt),desc(tasks.id)).limit(q.limit+1);const page=rows.slice(0,q.limit);return{data:page.map(x=>serialize(x)),nextCursor:rows.length>q.limit?encodeCursor(page.at(-1)!.updatedAt,page.at(-1)!.id):null};}
 async get(actor:TaskActor,id:string){if(!can(actor,'TASKS_VIEW_OWN')&&!canViewAll(actor))this.require(actor,'TASKS_VIEW_OWN');return serialize(await this.row(actor,id),true);}
 async activity(actor:TaskActor,id:string){await this.get(actor,id);const rows=await this.db.select().from(taskActivity).where(and(eq(taskActivity.tenantId,actor.tenantId),eq(taskActivity.taskId,id))).orderBy(asc(taskActivity.createdAt));return rows.map(x=>({id:x.id,activityType:x.activityType,actorUserId:x.actorUserId,fromValue:x.fromValue,toValue:x.toValue,createdAt:x.createdAt.toISOString()}));}
 private async assignee(actor:TaskActor,id:string|null|undefined,finance=false){if(!id)return null;const[u]=await this.db.select().from(users).where(and(eq(users.id,id),eq(users.tenantId,actor.tenantId),eq(users.accountStatus,'ACTIVE'))).limit(1);if(!u)throw taskError(400,'TASK_INVALID_ASSIGNEE','Assignee must be an active member of this workspace.');if(finance){const caps=effectiveCapabilities(u.role as 'owner'|'staff',(u.accessProfile||'PRACTITIONER') as AccessProfile,(u.permissions||{}) as Record<string,boolean>);if(!caps.includes('FINANCE_VIEW'))throw taskError(400,'TASK_ASSIGNEE_CANNOT_VIEW_SOURCE','Assignee cannot access the linked finance record.');}return u;}
 private async validateSource(actor:TaskActor,input:CreateTaskInput,allowAutomation=false){const type=input.sourceType,id=input.sourceId;if(type==='MANUAL'){if(id)throw taskError(400,'TASK_SOURCE_INVALID','Manual tasks cannot have a source ID.');return;}if(type==='AUTOMATION'){if(!allowAutomation)throw taskError(403,'TASK_AUTOMATION_SOURCE_INTERNAL','Automation tasks may only be created by the automation worker.');return;}if(!id)throw taskError(400,'TASK_SOURCE_REQUIRED','A source ID is required for linked tasks.');const table:any=type==='OPERATIONS_ISSUE'?operationsIssues:type==='APPOINTMENT'?appointments:type==='CLIENT'?clients:type==='FORM_ASSIGNMENT'?formAssignments:type==='PAYMENT'?checkoutTransactions:type==='REFUND'?stripeRefunds:products;const[row]=await this.db.select({id:table.id}).from(table).where(and(eq(table.id,id),eq(table.tenantId,actor.tenantId))).limit(1);if(!row)throw taskError(400,'TASK_SOURCE_NOT_FOUND','The linked source was not found in this workspace.');}
 private async validateLinks(actor:TaskActor,input:CreateTaskInput){for(const [id,table] of [[input.appointmentId,appointments],[input.clientId,clients],[input.operationsIssueId,operationsIssues],[input.formAssignmentId,formAssignments]] as const){if(!id)continue;const[row]=await this.db.select({id:table.id}).from(table).where(and(eq(table.id,id),eq(table.tenantId,actor.tenantId))).limit(1);if(!row)throw taskError(400,'TASK_LINK_NOT_FOUND','A linked record was not found in this workspace.');}}
 private notifyValues(tenantId:string,recipientUserId:string,type:string,title:string,message:string,sourceId:string){return{tenantId,recipientUserId,type,title,message,sourceType:'task',sourceId};}
 async create(actor:TaskActor,input:CreateTaskInput,internal?:{deduplicationKey?:string;automationRunId?:string;allowAutomation?:boolean}){this.require(actor,'TASKS_CREATE');if(isFinanceSource(input.sourceType))this.require(actor,'FINANCE_VIEW');const assignedUserId=input.assignedUserId??(!can(actor,'TASKS_ASSIGN')?actor.userId:null);if(assignedUserId!==actor.userId&&!can(actor,'TASKS_ASSIGN'))this.require(actor,'TASKS_ASSIGN');await this.validateSource(actor,input,internal?.allowAutomation);await this.validateLinks(actor,input);await this.assignee(actor,assignedUserId,isFinanceSource(input.sourceType));const created=await this.db.transaction(async tx=>{const[row]=await tx.insert(tasks).values({tenantId:actor.tenantId,title:input.title,description:input.description??null,notes:input.notes??null,priority:input.priority,status:'OPEN',assignedUserId,createdByUserId:actor.userId,dueAt:input.dueAt?new Date(input.dueAt):null,sourceType:input.sourceType,sourceId:input.sourceId??null,deduplicationKey:internal?.deduplicationKey,appointmentId:input.appointmentId??null,clientId:input.clientId??null,operationsIssueId:input.operationsIssueId??null,formAssignmentId:input.formAssignmentId??null,automationRunId:internal?.automationRunId??null}).onConflictDoNothing().returning();if(!row){const[existing]=await tx.select({id:tasks.id}).from(tasks).where(and(eq(tasks.tenantId,actor.tenantId),eq(tasks.deduplicationKey,internal!.deduplicationKey!))).limit(1);return existing!;}await tx.insert(taskActivity).values([{tenantId:actor.tenantId,taskId:row.id,activityType:'CREATED',actorUserId:actor.userId},...(row.assignedUserId?[{tenantId:actor.tenantId,taskId:row.id,activityType:'ASSIGNED',actorUserId:actor.userId,toValue:row.assignedUserId}]:[])] as any);if(row.assignedUserId)await tx.insert(internalNotifications).values(this.notifyValues(actor.tenantId,row.assignedUserId,'TASK_ASSIGNED','Task assigned',row.title,row.id));if(row.priority==='URGENT'&&row.assignedUserId)await tx.insert(internalNotifications).values(this.notifyValues(actor.tenantId,row.assignedUserId,'TASK_URGENT','Urgent task created',row.title,row.id));return row;});return this.get({...actor,permissions:[...new Set([...actor.permissions,'TASKS_VIEW_ALL'])]},created.id);}
 async createAutomationTask(input:{tenantId:string;automationRunId:string;idempotencyKey:string;createdByUserId:string;appointmentId?:string;clientId?:string;appointmentStaffId?:string;titleTemplateKey:'follow-up-client'|'review-form'|'rebook-cancelled'|'resolve-payment';assignTo:'APPOINTMENT_STAFF'|'OWNER'|'SPECIFIC_USER';specificUserId?:string;dueOffsetMinutes:number;priority:'LOW'|'NORMAL'|'HIGH'|'URGENT'}){const title={"follow-up-client":'Follow up with client',"review-form":'Review client form',"rebook-cancelled":'Rebook cancelled appointment',"resolve-payment":'Resolve payment follow-up'}[input.titleTemplateKey];let assignedUserId=input.specificUserId;if(input.assignTo==='APPOINTMENT_STAFF')assignedUserId=input.appointmentStaffId;if(input.assignTo==='OWNER'){const[owner]=await this.db.select({id:users.id}).from(users).where(and(eq(users.tenantId,input.tenantId),eq(users.role,'owner'),eq(users.accountStatus,'ACTIVE'))).limit(1);assignedUserId=owner?.id;}if(!assignedUserId)throw taskError(409,'AUTOMATION_STATE_CHANGED','The configured task assignee is unavailable.');return this.create({tenantId:input.tenantId,userId:input.createdByUserId,role:'owner',permissions:[]},{title,priority:input.priority,assignedUserId,dueAt:new Date(Date.now()+input.dueOffsetMinutes*60000).toISOString(),sourceType:'AUTOMATION',sourceId:input.automationRunId,appointmentId:input.appointmentId,clientId:input.clientId},{deduplicationKey:input.idempotencyKey,automationRunId:input.automationRunId,allowAutomation:true});}
 async update(actor:TaskActor,id:string,input:UpdateTaskInput){const current=await this.row(actor,id);if(!canUpdate(actor,current.assignedUserId))throw taskError(403,'TASK_FORBIDDEN','You cannot update this task.');if(['COMPLETED','CANCELLED'].includes(current.status))throw taskError(409,'TASK_NOT_ACTIONABLE','Completed or cancelled tasks must be reopened first.');await this.db.transaction(async tx=>{await tx.update(tasks).set({...input,dueAt:input.dueAt===undefined?undefined:input.dueAt?new Date(input.dueAt):null,updatedAt:new Date(),overdueNotifiedAt:input.dueAt!==undefined?null:undefined}).where(and(eq(tasks.id,id),eq(tasks.tenantId,actor.tenantId)));const events:any[]=[];if(input.priority&&input.priority!==current.priority)events.push({activityType:'PRIORITY_CHANGED',fromValue:current.priority,toValue:input.priority});if(input.dueAt!==undefined&&input.dueAt!==iso(current.dueAt))events.push({activityType:'DUE_DATE_CHANGED',fromValue:iso(current.dueAt),toValue:input.dueAt});if(events.length)await tx.insert(taskActivity).values(events.map(x=>({...x,tenantId:actor.tenantId,taskId:id,actorUserId:actor.userId})));});return this.get(actor,id);}
 async assign(actor:TaskActor,id:string,assignedUserId:string){this.require(actor,'TASKS_ASSIGN');const current=await this.row({...actor,permissions:[...actor.permissions,'TASKS_VIEW_ALL']},id);if(['COMPLETED','CANCELLED'].includes(current.status))throw taskError(409,'TASK_NOT_ACTIONABLE','Completed or cancelled tasks cannot be reassigned.');await this.assignee(actor,assignedUserId,isFinanceSource(current.sourceType));if(current.assignedUserId===assignedUserId)return serialize(current,true);await this.db.transaction(async tx=>{await tx.update(tasks).set({assignedUserId,updatedAt:new Date()}).where(and(eq(tasks.id,id),eq(tasks.tenantId,actor.tenantId)));await tx.insert(taskActivity).values({tenantId:actor.tenantId,taskId:id,activityType:current.assignedUserId?'REASSIGNED':'ASSIGNED',actorUserId:actor.userId,fromValue:current.assignedUserId,toValue:assignedUserId});await tx.insert(internalNotifications).values(this.notifyValues(actor.tenantId,assignedUserId,current.assignedUserId?'TASK_REASSIGNED':'TASK_ASSIGNED',current.assignedUserId?'Task reassigned':'Task assigned',current.title,id));});return this.get({...actor,permissions:[...actor.permissions,'TASKS_VIEW_ALL']},id);}
 private async transition(actor:TaskActor,id:string,to:'IN_PROGRESS'|'COMPLETED'|'OPEN'|'CANCELLED'){const current=await this.row(actor,id);const completing=to==='COMPLETED'||to==='CANCELLED';if(completing?!canComplete(actor,current.assignedUserId):!canUpdate(actor,current.assignedUserId))throw taskError(403,'TASK_FORBIDDEN','You cannot change this task status.');const allowed:Record<string,string[]>={IN_PROGRESS:['OPEN'],COMPLETED:['OPEN','IN_PROGRESS'],OPEN:['COMPLETED','CANCELLED'],CANCELLED:['OPEN','IN_PROGRESS']};if(!allowed[to].includes(current.status))throw taskError(409,'TASK_INVALID_TRANSITION',`Task cannot move from ${current.status} to ${to}.`);const now=new Date();const activity={IN_PROGRESS:'STARTED',COMPLETED:'COMPLETED',OPEN:'REOPENED',CANCELLED:'CANCELLED'}[to];await this.db.transaction(async tx=>{const[row]=await tx.update(tasks).set({status:to,updatedAt:now,completedAt:to==='COMPLETED'?now:to==='OPEN'?null:current.completedAt,completedByUserId:to==='COMPLETED'?actor.userId:to==='OPEN'?null:current.completedByUserId,cancelledAt:to==='CANCELLED'?now:to==='OPEN'?null:current.cancelledAt,cancelledByUserId:to==='CANCELLED'?actor.userId:to==='OPEN'?null:current.cancelledByUserId,overdueNotifiedAt:to==='OPEN'?null:current.overdueNotifiedAt}).where(and(eq(tasks.id,id),eq(tasks.tenantId,actor.tenantId),eq(tasks.status,current.status))).returning({id:tasks.id});if(!row)throw taskError(409,'TASK_CONCURRENT_UPDATE','The task changed while this action was running.');await tx.insert(taskActivity).values({tenantId:actor.tenantId,taskId:id,activityType:activity,actorUserId:actor.userId,fromValue:current.status,toValue:to});});return this.get(actor,id);}
 start(a:TaskActor,id:string){return this.transition(a,id,'IN_PROGRESS');}complete(a:TaskActor,id:string){return this.transition(a,id,'COMPLETED');}reopen(a:TaskActor,id:string){return this.transition(a,id,'OPEN');}cancel(a:TaskActor,id:string){return this.transition(a,id,'CANCELLED');}
 async createFromIssue(actor:TaskActor,issueId:string,input:Omit<CreateTaskInput,'sourceType'|'sourceId'|'operationsIssueId'>){const[issue]=await this.db.select().from(operationsIssues).where(and(eq(operationsIssues.id,issueId),eq(operationsIssues.tenantId,actor.tenantId),can(actor,'OPERATIONS_VIEW_ALL')?undefined:eq(operationsIssues.assignedToUserId,actor.userId))).limit(1);if(!issue)throw taskError(404,'OPERATIONS_ISSUE_NOT_FOUND','Issue not found.');if(['PAYMENT','REFUND'].includes(issue.category)&&!can(actor,'FINANCE_VIEW'))throw taskError(404,'OPERATIONS_ISSUE_NOT_FOUND','Issue not found.');return this.create(actor,{...input,sourceType:'OPERATIONS_ISSUE',sourceId:issue.id,operationsIssueId:issue.id,appointmentId:input.appointmentId??issue.relatedAppointmentId});}
 async processOverdue(secret:string|undefined){if(!process.env.TASK_WORKER_SECRET||secret!==process.env.TASK_WORKER_SECRET)throw taskError(401,'UNAUTHENTICATED','Unauthorized');const count=await this.db.transaction(async tx=>{const claimed=await tx.execute(sql`UPDATE tasks SET overdue_notified_at=now() WHERE id IN (SELECT id FROM tasks WHERE status IN ('OPEN','IN_PROGRESS') AND due_at < now() AND overdue_notified_at IS NULL ORDER BY due_at FOR UPDATE SKIP LOCKED LIMIT 100) RETURNING id,tenant_id,assigned_user_id,title`);const rows=((claimed as unknown as {rows?:any[]}).rows??[]) as any[];let notified=0;for(const row of rows){if(row.assigned_user_id){await tx.insert(internalNotifications).values(this.notifyValues(row.tenant_id,row.assigned_user_id,'TASK_OVERDUE','Task overdue',row.title,row.id));notified++;}}return notified;});return{processed:count};}
}
