import React, { useEffect, useMemo, useState } from 'react';
import { ExternalLink, MessageSquareText, RefreshCw, Send, Settings2, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router';
import { DEFAULT_REVIEW_INVITATION_MESSAGE } from '@ks-os/contracts';
import { getDataProvider } from '../../data/data-provider.js';

const provider = getDataProvider();

function ReputationNav() {
  return <div className="mb-5 flex flex-wrap gap-2 border-b border-slate-200 pb-3 text-sm font-bold">
    <Link className="rounded-lg px-3 py-2 hover:bg-white" to="/app/reputation">Overview</Link>
    <Link className="rounded-lg px-3 py-2 hover:bg-white" to="/app/reputation/reviews">External reviews</Link>
    <Link className="rounded-lg px-3 py-2 hover:bg-white" to="/app/reputation/invitations">Invitations</Link>
    <Link className="rounded-lg px-3 py-2 hover:bg-white" to="/app/settings/integrations/reviews">Connections & policy</Link>
  </div>;
}

function Page({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return <section className="mx-auto max-w-6xl">
    <div className="mb-5"><h1 className="text-2xl font-black text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-600">{subtitle}</p></div>
    <ReputationNav />{children}
  </section>;
}

const ProviderBadge = ({ name }: { name: string }) => <span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${name === 'GOOGLE' ? 'bg-blue-50 text-blue-700' : 'bg-emerald-50 text-emerald-700'}`}>{name === 'GOOGLE' ? 'Google' : 'Trustpilot'}</span>;

export function ReputationOverviewPage() {
  const [data, setData] = useState<any>(); const [error, setError] = useState('');
  useEffect(() => { provider.getReputationOverview().then(setData).catch((e) => setError(e.message)); }, []);
  const metrics = Object.fromEntries((data?.providerReviewMetrics ?? []).map((row: any) => [row.provider, row]));
  return <Page title="Reputation" subtitle="Monitor provider-hosted reviews. KS OS does not create a review score or host public reviews.">
    {error && <Notice tone="error">{error}</Notice>}
    <div className="grid gap-4 md:grid-cols-2">
      {['GOOGLE', 'TRUSTPILOT'].map((name) => <div key={name} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex items-center justify-between"><ProviderBadge name={name} /><span className="text-xs text-slate-500">Provider-attributed</span></div>
        <div className="mt-5 grid grid-cols-2 gap-4">
          <Metric label={name === 'GOOGLE' ? 'Google rating' : 'Trustpilot rating'} value={metrics[name]?.average_rating ?? '—'} />
          <Metric label="External review count" value={metrics[name]?.review_count ?? 0} />
        </div>
        <p className="mt-4 text-xs text-slate-500">{data?.connections?.some((connection: any) => connection.provider === name) ? 'A provider destination is configured.' : 'No provider destination configured.'}</p>
      </div>)}
    </div>
    <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>No combined score:</strong> Google and Trustpilot figures remain separate because the providers are authoritative.</div>
  </Page>;
}

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><div className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 text-2xl font-black text-slate-900">{value}</div></div>; }
function Notice({ children, tone = 'info' }: { children: React.ReactNode; tone?: 'info'|'error'|'success' }) { const cls = tone === 'error' ? 'border-red-200 bg-red-50 text-red-800' : tone === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-blue-200 bg-blue-50 text-blue-800'; return <div className={`mb-4 rounded-xl border p-3 text-sm ${cls}`}>{children}</div>; }

export function ReputationInvitationsPage() {
  const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState('');
  useEffect(() => { provider.listReviewInvitations().then(setRows).catch((e) => setError(e.message)); }, []);
  return <Page title="Review invitations" subtitle="Delivery and provider-click activity. A click is never counted as a submitted review.">
    {error && <Notice tone="error">{error}</Notice>}
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Provider</th><th className="p-3">Channel</th><th className="p-3">Status</th><th className="p-3">Scheduled</th><th className="p-3">Activity</th></tr></thead><tbody>
      {rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="p-3"><ProviderBadge name={row.provider} /></td><td className="p-3">{row.channel}</td><td className="p-3 font-bold">{row.status}</td><td className="p-3">{new Date(row.scheduledFor).toLocaleString()}</td><td className="p-3 text-xs text-slate-600">{row.googleClickedAt ? 'Google clicked ' : ''}{row.trustpilotClickedAt ? 'Trustpilot clicked' : ''}{!row.clickedAt ? 'No provider click recorded' : ''}</td></tr>)}
      {!rows.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">No invitations have been scheduled.</td></tr>}
    </tbody></table></div>
  </Page>;
}

export function ExternalReviewsPage() {
  const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState(''); const [replying, setReplying] = useState<string | null>(null); const [reply, setReply] = useState(''); const [privacy, setPrivacy] = useState(false);
  const load = () => provider.listExternalReviews().then(setRows).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, []);
  const saveReply = async (id: string) => { if (!privacy) return; try { await provider.saveExternalReviewReply(id, reply); setReplying(null); setReply(''); setPrivacy(false); await load(); } catch (e: any) { setError(e.message); } };
  return <Page title="External reviews" subtitle="Synchronized provider data is read-only in KS OS; public replies are sent back to the provider.">
    {error && <Notice tone="error">{error}</Notice>}
    <div className="space-y-3">{rows.map((row) => <article key={row.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-start justify-between gap-3"><div><ProviderBadge name={row.provider} /><div className="mt-2 font-black text-slate-900">{row.rating}/5 on {row.provider === 'GOOGLE' ? 'Google' : 'Trustpilot'}</div><div className="text-xs text-slate-500">{row.reviewerDisplayName || 'Provider user'} · {new Date(row.reviewCreatedAt).toLocaleDateString()}{row.verificationLevel ? ` · ${row.verificationLevel}` : ''}</div></div>{row.sourceUrl && <a className="flex items-center gap-1 text-sm font-bold text-indigo-700" href={row.sourceUrl} target="_blank" rel="noreferrer">Original <ExternalLink className="h-4 w-4" /></a>}</div>
      {row.title && <h2 className="mt-4 font-bold">{row.title}</h2>}<p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{row.reviewText || 'No written comment.'}</p>
      {row.businessReplyText && <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><strong>Public business reply:</strong> {row.businessReplyText}</div>}
      <div className="mt-4 flex gap-2"><button className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white" onClick={() => { setReplying(row.id); setReply(row.businessReplyText || ''); }}>Write or update public reply</button>{row.businessReplyText && <button className="rounded-lg border px-3 py-2 text-xs font-bold" onClick={async () => { if (window.confirm('Delete this public provider reply?')) { await provider.deleteExternalReviewReply(row.id); await load(); } }}>Delete reply</button>}</div>
      {replying === row.id && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-bold text-amber-950">Privacy reminder: this reply is public. Do not include contact details, appointment/treatment information, medical details, disputes, or internal notes.</p><textarea className="mt-3 min-h-28 w-full rounded-lg border border-slate-300 p-3 text-sm" maxLength={2000} value={reply} onChange={(e) => setReply(e.target.value)} /><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={privacy} onChange={(e) => setPrivacy(e.target.checked)} /> I have removed private information.</label><button disabled={!privacy || !reply.trim()} onClick={() => saveReply(row.id)} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Post public reply</button></div>}
    </article>)}{!rows.length && <div className="rounded-xl border border-dashed p-8 text-center text-slate-500">No provider reviews have been synchronized.</div>}</div>
  </Page>;
}

export function ReviewConnectionsPage() {
  const [connections, setConnections] = useState<any[]>([]); const [rules, setRules] = useState<any[]>([]); const [locations, setLocations] = useState<any[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [google, setGoogle] = useState({ businessDisplayName: '', reviewUrl: '', locationId: '' });
  const [trustpilot, setTrustpilot] = useState({ businessDisplayName: '', reviewUrl: '', locationId: '', profileDomain: '' });
  const [tpApi, setTpApi] = useState({ businessDisplayName: '', businessUnitId: '', providerLocationId: '', profileDomain: '', locale: 'en-GB', invitationTemplateId: '', apiKey: '', accessToken: '', authorBusinessUserId: '' });
  const [rule, setRule] = useState({ name: 'After-visit review invitation', providerMode: 'BOTH', channel: 'EMAIL', delayMinutes: 1440, locationId: '', messageTemplate: DEFAULT_REVIEW_INVITATION_MESSAGE, privateContactEnabled: true });
  const load = async () => { const [c, r, l] = await Promise.all([provider.listReviewConnections(), provider.listReviewInvitationRules(), provider.listReviewLocations()]); setConnections(c); setRules(r); setLocations(l); };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const act = async (fn: () => Promise<any>, success: string) => { setError(''); try { await fn(); setMessage(success); await load(); } catch (e: any) { setError(e.message); } };
  const locationSelect = (value: string, set: (value: string) => void) => <select className="w-full rounded-lg border p-2.5 text-sm" value={value} onChange={(e) => set(e.target.value)}><option value="">Tenant-wide fallback</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}{location.isPrimary ? ' (primary)' : ''}</option>)}</select>;
  return <Page title="Review connections & policy" subtitle="Configure genuine provider destinations and one consistent neutral invitation policy.">
    {message && <Notice tone="success">{message}</Notice>}{error && <Notice tone="error">{error}</Notice>}
    <div className="mb-6 grid gap-4 lg:grid-cols-2">
      <form className="rounded-xl border bg-white p-5" onSubmit={(e) => { e.preventDefault(); act(() => provider.configureGoogleReviewLink({ ...google, locationId: google.locationId || null }), 'Google review link configured.'); }}><h2 className="font-black">Google review link</h2><p className="mb-4 mt-1 text-xs text-slate-500">Manual links do not prove Business Profile ownership and do not require API approval.</p><Field label="Business display name" value={google.businessDisplayName} onChange={(businessDisplayName) => setGoogle({ ...google, businessDisplayName })} /><Field label="Verified Google review-request URL" value={google.reviewUrl} onChange={(reviewUrl) => setGoogle({ ...google, reviewUrl })} />{locationSelect(google.locationId, (locationId) => setGoogle({ ...google, locationId }))}<button className="mt-4 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">Save Google link</button></form>
      <form className="rounded-xl border bg-white p-5" onSubmit={(e) => { e.preventDefault(); act(() => provider.configureTrustpilot({ ...trustpilot, connectionType: 'MANUAL_LINK', locationId: trustpilot.locationId || null, locale: 'en-GB' }), 'Trustpilot review link configured.'); }}><h2 className="font-black">Trustpilot review link</h2><p className="mb-4 mt-1 text-xs text-slate-500">Limited fallback using a validated Trustpilot profile or evaluation URL.</p><Field label="Business display name" value={trustpilot.businessDisplayName} onChange={(businessDisplayName) => setTrustpilot({ ...trustpilot, businessDisplayName })} /><Field label="Trustpilot profile or evaluation URL" value={trustpilot.reviewUrl} onChange={(reviewUrl) => setTrustpilot({ ...trustpilot, reviewUrl })} />{locationSelect(trustpilot.locationId, (locationId) => setTrustpilot({ ...trustpilot, locationId }))}<button className="mt-4 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Save Trustpilot link</button></form>
    </div>
    <div className="mb-6 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Optional provider APIs</h2><p className="text-xs text-slate-500">OAuth/API features require provider approval. Secrets are encrypted server-side and never returned.</p></div><button className="rounded-lg border px-4 py-2 text-sm font-bold" onClick={() => act(async () => { const result = await provider.startGoogleReviewOauth(); window.location.assign(result.authorizationUrl); }, 'Opening Google authorisation…')}>Connect Google Business Profile</button></div><form className="mt-5 border-t pt-5" onSubmit={(e) => { e.preventDefault(); act(() => provider.configureTrustpilot({ connectionType: 'API', businessDisplayName: tpApi.businessDisplayName, businessUnitId: tpApi.businessUnitId, providerLocationId: tpApi.providerLocationId || null, profileDomain: tpApi.profileDomain || null, locale: tpApi.locale, invitationTemplateId: tpApi.invitationTemplateId || null, apiCredentials: { apiKey: tpApi.apiKey, accessToken: tpApi.accessToken, authorBusinessUserId: tpApi.authorBusinessUserId || undefined } }), 'Trustpilot API connection saved.'); }}><h3 className="text-sm font-black">Trustpilot API connection</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Business display name" value={tpApi.businessDisplayName} onChange={(value) => setTpApi({ ...tpApi, businessDisplayName: value })} /><Field label="Business unit ID" value={tpApi.businessUnitId} onChange={(value) => setTpApi({ ...tpApi, businessUnitId: value })} /><Field label="Profile domain" value={tpApi.profileDomain} onChange={(value) => setTpApi({ ...tpApi, profileDomain: value })} /><Field label="Trustpilot location ID (optional)" value={tpApi.providerLocationId} onChange={(value) => setTpApi({ ...tpApi, providerLocationId: value })} /><Field label="Invitation template ID (optional)" value={tpApi.invitationTemplateId} onChange={(value) => setTpApi({ ...tpApi, invitationTemplateId: value })} /><Field label="Reply business-user ID (optional)" value={tpApi.authorBusinessUserId} onChange={(value) => setTpApi({ ...tpApi, authorBusinessUserId: value })} /><Field label="API key" value={tpApi.apiKey} onChange={(value) => setTpApi({ ...tpApi, apiKey: value })} /><Field label="OAuth access token" value={tpApi.accessToken} onChange={(value) => setTpApi({ ...tpApi, accessToken: value })} /></div><button className="mt-2 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Save encrypted Trustpilot API connection</button></form></div>
    <div className="mb-6 rounded-xl border bg-white p-5"><h2 className="font-black">Configured destinations</h2><div className="mt-3 space-y-2">{connections.map((connection) => <div key={connection.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 p-3"><div><ProviderBadge name={connection.provider} /> <span className="ml-2 text-sm font-bold">{connection.label}</span><div className="mt-1 text-xs text-slate-500">{connection.businessDisplayName} · {connection.locationId ? 'Location-specific' : 'Tenant-wide fallback'} · {connection.status}</div></div><div className="flex gap-2">{connection.reviewUrl && <button className="rounded-lg border px-3 py-1.5 text-xs font-bold" onClick={() => act(() => provider.testReviewConnection(connection.id), 'Provider link verified.')}>Test link</button>}<button className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-bold text-red-700" onClick={() => window.confirm('Disconnect this review destination?') && act(() => provider.deleteReviewConnection(connection.id), 'Connection removed.')}>Disconnect</button></div></div>)}{!connections.length && <p className="text-sm text-slate-500">No provider destinations configured.</p>}</div></div>
    <form className="rounded-xl border bg-white p-5" onSubmit={(e) => { e.preventDefault(); act(() => provider.createReviewInvitationRule({ ...rule, locationId: rule.locationId || null }), 'Neutral invitation policy activated.'); }}><h2 className="font-black">Neutral invitation policy</h2><p className="mb-4 mt-1 text-xs text-slate-500">Applies automatically to every eligible completed appointment. Staff cannot choose recipients.</p><div className="grid gap-3 md:grid-cols-2"><Field label="Policy name" value={rule.name} onChange={(name) => setRule({ ...rule, name })} /><label className="text-sm font-bold">Providers<select className="mt-1 w-full rounded-lg border p-2.5 font-normal" value={rule.providerMode} onChange={(e) => setRule({ ...rule, providerMode: e.target.value })}><option value="GOOGLE">Google</option><option value="TRUSTPILOT">Trustpilot</option><option value="BOTH">Both equally</option></select></label><label className="text-sm font-bold">Channel<select className="mt-1 w-full rounded-lg border p-2.5 font-normal" value={rule.channel} onChange={(e) => setRule({ ...rule, channel: e.target.value })}><option value="EMAIL">Email</option><option value="SMS">SMS (marketing opt-in required)</option><option value="CUSTOMER_PORTAL">Customer portal</option></select></label><label className="text-sm font-bold">Delay<select className="mt-1 w-full rounded-lg border p-2.5 font-normal" value={rule.delayMinutes} onChange={(e) => setRule({ ...rule, delayMinutes: Number(e.target.value) })}>{[[0,'Immediately'],[120,'2 hours'],[360,'6 hours'],[1440,'24 hours'],[2880,'2 days'],[4320,'3 days'],[10080,'7 days']].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>{locationSelect(rule.locationId, (locationId) => setRule({ ...rule, locationId }))}</div><label className="mt-4 block text-sm font-bold">Neutral wording<textarea className="mt-1 min-h-28 w-full rounded-lg border p-3 font-normal" maxLength={800} value={rule.messageTemplate} onChange={(e) => setRule({ ...rule, messageTemplate: e.target.value })} /></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={rule.privateContactEnabled} onChange={(e) => setRule({ ...rule, privateContactEnabled: e.target.checked })} /> Show the same private contact option to everyone.</label><button className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Activate policy</button></form>
    <div className="mt-4 space-y-2">{rules.map((existing) => <div key={existing.id} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><strong>{existing.name}</strong><div className="text-xs text-slate-500">{existing.providerMode} · {existing.channel} · {existing.delayMinutes} minutes · v{existing.ruleVersion}</div></div><button className="rounded-lg border px-3 py-2 text-xs font-bold" onClick={() => act(() => provider.reviewInvitationRuleCommand(existing.id, existing.status === 'ACTIVE' ? 'pause' : 'resume'), existing.status === 'ACTIVE' ? 'Policy paused.' : 'Policy resumed.')}>{existing.status === 'ACTIVE' ? 'Pause' : 'Resume'}</button></div>)}</div>
  </Page>;
}

function Field({ label, value, onChange, type = 'text', required = !/\(optional\)/i.test(label) }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { const inputType = type === 'password' || /api key|access token/i.test(label) ? 'password' : type; return <label className="mb-3 block text-sm font-bold">{label}<input type={inputType} required={required} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" value={value} onChange={(e) => onChange(e.target.value)} autoComplete={inputType === 'password' ? 'off' : undefined} /></label>; }

export function PublicReviewInvitationPage() {
  const { token = '' } = useParams(); const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  useEffect(() => { fetch('/api/v1/public/review-invitations/' + encodeURIComponent(token)).then(async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok || !body.data) throw new Error(body.error?.message || 'This invitation is unavailable.'); setData(body.data); }).catch((e) => setError(e.message || 'This invitation is unavailable.')); }, [token]);
  const choose = async (name: string) => { setBusy(name); try { const response = await fetch('/api/v1/public/review-invitations/' + encodeURIComponent(token) + '/click', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ provider: name }) }); const body = await response.json().catch(() => ({})); if (!response.ok || !body.data?.redirectUrl) throw new Error(body.error?.message || 'The provider is unavailable.'); window.location.assign(body.data.redirectUrl); } catch (e: any) { setError(e.message || 'The provider is unavailable.'); setBusy(''); } };
  if (error) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><div className="max-w-md rounded-2xl border bg-white p-8 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-slate-400" /><h1 className="mt-4 text-xl font-black">Review invitation unavailable</h1><p className="mt-2 text-sm text-slate-600">{error}</p></div></main>;
  if (!data) return <main className="flex min-h-screen items-center justify-center bg-slate-50 text-sm font-bold text-slate-500">Loading secure invitation…</main>;
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-5"><section className="w-full max-w-2xl rounded-3xl border border-slate-200 bg-white p-7 shadow-xl md:p-10"><div className="text-center"><MessageSquareText className="mx-auto h-10 w-10 text-indigo-600" /><h1 className="mt-3 text-2xl font-black text-slate-900">Share honest feedback about {data.salonName}</h1><p className="mt-2 text-sm text-slate-500">Visit on {new Date(data.appointmentDate).toLocaleDateString()}</p><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-slate-700">{data.message}</p></div><div className={`mt-7 grid gap-3 ${data.providers.length === 2 ? 'sm:grid-cols-2' : ''}`}>{data.providers.map((item: any) => <button key={item.provider} disabled={Boolean(busy)} onClick={() => choose(item.provider)} className="flex min-h-14 items-center justify-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white shadow-sm transition hover:bg-indigo-700 disabled:opacity-50">{busy === item.provider ? 'Opening…' : item.label}<ExternalLink className="h-4 w-4" /></button>)}</div>{data.privateContactUrl && <div className="mt-6 border-t pt-5 text-center"><a className="text-sm font-bold text-slate-700 underline" href={data.privateContactUrl}>Contact the salon privately</a><p className="mt-1 text-xs text-slate-500">This is not a public review and does not replace either provider option.</p></div>}<p className="mt-6 text-center text-xs text-slate-500">There is no obligation to leave a review. Your review is created and hosted by the provider you choose, not KS OS.</p></section></main>;
}
