import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowLeft, BarChart3, ChevronLeft, ChevronRight, FileText, RefreshCw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { getDataProvider } from '../../data/data-provider.js';

type Option={value:string;label:string};
type Column={key:string;label:string;kind?:'money'|'date'|'percent'|'reference';link?:(row:any)=>string|null};
type Summary={key:string;label:string;kind?:'money'|'percent'};
type Config={slug:string;title:string;description:string;method:string;period?:boolean;sorts:Option[];filters?:Array<{key:string;label:string;options:Option[]}>;summaries:Summary[];columns:Column[]};

const status=(values:string[]):Option[]=>values.map(value=>({value,label:value.replaceAll('_',' ').toLowerCase().replace(/^./,x=>x.toUpperCase())}));
const appointmentLink=(row:any)=>row.appointmentId?`/app/calendar?appointmentId=${encodeURIComponent(row.appointmentId)}`:null;
const clientLink=(row:any)=>row.clientId?`/app/clients/${encodeURIComponent(row.clientId)}`:null;
const paymentLink=(row:any)=>row.transactionId?`/app/payments/${encodeURIComponent(row.transactionId)}`:null;
const formLink=(row:any)=>row.formId?`/app/forms/${encodeURIComponent(row.formId)}`:null;

export const REPORT_CONFIGS:Config[]=[
  {slug:'appointments',title:'Appointments report',description:'The appointments behind booking and quoted-value summaries.',method:'getAppointmentsReport',period:true,sorts:[{value:'date_desc',label:'Newest appointment'},{value:'date_asc',label:'Oldest appointment'},{value:'created_desc',label:'Recently created'},{value:'amount_desc',label:'Highest quoted amount'}],filters:[{key:'status',label:'Status',options:status(['PENDING','CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED','CANCELLED','NO_SHOW'])},{key:'bookingChannel',label:'Booking channel',options:[{value:'in_shop',label:'In shop'},{value:'mobile',label:'Mobile'}]}],summaries:[{key:'total',label:'Appointments'},{key:'completed',label:'Completed'},{key:'cancelled',label:'Cancelled'},{key:'noShow',label:'No-show'},{key:'awaitingPayment',label:'Awaiting payment'},{key:'quotedAmountTotal',label:'Quoted total',kind:'money'}],columns:[{key:'publicReference',label:'Reference',kind:'reference',link:appointmentLink},{key:'startTime',label:'Date',kind:'date'},{key:'clientDisplayName',label:'Client'},{key:'serviceName',label:'Service'},{key:'staffName',label:'Staff'},{key:'status',label:'Status'},{key:'bookingChannel',label:'Channel'},{key:'quotedAmount',label:'Quoted',kind:'money'},{key:'paymentState',label:'Payment'}]},
  {slug:'clients',title:'Clients report',description:'Client activity classified with the Phase 8.1 new and returning definition.',method:'getClientsReport',period:true,sorts:[{value:'last_visit_desc',label:'Latest appointment'},{value:'name_asc',label:'Name'},{value:'spend_desc',label:'Highest recorded spend'},{value:'appointments_desc',label:'Most appointments'}],filters:[{key:'newOrReturning',label:'Client type',options:[{value:'NEW',label:'New'},{value:'RETURNING',label:'Returning'}]},{key:'lastVisitRange',label:'Last completed visit',options:[{value:'LAST_30_DAYS',label:'Last 30 days'},{value:'LAST_90_DAYS',label:'Last 90 days'},{value:'OVER_90_DAYS',label:'Over 90 days'},{value:'NEVER',label:'Never completed'}]}],summaries:[{key:'totalClients',label:'Clients'},{key:'newClients',label:'New'},{key:'returningClients',label:'Returning'},{key:'recordedSpend',label:'Recorded spend',kind:'money'}],columns:[{key:'name',label:'Client',link:clientLink},{key:'clientType',label:'Type'},{key:'firstAppointmentAt',label:'First appointment',kind:'date'},{key:'lastAppointmentAt',label:'Last appointment',kind:'date'},{key:'completedAppointmentCount',label:'Completed'},{key:'cancelledCount',label:'Cancelled'},{key:'noShowCount',label:'No-show'},{key:'recordedSpend',label:'Recorded spend',kind:'money'},{key:'futureAppointmentCount',label:'Future'}]},
  {slug:'services',title:'Services report',description:'Booking activity and recorded transaction attribution by service.',method:'getServicesReport',period:true,sorts:[{value:'bookings_desc',label:'Most bookings'},{value:'revenue_desc',label:'Highest recorded revenue'},{value:'completed_desc',label:'Most completed'},{value:'name_asc',label:'Name'}],summaries:[{key:'totalServices',label:'Services'},{key:'bookings',label:'Bookings'},{key:'completed',label:'Completed'},{key:'recordedRevenue',label:'Recorded revenue',kind:'money'}],columns:[{key:'serviceName',label:'Service'},{key:'bookings',label:'Bookings'},{key:'completed',label:'Completed'},{key:'cancelled',label:'Cancelled'},{key:'noShows',label:'No-show'},{key:'recordedRevenue',label:'Recorded revenue',kind:'money'},{key:'averageRecordedTransaction',label:'Average transaction',kind:'money'},{key:'uniqueClients',label:'Unique clients'},{key:'rebookingIndicator',label:'Rebooking',kind:'percent'}]},
  {slug:'staff',title:'Staff activity report',description:'Scheduled capacity, booked work and recorded revenue—not staff earnings.',method:'getStaffReport',period:true,sorts:[{value:'booked_desc',label:'Most booked minutes'},{value:'utilisation_desc',label:'Highest utilisation'},{value:'revenue_desc',label:'Highest recorded revenue'},{value:'name_asc',label:'Name'}],filters:[{key:'accountStatus',label:'Account status',options:status(['ACTIVE','SUSPENDED','DEACTIVATED'])}],summaries:[{key:'totalStaff',label:'Staff'},{key:'scheduledMinutes',label:'Scheduled minutes'},{key:'bookedMinutes',label:'Booked minutes'},{key:'completedAppointments',label:'Completed'},{key:'recordedRevenue',label:'Recorded revenue',kind:'money'}],columns:[{key:'staffName',label:'Staff',link:r=>r.staffId?`/app/settings/team/${encodeURIComponent(r.staffId)}`:null},{key:'accountStatus',label:'Account status'},{key:'scheduledMinutes',label:'Scheduled minutes'},{key:'bookedMinutes',label:'Booked minutes'},{key:'utilisationPercentage',label:'Utilisation',kind:'percent'},{key:'completedAppointments',label:'Completed'},{key:'cancelledAppointments',label:'Cancelled'},{key:'noShows',label:'No-show'},{key:'uniqueClients',label:'Unique clients'},{key:'recordedRevenue',label:'Recorded revenue',kind:'money'}]},
  {slug:'products',title:'Product sales report',description:'Sales-derived quantities from checkout product arrays; this is not a stock ledger.',method:'getProductsReport',period:true,sorts:[{value:'quantity_desc',label:'Most units sold'},{value:'name_asc',label:'Name'},{value:'stock_asc',label:'Lowest stock'}],summaries:[{key:'totalProducts',label:'Products'},{key:'productsSold',label:'Products sold'},{key:'quantitySold',label:'Units sold'},{key:'grossRecordedSales',label:'Gross sales',kind:'money'}],columns:[{key:'name',label:'Product'},{key:'sku',label:'SKU'},{key:'quantitySold',label:'Quantity sold'},{key:'grossRecordedSales',label:'Gross recorded sales',kind:'money'},{key:'transactionCount',label:'Transactions'},{key:'currentStock',label:'Current stock'},{key:'lastSaleAt',label:'Last sale',kind:'date'}]},
  {slug:'stock',title:'Current stock report',description:'Current quantities with a fixed low-stock indicator of one to five units.',method:'getStockReport',sorts:[{value:'quantity_asc',label:'Lowest quantity'},{value:'quantity_desc',label:'Highest quantity'},{value:'name_asc',label:'Name'},{value:'last_sale_desc',label:'Latest sale'}],filters:[{key:'status',label:'Stock status',options:[{value:'IN_STOCK',label:'In stock (>5)'},{value:'LOW_STOCK',label:'Low stock (1–5)'},{value:'OUT_OF_STOCK',label:'Out of stock'}]}],summaries:[{key:'totalProducts',label:'Products'},{key:'inStock',label:'In stock'},{key:'lowStock',label:'Low stock'},{key:'outOfStock',label:'Out of stock'}],columns:[{key:'name',label:'Product'},{key:'sku',label:'SKU'},{key:'currentQuantity',label:'Current quantity'},{key:'lowStock',label:'Low stock'},{key:'outOfStock',label:'Out of stock'},{key:'lastSaleAt',label:'Last sale',kind:'date'}]},
  {slug:'payments',title:'Payment transactions report',description:'Recorded transactions split by source, method, status and refunds.',method:'getPaymentsReport',period:true,sorts:[{value:'date_desc',label:'Newest transaction'},{value:'date_asc',label:'Oldest transaction'},{value:'amount_desc',label:'Highest gross amount'},{value:'net_desc',label:'Highest net amount'}],filters:[{key:'source',label:'Source',options:status(['STRIPE_ONLINE','MANUAL_CASH','EXTERNAL_TERMINAL','MANUAL_SPLIT'])},{key:'status',label:'Status',options:status(['PENDING','SUCCEEDED','PARTIALLY_REFUNDED','REFUNDED','FAILED'])}],summaries:[{key:'totalTransactions',label:'Transactions'},{key:'succeeded',label:'Successful history'},{key:'failed',label:'Failed'},{key:'grossAmount',label:'Gross',kind:'money'},{key:'refundedAmount',label:'Refunded',kind:'money'},{key:'netAmount',label:'Net recorded',kind:'money'}],columns:[{key:'date',label:'Date',kind:'date'},{key:'bookingReference',label:'Booking',kind:'reference',link:appointmentLink},{key:'clientDisplayName',label:'Client'},{key:'serviceName',label:'Service'},{key:'source',label:'Source'},{key:'method',label:'Method'},{key:'grossAmount',label:'Gross',kind:'money'},{key:'refundedAmount',label:'Refunded',kind:'money'},{key:'netAmount',label:'Net',kind:'money'},{key:'status',label:'Status',link:paymentLink}]},
  {slug:'refunds',title:'Refunds report',description:'KS OS and Stripe Dashboard refund records without internal notes or provider identifiers.',method:'getRefundsReport',period:true,sorts:[{value:'requested_desc',label:'Newest request'},{value:'completed_desc',label:'Recently completed'},{value:'amount_desc',label:'Highest amount'}],filters:[{key:'status',label:'Status',options:status(['CREATING','PENDING','SUCCEEDED','FAILED','CANCELLED'])},{key:'source',label:'Source',options:[{value:'KS_OS',label:'KS OS'},{value:'STRIPE_DASHBOARD',label:'Stripe Dashboard'}]}],summaries:[{key:'totalRefunds',label:'Refunds'},{key:'requestedAmount',label:'Requested',kind:'money'},{key:'completedAmount',label:'Completed',kind:'money'},{key:'failed',label:'Failed'}],columns:[{key:'dateRequested',label:'Requested',kind:'date'},{key:'dateCompleted',label:'Completed',kind:'date'},{key:'bookingReference',label:'Booking',kind:'reference'},{key:'amount',label:'Amount',kind:'money'},{key:'status',label:'Status'},{key:'reason',label:'Reason'},{key:'source',label:'Source'},{key:'requestedBy',label:'Requested by',link:paymentLink}]},
  {slug:'forms',title:'Forms report',description:'Assignment and completion status without answers, acknowledgement names or public tokens.',method:'getFormsReport',period:true,sorts:[{value:'assigned_desc',label:'Recently assigned'},{value:'appointment_desc',label:'Appointment reference'},{value:'submitted_desc',label:'Recently submitted'},{value:'title_asc',label:'Title'}],filters:[{key:'status',label:'Status',options:status(['PENDING','OPENED','SUBMITTED','EXPIRED','CANCELLED'])}],summaries:[{key:'assigned',label:'Assigned'},{key:'opened',label:'Opened'},{key:'submitted',label:'Submitted'},{key:'expired',label:'Expired'},{key:'cancelled',label:'Cancelled'},{key:'completionRate',label:'Completion rate',kind:'percent'}],columns:[{key:'formTitle',label:'Form',link:formLink},{key:'formVersion',label:'Version'},{key:'clientDisplayName',label:'Client'},{key:'appointmentReference',label:'Appointment',kind:'reference',link:appointmentLink},{key:'assignedAt',label:'Assigned',kind:'date'},{key:'openedAt',label:'Opened',kind:'date'},{key:'submittedAt',label:'Submitted',kind:'date'},{key:'status',label:'Status'},{key:'assignedBy',label:'Assigned by'}]},
  {slug:'communications',title:'Communications report',description:'Masked email and SMS delivery history without bodies, links, tokens or provider payloads.',method:'getCommunicationsReport',period:true,sorts:[{value:'queued_desc',label:'Newest queued'},{value:'queued_asc',label:'Oldest queued'},{value:'status_asc',label:'Status'}],filters:[{key:'channel',label:'Channel',options:[{value:'EMAIL',label:'Email'},{value:'SMS',label:'SMS'}]},{key:'status',label:'Status',options:status(['PENDING','PROCESSING','ACCEPTED','QUEUED','SENT','DELIVERED','FAILED','UNDELIVERED','BOUNCED','COMPLAINED','SUPPRESSED','EXPIRED','CANCELLED'])}],summaries:[{key:'total',label:'Communications'},{key:'email',label:'Email'},{key:'sms',label:'SMS'},{key:'delivered',label:'Delivered'},{key:'failed',label:'Failed'},{key:'segments',label:'SMS segments'}],columns:[{key:'channel',label:'Channel'},{key:'category',label:'Template/category'},{key:'maskedRecipient',label:'Recipient'},{key:'relatedType',label:'Related record'},{key:'queuedAt',label:'Queued',kind:'date'},{key:'sentAt',label:'Sent',kind:'date'},{key:'deliveredAt',label:'Delivered',kind:'date'},{key:'status',label:'Status'},{key:'segmentCount',label:'Segments'},{key:'failureCategory',label:'Failure category'}]},
];

const presets:Option[]=[{value:'TODAY',label:'Today'},{value:'LAST_7_DAYS',label:'Last 7 days'},{value:'LAST_30_DAYS',label:'Last 30 days'},{value:'THIS_MONTH',label:'This month'},{value:'LAST_MONTH',label:'Last month'},{value:'CUSTOM',label:'Custom'}];

function valueLabel(value:any,column:Column,currency:string){
  if(value===null||value===undefined)return 'Unavailable';
  if(typeof value==='boolean')return value?'Yes':'No';
  if(column.kind==='money')return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(value)/100);
  if(column.kind==='percent')return `${Number(value).toFixed(1)}%`;
  if(column.kind==='date')return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
  if(column.kind==='reference')return String(value).slice(0,8);
  return String(value).replaceAll('_',' ');
}

function SummaryCard({item,value,currency}:{item:Summary;value:any;currency:string}){const column:Column={key:item.key,label:item.label,kind:item.kind};return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{item.label}</p><p className="mt-2 text-2xl font-black text-slate-900">{valueLabel(value,column,currency)}</p></div>}

export function ReportsHome(){return <section className="space-y-6" aria-labelledby="reports-title"><div><h1 id="reports-title" className="text-2xl font-black text-slate-950">Operational reports</h1><p className="mt-1 text-sm text-slate-600">Inspect the records behind dashboard summaries. Reports are read-only and tenant-scoped.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{REPORT_CONFIGS.map(report=><Link key={report.slug} to={`/app/reports/${report.slug}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-indigo-300 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-indigo-500"><div className="flex items-start gap-3"><div className="rounded-xl bg-indigo-50 p-2 text-indigo-700"><FileText className="h-5 w-5"/></div><div><h2 className="font-black text-slate-900">{report.title}</h2><p className="mt-1 text-sm text-slate-600">{report.description}</p></div></div></Link>)}</div></section>}

export function ReportPage(){
  const {reportKey}=useParams();const config=useMemo(()=>REPORT_CONFIGS.find(item=>item.slug===reportKey),[reportKey]);
  const [period,setPeriod]=useState('LAST_30_DAYS');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [search,setSearch]=useState('');const [sort,setSort]=useState('');const [filters,setFilters]=useState<Record<string,string>>({});const [cursorHistory,setCursorHistory]=useState<string[]>([]);const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
  useEffect(()=>{if(config){setSort(config.sorts[0].value);setFilters({});setCursorHistory([]);}},[config]);
  const resetPage=()=>setCursorHistory([]);
  const load=useCallback(async()=>{if(!config||!sort)return;if(config.period&&period==='CUSTOM'&&(!from||!to)){setData(null);setError('');setLoading(false);return;}setLoading(true);setError('');try{const query:any={limit:25,sort,...filters};if(config.period){query.period=period;if(period==='CUSTOM'){query.from=from;query.to=to;}}if(config.slug!=='communications'&&search.trim())query.search=search.trim();const cursor=cursorHistory.at(-1);if(cursor)query.cursor=cursor;const provider:any=getDataProvider();setData(await provider[config.method](query));}catch(e:any){setData(null);setError(e?.message||'The report could not be loaded.');}finally{setLoading(false);}},[config,sort,filters,period,from,to,search,cursorHistory,retry]);
  useEffect(()=>{void load();},[load]);
  if(!config)return <div className="rounded-xl border border-slate-200 bg-white p-8"><h1 className="font-black">Report not found</h1><Link className="mt-3 inline-block text-indigo-700 underline" to="/app/reports">Return to reports</Link></div>;
  const currency=data?.currency||'GBP';
  const exportType=(config.slug==='staff'?'STAFF_ACTIVITY':config.slug.toUpperCase()) as string;
  return <section className="space-y-5" aria-labelledby="report-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/app/reports" className="mb-2 inline-flex items-center gap-1 text-sm font-bold text-indigo-700"><ArrowLeft className="h-4 w-4"/>All reports</Link><h1 id="report-title" className="text-2xl font-black text-slate-950">{config.title}</h1><p className="mt-1 max-w-3xl text-sm text-slate-600">{config.description}</p></div><div className="flex gap-2"><Link to={`/app/reports/exports?reportType=${exportType}`} className="rounded-lg bg-indigo-700 px-3 py-2 text-xs font-bold text-white">Export CSV</Link><Link to={`/app/reports/schedules?reportType=${exportType}`} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">Schedule report</Link></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
      {config.period&&<label className="text-xs font-bold text-slate-600">Period<select aria-label="Report period" value={period} onChange={e=>{setPeriod(e.target.value);resetPage();}} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{presets.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
      {config.period&&period==='CUSTOM'&&<><label className="text-xs font-bold text-slate-600">From<input aria-label="From date" type="date" value={from} onChange={e=>{setFrom(e.target.value);resetPage();}} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"/></label><label className="text-xs font-bold text-slate-600">To<input aria-label="To date" type="date" value={to} onChange={e=>{setTo(e.target.value);resetPage();}} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"/></label></>}
      {config.slug!=='communications'&&<label className="text-xs font-bold text-slate-600">Search<input aria-label="Search report" value={search} onChange={e=>{setSearch(e.target.value);resetPage();}} placeholder="Name or reference" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"/></label>}
      {config.filters?.map(filter=><label key={filter.key} className="text-xs font-bold text-slate-600">{filter.label}<select aria-label={filter.label} value={filters[filter.key]||''} onChange={e=>{setFilters(current=>({...current,[filter.key]:e.target.value}));resetPage();}} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All</option>{filter.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}
      <label className="text-xs font-bold text-slate-600">Sort<select aria-label="Report sort" value={sort} onChange={e=>{setSort(e.target.value);resetPage();}} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{config.sorts.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>
    </div></div>
    {config.period&&period==='CUSTOM'&&(!from||!to)&&<div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 text-sm font-bold text-indigo-900">Choose both custom dates to load this report.</div>}
    {loading&&<div role="status" aria-live="polite" className="space-y-4"><span className="sr-only">Loading report</span><div className="grid gap-3 sm:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-24 animate-pulse rounded-xl bg-slate-200"/>)}</div><div className="h-72 animate-pulse rounded-xl bg-slate-200"/></div>}
    {!loading&&error&&<div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-900"><div className="flex items-start gap-3"><AlertCircle className="mt-0.5 h-5 w-5"/><div><h2 className="font-black">Report unavailable</h2><p className="mt-1 text-sm">{error}</p><button onClick={()=>setRetry(value=>value+1)} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-rose-900 px-3 py-2 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Retry</button></div></div></div>}
    {!loading&&!error&&data&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{config.summaries.map(item=><SummaryCard key={item.key} item={item} value={data.summary?.[item.key]} currency={currency}/>)}</div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div className="flex items-center gap-2"><BarChart3 className="h-4 w-4 text-indigo-700"/><h2 className="font-black text-slate-900">Detailed records</h2></div><span className="text-xs font-bold text-slate-500">Page {cursorHistory.length+1}</span></div>{data.rows.length===0?<div className="p-10 text-center"><h3 className="font-black text-slate-800">No matching records</h3><p className="mt-1 text-sm text-slate-500">No live records match the selected period and filters.</p></div>:<div className="overflow-x-auto"><table className="min-w-full border-collapse text-left text-sm"><caption className="sr-only">{config.title} detailed records</caption><thead className="bg-slate-50"><tr>{config.columns.map(column=><th key={column.key} scope="col" className="whitespace-nowrap border-b border-slate-200 px-4 py-3 text-xs font-black uppercase tracking-wide text-slate-500">{column.label}</th>)}</tr></thead><tbody>{data.rows.map((row:any,index:number)=><tr key={row.appointmentId||row.clientId||row.serviceId||row.staffId||row.productId||row.transactionId||row.refundId||row.assignmentId||row.communicationId||index} className="border-b border-slate-100 last:border-0 hover:bg-slate-50">{config.columns.map(column=>{const display=valueLabel(row[column.key],column,currency);const href=column.link?.(row);return <td key={column.key} className="max-w-xs whitespace-nowrap px-4 py-3 text-slate-700">{href?<Link className="font-bold text-indigo-700 hover:underline" to={href}>{display}</Link>:display}</td>})}</tr>)}</tbody></table></div>}<div className="flex items-center justify-between border-t border-slate-200 px-4 py-3"><button disabled={!cursorHistory.length} onClick={()=>setCursorHistory(history=>history.slice(0,-1))} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40"><ChevronLeft className="h-4 w-4"/>Previous</button><button disabled={!data.pagination?.nextCursor} onClick={()=>setCursorHistory(history=>[...history,data.pagination.nextCursor])} className="inline-flex items-center gap-1 rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40">Next<ChevronRight className="h-4 w-4"/></button></div></div></>}
  </section>;
}
