import React from 'react';
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter} from 'react-router';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {ReportExportsPage,ReportSchedulesPage} from './ReportOperations.js';
import {AdvancedAnalyticsPage} from '../analytics/AdvancedAnalyticsPage.js';

const provider={listReportExports:vi.fn(),createReportExport:vi.fn(),downloadReportExport:vi.fn(),cancelReportExport:vi.fn(),listReportSchedules:vi.fn(),listTeam:vi.fn(),createReportSchedule:vi.fn(),reportScheduleCommand:vi.fn(),getAdvancedAnalytics:vi.fn()};
vi.mock('../../data/data-provider.js',()=>({getDataProvider:()=>provider}));
const exportRow={id:'11111111-1111-1111-1111-111111111111',reportType:'APPOINTMENTS',status:'READY',requestedByName:'Owner',rowCount:3,requestedAt:'2026-07-19T10:00:00.000Z',expiresAt:'2026-07-22T10:00:00.000Z'};

describe('Report operations',()=>{beforeEach(()=>{vi.clearAllMocks();provider.listReportExports.mockResolvedValue({data:[exportRow]});provider.createReportExport.mockResolvedValue({});provider.downloadReportExport.mockResolvedValue({url:'#secure-download'});provider.listReportSchedules.mockResolvedValue({data:[{id:'22222222-2222-2222-2222-222222222222',name:'Weekly operations',reportType:'APPOINTMENTS',frequency:'WEEKLY',deliveryTimeLocal:'09:00',timezone:'Europe/London',recipientUserIds:[],additionalRecipientsMasked:['o***@example.com'],status:'ACTIVE',nextRunAt:'2026-07-20T08:00:00.000Z',lastRunAt:null}]});provider.listTeam.mockResolvedValue({members:[]});provider.reportScheduleCommand.mockResolvedValue(undefined);});
  it('queues an asynchronous CSV export and shows secure history',async()=>{render(<MemoryRouter><ReportExportsPage/></MemoryRouter>);expect(await screen.findByText('Owner')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Export CSV'}));await waitFor(()=>expect(provider.createReportExport).toHaveBeenCalledWith(expect.objectContaining({reportType:'APPOINTMENTS',format:'CSV'})));expect(screen.getByRole('button',{name:'Download'})).toBeInTheDocument();});
  it('pauses an active schedule through the live provider',async()=>{render(<MemoryRouter><ReportSchedulesPage/></MemoryRouter>);await screen.findByText('Weekly operations');await userEvent.click(screen.getByRole('button',{name:'Pause Weekly operations'}));await waitFor(()=>expect(provider.reportScheduleCommand).toHaveBeenCalledWith('22222222-2222-2222-2222-222222222222','pause'));});
});

describe('Advanced analytics',()=>{it('renders insufficient sample states honestly',async()=>{provider.getAdvancedAnalytics.mockResolvedValue({period:{preset:'LAST_90_DAYS',from:'2026-01-01T00:00:00.000Z',to:'2026-04-01T00:00:00.000Z',previousFrom:'2025-10-01T00:00:00.000Z',previousTo:'2026-01-01T00:00:00.000Z',timezone:'Europe/London',localFrom:'2026-01-01',localTo:'2026-03-31',grain:'DAY'},currency:'GBP',minimumSampleSize:10,bookingTrend:[],revenueTrend:[],retention:{status:'INSUFFICIENT_DATA',sampleSize:4,eligible:4,matched:2,percentage:null,explanation:'Small cohort',windowDays:90},rebooking:{status:'INSUFFICIENT_DATA',sampleSize:4,eligible:4,matched:1,percentage:null,explanation:'Small cohort'},leadTime:{status:'INSUFFICIENT_DATA',sampleSize:3,explanation:'Small sample',medianHours:null,averageHours:null,distribution:[]},serviceDemand:[],staffUtilisationTrend:[],bookingPatterns:[],revenueMix:[],clientFrequency:[],forwardBookings:{horizonDays:90,confirmedAppointmentCount:0,confirmedBookingValue:0,currentBookingPace:0,previousBookingPace:0,paceChangePercentage:null,label:'Projected from bookings already confirmed'},limitations:['No false precision.'],generatedAt:'2026-07-19T10:00:00.000Z'});render(<MemoryRouter><AdvancedAnalyticsPage/></MemoryRouter>);expect((await screen.findAllByText('Insufficient data')).length).toBeGreaterThanOrEqual(2);expect(screen.getByText(/Rates require at least 10/)).toBeInTheDocument();expect(provider.getAdvancedAnalytics).toHaveBeenCalledWith(expect.objectContaining({preset:'LAST_90_DAYS'}));});});
