import {CalendarDays,CheckCircle2,Clock3,TrendingDown,TrendingUp,Users} from 'lucide-react';
import type {BusinessProfile,DashboardOverviewResponse,KpiValue} from '@ks-os/contracts';
const money=(value:number,currency:string)=>new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(value/100);
const Change=({metric,suffix=''}:{metric:KpiValue;suffix?:string})=>metric.changeValue===null?<span className="text-xs text-slate-400">No comparison</span>:<span className={`inline-flex items-center gap-1 text-xs font-semibold ${metric.changeValue>0?'text-emerald-700':metric.changeValue<0?'text-rose-700':'text-slate-500'}`}>{metric.changeValue>0?<TrendingUp className="h-3 w-3"/>:metric.changeValue<0?<TrendingDown className="h-3 w-3"/>:null}{metric.changePercentage===null?'Previous period was zero':`${metric.changePercentage>0?'+':''}${metric.changePercentage}% vs previous`}{suffix}</span>;
function KpiCard({label,value,metric,detail}:{label:string;value:string;metric:KpiValue;detail?:string}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-xs"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p><div className="mt-2"><Change metric={metric}/></div>{detail&&<p className="mt-2 text-xs text-slate-500">{detail}</p>}</article>}


export function DashboardWidgets({data,profile}:{data:DashboardOverviewResponse;profile:BusinessProfile}) {
  const show=(key:BusinessProfile['dashboard'][number])=>profile.dashboard.includes(key);
  const empty=data.bookings.total.value===0&&data.revenue.recordedRevenue.value===0&&data.clients.uniqueClients.value===0;
  const ops=[['Appointments today',data.operations.todayAppointments,'/app/calendar'],['Awaiting payment',data.operations.awaitingPayment,'/app/payments'],['Incomplete forms',data.operations.incompleteForms,'/app/forms'],['Failed communications',data.operations.failedEmails+data.operations.failedSms,'/app/settings/communications'],['Open disputes',data.operations.openDisputes,'/app/finance/disputes'],['Payment actions',data.operations.failedPayouts+data.operations.stripeActionRequired,'/app/finance']].filter(([, , href]) => href !== '/app/calendar' || profile.enabledModules.includes('bookings'));

  return <>    {empty&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-4 text-sm text-slate-600">{profile.enabledModules.includes('bookings') ? 'No appointments, recorded revenue, or client activity exists for this period. Values below remain zero rather than showing sample data.' : 'No recorded activity exists for this period.'}</div>}
    <section aria-labelledby="kpis"><h2 id="kpis" className="sr-only">Key performance indicators</h2><div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{show('booking-summary')&&<><KpiCard label="Bookings" value={String(data.bookings.total.value)} metric={data.bookings.total}/><KpiCard label="Completed" value={String(data.bookings.completed.value)} metric={data.bookings.completed}/><KpiCard label="Cancellations" value={String(data.bookings.cancelled.value)} metric={data.bookings.cancelled} detail={`${data.bookings.cancellationRate.value}% of eligible bookings`}/><KpiCard label="No-shows" value={String(data.bookings.noShow.value)} metric={data.bookings.noShow} detail={`${data.bookings.noShowRate.value}% of eligible bookings`}/></>}{show('revenue-summary')&&<><KpiCard label="Recorded revenue" value={money(data.revenue.recordedRevenue.value,data.currency)} metric={data.revenue.recordedRevenue} detail="Successful recorded transactions before refunds"/><KpiCard label="Outstanding" value={money(data.revenue.outstandingAmount.value,data.currency)} metric={data.revenue.outstandingAmount} detail="Awaiting-payment appointments in this period"/><KpiCard label="Average transaction" value={money(data.revenue.averageTransactionValue.value,data.currency)} metric={data.revenue.averageTransactionValue}/></>}{show('customer-summary')&&<KpiCard label={`New ${profile.terminology.customers.toLowerCase()}`} value={String(data.clients.newClients.value)} metric={data.clients.newClients} detail={`${data.clients.returningClients.value} returning`}/>}</div></section>
    {show('operations')&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Today needs attention</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ops.map(([label,value,href])=><a key={label as string} href={href as string} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:border-indigo-300"><span className="text-sm font-semibold text-slate-700">{label}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-sm font-black">{value}</span></a>)}</div></section>}
    <div className="grid gap-6 xl:grid-cols-2">{show('daily-trend')&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Daily trend</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Daily bookings, completions and recorded revenue</caption><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Date</th><th>Bookings</th><th>Completed</th><th>Recorded revenue</th></tr></thead><tbody>{data.dailyTrend.map(day=><tr key={day.date} className="border-b last:border-0"><td className="py-2 font-medium">{day.date}</td><td>{day.bookings}</td><td>{day.completedAppointments}</td><td>{money(day.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div></section>}
      {show('top-services')&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Top services</h2></div>{data.topServices.length===0?<p className="mt-4 text-sm text-slate-500">No service activity in this period.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Service</th><th>Bookings</th><th>Completed</th><th>Revenue</th></tr></thead><tbody>{data.topServices.map(s=><tr key={s.serviceId} className="border-b last:border-0"><td className="py-2 font-semibold">{s.serviceName}</td><td>{s.bookingCount}</td><td>{s.completedCount}</td><td>{money(s.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div>}</section>}</div>
    {show('staff-utilisation')&&<section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">{profile.terminology.staffPlural} activity and utilisation</h2></div><p className="mt-1 text-xs text-slate-500">Availability comes from staff schedules; missing schedules remain unavailable rather than estimated.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Team member</th><th>Booked minutes</th><th>Available minutes</th><th>Utilisation</th><th>Completed</th><th>Recorded revenue</th></tr></thead><tbody>{data.staffUtilisation.map(s=><tr key={s.staffId} className="border-b last:border-0"><td className="py-2 font-semibold">{s.staffName}</td><td>{s.bookedMinutes}</td><td>{s.availableMinutes??'Unavailable'}</td><td>{s.utilisationPercentage===null?'Unavailable':`${s.utilisationPercentage}%`}</td><td>{s.completedAppointments}</td><td>{money(s.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div></section>}
    <footer className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>Net recorded revenue: {money(data.revenue.netRecordedRevenue.value,data.currency)} after {money(data.revenue.refundedAmount.value,data.currency)} completed refunds.</span><span>Updated {new Date(data.generatedAt).toLocaleTimeString('en-GB')}</span></footer></>;
}
