import {useBusinessProfile} from '../../auth/useBusinessProfile';
import {DashboardWidgets} from './DashboardWidgets';
import React,{useCallback,useEffect,useState} from 'react';
import { AlertCircle,RefreshCw } from 'lucide-react';
import type { AnalyticsPreset,DashboardOverviewQuery,DashboardOverviewResponse } from '@ks-os/contracts';
import { getDataProvider } from '../../data/data-provider.js';

const presets:{value:AnalyticsPreset;label:string}[]=[{value:'TODAY',label:'Today'},{value:'LAST_7_DAYS',label:'Last 7 days'},{value:'LAST_30_DAYS',label:'Last 30 days'},{value:'THIS_MONTH',label:'This month'},{value:'CUSTOM',label:'Custom'}];
export function DashboardOverview(){const profile=useBusinessProfile();const [query,setQuery]=useState<DashboardOverviewQuery>({preset:'LAST_7_DAYS'});const [customFrom,setCustomFrom]=useState('');const [customTo,setCustomTo]=useState('');const [data,setData]=useState<DashboardOverviewResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [retry,setRetry]=useState(0);
  const load=useCallback(async()=>{if(query.preset==='CUSTOM'&&(!query.from||!query.to))return;setLoading(true);setError(null);try{setData(await getDataProvider().getDashboardOverview(query));}catch(e:any){setError(e.message||'Dashboard analytics are unavailable.');setData(null);}finally{setLoading(false);}},[query,retry]);useEffect(()=>{void load()},[load]);
  const selectPreset=(preset:AnalyticsPreset)=>{if(preset==='CUSTOM')setQuery({preset,from:customFrom||undefined,to:customTo||undefined});else setQuery({preset});};
  const applyCustom=()=>{if(customFrom&&customTo)setQuery({preset:'CUSTOM',from:customFrom,to:customTo});};
  if(loading&&!data)return <div className="space-y-4" aria-live="polite"><div className="h-20 animate-pulse rounded-2xl bg-slate-200"/><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-slate-200"/>)}</div><p className="sr-only">Loading dashboard analytics</p></div>;
  if(error)return <div role="alert" className="mx-auto max-w-xl rounded-2xl border border-rose-200 bg-white p-8 text-center"><AlertCircle className="mx-auto h-8 w-8 text-rose-600"/><h2 className="mt-3 text-lg font-bold">Dashboard unavailable</h2><p className="mt-2 text-sm text-slate-600">{error}</p><button onClick={()=>setRetry(v=>v+1)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Retry</button></div>;
  if(!data)return null;
  return <main className="space-y-6" aria-busy={loading}>
    <header className="rounded-3xl bg-slate-900 p-6 text-white"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-300">Business performance</p><h2 className="mt-2 text-3xl font-black">{profile.displayName} at a glance</h2><p className="mt-2 text-sm text-slate-300">Live tenant-scoped results for {data.period.localFrom} to {data.period.localTo}, using {data.period.timezone}.</p></div><div className="flex flex-wrap gap-2" aria-label="Reporting period">{presets.map(p=><button key={p.value} onClick={()=>selectPreset(p.value)} aria-pressed={query.preset===p.value} className={`rounded-lg px-3 py-2 text-xs font-bold ${query.preset===p.value?'bg-white text-slate-900':'bg-white/10 text-white hover:bg-white/20'}`}>{p.label}</button>)}</div></div>{query.preset==='CUSTOM'&&<div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs">From<input aria-label="Custom period from" type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)} className="mt-1 block rounded-lg border-0 p-2 text-slate-900"/></label><label className="text-xs">To<input aria-label="Custom period to" type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)} className="mt-1 block rounded-lg border-0 p-2 text-slate-900"/></label><button onClick={applyCustom} disabled={!customFrom||!customTo} className="rounded-lg bg-indigo-500 px-4 py-2 text-sm font-bold disabled:opacity-50">Apply</button></div>}</header>
    <DashboardWidgets data={data} profile={profile}/>
  </main>;
}
