import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { AlertCircle,CalendarDays,CheckCircle2,Clock3,CreditCard,RefreshCw,TrendingDown,TrendingUp,Users } from 'lucide-react';
import type { AnalyticsPreset,DashboardOverviewQuery,DashboardOverviewResponse,KpiValue } from '@ks-os/contracts';
import { getDataProvider } from '../../data/data-provider.js';

const presets:{value:AnalyticsPreset;label:string}[]=[{value:'TODAY',label:'Today'},{value:'LAST_7_DAYS',label:'Last 7 days'},{value:'LAST_30_DAYS',label:'Last 30 days'},{value:'THIS_MONTH',label:'This month'},{value:'CUSTOM',label:'Custom'}];
const money=(value:number,currency:string)=>new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(value/100);
const Change=({metric,suffix=''}:{metric:KpiValue;suffix?:string})=>metric.changeValue===null?<span className="text-xs text-slate-400">No comparison</span>:<span className={`inline-flex items-center gap-1 text-xs font-semibold ${metric.changeValue>0?'text-emerald-700':metric.changeValue<0?'text-rose-700':'text-slate-500'}`}>{metric.changeValue>0?<TrendingUp className="h-3 w-3"/>:metric.changeValue<0?<TrendingDown className="h-3 w-3"/>:null}{metric.changePercentage===null?'Previous period was zero':`${metric.changePercentage>0?'+':''}${metric.changePercentage}% vs previous`}{suffix}</span>;
function KpiCard({label,value,metric,detail}:{label:string;value:string;metric:KpiValue;detail?:string}){return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-xs"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-900">{value}</p><div className="mt-2"><Change metric={metric}/></div>{detail&&<p className="mt-2 text-xs text-slate-500">{detail}</p>}</article>}

export function DashboardOverview(){const [query,setQuery]=useState<DashboardOverviewQuery>({preset:'LAST_7_DAYS'});const [customFrom,setCustomFrom]=useState('');const [customTo,setCustomTo]=useState('');const [data,setData]=useState<DashboardOverviewResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [retry,setRetry]=useState(0);
  const load=useCallback(async()=>{if(query.preset==='CUSTOM'&&(!query.from||!query.to))return;setLoading(true);setError(null);try{setData(await getDataProvider().getDashboardOverview(query));}catch(e:any){setError(e.message||'Dashboard analytics are unavailable.');setData(null);}finally{setLoading(false);}},[query,retry]);useEffect(()=>{void load()},[load]);
  const selectPreset=(preset:AnalyticsPreset)=>{if(preset==='CUSTOM')setQuery({preset,from:customFrom||undefined,to:customTo||undefined});else setQuery({preset});};
  const applyCustom=()=>{if(customFrom&&customTo)setQuery({preset:'CUSTOM',from:customFrom,to:customTo});};
  const empty=useMemo(()=>Boolean(data&&data.bookings.total.value===0&&data.revenue.recordedRevenue.value===0&&data.clients.uniqueClients.value===0),[data]);
  if(loading&&!data)return <div className="space-y-4" aria-live="polite"><div className="h-20 animate-pulse rounded-2xl bg-slate-200"/><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-slate-200"/>)}</div><p className="sr-only">Loading dashboard analytics</p></div>;
  if(error)return <div role="alert" className="mx-auto max-w-xl rounded-2xl border border-rose-200 bg-white p-8 text-center"><AlertCircle className="mx-auto h-8 w-8 text-rose-600"/><h2 className="mt-3 text-lg font-bold">Dashboard unavailable</h2><p className="mt-2 text-sm text-slate-600">{error}</p><button onClick={()=>setRetry(v=>v+1)} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white"><RefreshCw className="h-4 w-4"/>Retry</button></div>;
  if(!data)return null;
  const ops=[['Appointments today',data.operations.todayAppointments,'/app/calendar'],['Awaiting payment',data.operations.awaitingPayment,'/app/payments'],['Incomplete forms',data.operations.incompleteForms,'/app/forms'],['Failed communications',data.operations.failedEmails+data.operations.failedSms,'/app/settings/communications'],['Open disputes',data.operations.openDisputes,'/app/finance/disputes'],['Payment actions',data.operations.failedPayouts+data.operations.stripeActionRequired,'/app/finance']];
  return <main className="space-y-6" aria-busy={loading}>
    <header className="rounded-3xl bg-slate-900 p-6 text-white"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-300">Business performance</p><h2 className="mt-2 text-3xl font-black">Your business at a glance</h2><p className="mt-2 text-sm text-slate-300">Live tenant-scoped results for {data.period.localFrom} to {data.period.localTo}, using {data.period.timezone}.</p></div><div className="flex flex-wrap gap-2" aria-label="Reporting period">{presets.map(p=><button key={p.value} onClick={()=>selectPreset(p.value)} aria-pressed={query.preset===p.value} className={`rounded-lg px-3 py-2 text-xs font-bold ${query.preset===p.value?'bg-white text-slate-900':'bg-white/10 text-white hover:bg-white/20'}`}>{p.label}</button>)}</div></div>{query.preset==='CUSTOM'&&<div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs">From<input aria-label="Custom period from" type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)} className="mt-1 block rounded-lg border-0 p-2 text-slate-900"/></label><label className="text-xs">To<input aria-label="Custom period to" type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)} className="mt-1 block rounded-lg border-0 p-2 text-slate-900"/></label><button onClick={applyCustom} disabled={!customFrom||!customTo} className="rounded-lg bg-indigo-500 px-4 py-2 text-sm font-bold disabled:opacity-50">Apply</button></div>}</header>
    {empty&&<div className="rounded-xl border border-dashed border-slate-300 bg-white p-4 text-sm text-slate-600">No appointments, recorded revenue, or client activity exists for this period. Values below remain zero rather than showing sample data.</div>}
    <section aria-labelledby="kpis"><h2 id="kpis" className="sr-only">Key performance indicators</h2><div className="grid grid-cols-2 gap-4 xl:grid-cols-4"><KpiCard label="Bookings" value={String(data.bookings.total.value)} metric={data.bookings.total}/><KpiCard label="Completed" value={String(data.bookings.completed.value)} metric={data.bookings.completed}/><KpiCard label="Cancellations" value={String(data.bookings.cancelled.value)} metric={data.bookings.cancelled} detail={`${data.bookings.cancellationRate.value}% of eligible bookings`}/><KpiCard label="No-shows" value={String(data.bookings.noShow.value)} metric={data.bookings.noShow} detail={`${data.bookings.noShowRate.value}% of eligible bookings`}/><KpiCard label="Recorded revenue" value={money(data.revenue.recordedRevenue.value,data.currency)} metric={data.revenue.recordedRevenue} detail="Successful recorded transactions before refunds"/><KpiCard label="Outstanding" value={money(data.revenue.outstandingAmount.value,data.currency)} metric={data.revenue.outstandingAmount} detail="Awaiting-payment appointments in this period"/><KpiCard label="Average transaction" value={money(data.revenue.averageTransactionValue.value,data.currency)} metric={data.revenue.averageTransactionValue}/><KpiCard label="New clients" value={String(data.clients.newClients.value)} metric={data.clients.newClients} detail={`${data.clients.returningClients.value} returning`}/></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Today needs attention</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{ops.map(([label,value,href])=><a key={label as string} href={href as string} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:border-indigo-300"><span className="text-sm font-semibold text-slate-700">{label}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-sm font-black">{value}</span></a>)}</div></section>
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Daily trend</h2></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Daily bookings, completions and recorded revenue</caption><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Date</th><th>Bookings</th><th>Completed</th><th>Recorded revenue</th></tr></thead><tbody>{data.dailyTrend.map(day=><tr key={day.date} className="border-b last:border-0"><td className="py-2 font-medium">{day.date}</td><td>{day.bookings}</td><td>{day.completedAppointments}</td><td>{money(day.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Top services</h2></div>{data.topServices.length===0?<p className="mt-4 text-sm text-slate-500">No service activity in this period.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Service</th><th>Bookings</th><th>Completed</th><th>Revenue</th></tr></thead><tbody>{data.topServices.map(s=><tr key={s.serviceId} className="border-b last:border-0"><td className="py-2 font-semibold">{s.serviceName}</td><td>{s.bookingCount}</td><td>{s.completedCount}</td><td>{money(s.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div>}</section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-indigo-600"/><h2 className="text-lg font-black">Team activity and utilisation</h2></div><p className="mt-1 text-xs text-slate-500">Availability comes from staff schedules; missing schedules remain unavailable rather than estimated.</p><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="py-2">Team member</th><th>Booked minutes</th><th>Available minutes</th><th>Utilisation</th><th>Completed</th><th>Recorded revenue</th></tr></thead><tbody>{data.staffUtilisation.map(s=><tr key={s.staffId} className="border-b last:border-0"><td className="py-2 font-semibold">{s.staffName}</td><td>{s.bookedMinutes}</td><td>{s.availableMinutes??'Unavailable'}</td><td>{s.utilisationPercentage===null?'Unavailable':`${s.utilisationPercentage}%`}</td><td>{s.completedAppointments}</td><td>{money(s.recordedRevenue,data.currency)}</td></tr>)}</tbody></table></div></section>
    <footer className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>Net recorded revenue: {money(data.revenue.netRecordedRevenue.value,data.currency)} after {money(data.revenue.refundedAmount.value,data.currency)} completed refunds.</span><span>Updated {new Date(data.generatedAt).toLocaleTimeString('en-GB')}</span></footer>
  </main>;
}
