'use client';

import React, { useState, useEffect } from 'react';
import { supabase } from '@/utils/supabase/client';
import styles from './OnboardingWizard.module.css';

interface ProvisionFormData {
  salonName: string;
  subdomain: string;
  industry: 'barber' | 'nails' | 'aesthetics' | '';
  ownerEmail: string;
  ownerId: string; // The user ID generated by Supabase Auth for the salon owner
}

export default function OnboardingWizard() {
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<ProvisionFormData>({
    salonName: '',
    subdomain: '',
    industry: '',
    ownerEmail: '',
    ownerId: '',
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successTenantId, setSuccessTenantId] = useState<string | null>(null);

  // Hardcoded security check: Only the agency owner can view this wizard
  const AUTHORIZED_AGENCY_EMAIL = 'your-email@ks-studio.com';

  useEffect(() => {
    const checkAgencyAdmin = async () => {
      try {
        const { data: { user }, error: authErr } = await supabase.auth.getUser();
        if (authErr) throw authErr;
        setCurrentUser(user);
      } catch (err) {
        console.error('Error fetching admin auth:', err);
      } finally {
        setCheckingAuth(false);
      }
    };
    checkAgencyAdmin();
  }, []);

  const handleInputChange = (field: keyof ProvisionFormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    setError(null);
  };

  const handleIndustrySelect = (ind: 'barber' | 'nails' | 'aesthetics') => {
    setFormData((prev) => ({ ...prev, industry: ind }));
    setError(null);
  };

  const nextStep = () => {
    // Basic step validation
    if (step === 1) {
      if (!formData.salonName.trim() || !formData.subdomain.trim()) {
        setError('Please complete all salon identity fields.');
        return;
      }
      // Basic subdomain regex check (alphanumeric only)
      const cleanSub = formData.subdomain.toLowerCase().replace(/[^a-z0-9-]/g, '');
      if (cleanSub !== formData.subdomain.toLowerCase()) {
        setError('Subdomain must contain lowercase alphanumeric characters and hyphens only.');
        return;
      }
    }
    if (step === 2 && !formData.industry) {
      setError('Please select an industry vertical.');
      return;
    }
    if (step === 3) {
      if (!formData.ownerEmail.trim() || !formData.ownerId.trim()) {
        setError('Owner email and Supabase Auth ID are required.');
        return;
      }
      // Basic email syntax validation
      if (!formData.ownerEmail.includes('@')) {
        setError('Please enter a valid owner email address.');
        return;
      }
      // Basic UUID syntax check
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      if (!uuidRegex.test(formData.ownerId)) {
        setError('Please enter a valid UUID v4 for the owner Auth ID.');
        return;
      }
    }

    setError(null);
    setStep((prev) => prev + 1);
  };

  const prevStep = () => {
    setError(null);
    setStep((prev) => prev - 1);
  };

  const triggerProvisioning = async () => {
    setIsProcessing(true);
    setError(null);

    try {
      // Trigger Postgres stored procedure RPC on Supabase
      const { data: tenantId, error: rpcErr } = await supabase.rpc('provision_new_tenant', {
        p_name: formData.salonName,
        p_subdomain: formData.subdomain.toLowerCase(),
        p_industry: formData.industry,
        p_owner_email: formData.ownerEmail,
        p_owner_id: formData.ownerId,
      });

      if (rpcErr) throw rpcErr;

      setSuccessTenantId(tenantId);
      setStep(5); // Success step
    } catch (err: any) {
      setError(err.message || 'Tenant provisioning execution failed.');
    } finally {
      setIsProcessing(false);
    }
  };

  if (checkingAuth) return <div className={styles.authChecking}>Verifying Agency Admin Credentials...</div>;

  // Security gate (bypassed in development mode for easy UI testing)
  const isDev = process.env.NODE_ENV === 'development';
  if (!isDev && (!currentUser || currentUser.email !== AUTHORIZED_AGENCY_EMAIL)) {
    return (
      <div className={styles.unauthorizedContainer}>
        <div className={styles.unauthorizedCard}>
          <span className={styles.alertIcon}>🔒</span>
          <h3>Access Denied</h3>
          <p>This onboarding dashboard is restricted to the KS Studio Master Agency Administrator.</p>
        </div>
      </div>
    );
  }


  return (
    <div className={styles.wizardContainer}>
      <div className={styles.wizardHeader}>
        <h2>Agency Onboarding Dashboard</h2>
        <span className={styles.headerSubtitle}>KS Studio Salon Tenant Provisioning</span>
      </div>

      {/* Steps Progress Indicators */}
      {step <= 4 && (
        <div className={styles.progressBar}>
          <div className={`${styles.progressStep} ${step >= 1 ? styles.stepActive : ''}`}>1. Identity</div>
          <div className={`${styles.progressStep} ${step >= 2 ? styles.stepActive : ''}`}>2. Vertical</div>
          <div className={`${styles.progressStep} ${step >= 3 ? styles.stepActive : ''}`}>3. Owner</div>
          <div className={`${styles.progressStep} ${step >= 4 ? styles.stepActive : ''}`}>4. Confirm</div>
        </div>
      )}

      {error && <div className={styles.errorMessage}>{error}</div>}

      <div className={styles.wizardContent}>
        {/* STEP 1: Basic Identity */}
        {step === 1 && (
          <div className={styles.stepContainer}>
            <h3>Step 1: Salon Identity</h3>
            <p className={styles.stepDesc}>Enter the basic trading name and choose their unique tenant URL subdomain.</p>
            
            <div className={styles.inputGroup}>
              <label htmlFor="salonName" className={styles.label}>Salon Name</label>
              <input
                id="salonName"
                type="text"
                className={styles.input}
                placeholder="e.g. The Hair Lounge"
                value={formData.salonName}
                onChange={(e) => handleInputChange('salonName', e.target.value)}
              />
            </div>

            <div className={styles.inputGroup}>
              <label htmlFor="subdomain" className={styles.label}>Subdomain URL</label>
              <div className={styles.subdomainInputWrapper}>
                <input
                  id="subdomain"
                  type="text"
                  className={styles.subdomainInput}
                  placeholder="e.g. hair-lounge"
                  value={formData.subdomain}
                  onChange={(e) => handleInputChange('subdomain', e.target.value)}
                />
                <span className={styles.subdomainDomainSuffix}>.growthos.com</span>
              </div>
            </div>
          </div>
        )}

        {/* STEP 2: Industry Vertical */}
        {step === 2 && (
          <div className={styles.stepContainer}>
            <h3>Step 2: Choose Industry Starter Pack</h3>
            <p className={styles.stepDesc}>This configures the default intake forms and service directories for the salon type.</p>

            <div className={styles.cardsGrid}>
              <button
                type="button"
                className={`${styles.verticalCard} ${formData.industry === 'barber' ? styles.verticalCardSelected : ''}`}
                onClick={() => handleIndustrySelect('barber')}
              >
                <span className={styles.cardEmoji}>💈</span>
                <span className={styles.cardTitle}>Barber Shop</span>
                <span className={styles.cardDetail}>Includes Skin Fades, Beard Trims, and Razor Waivers.</span>
              </button>

              <button
                type="button"
                className={`${styles.verticalCard} ${formData.industry === 'nails' ? styles.verticalCardSelected : ''}`}
                onClick={() => handleIndustrySelect('nails')}
              >
                <span className={styles.cardEmoji}>💅</span>
                <span className={styles.cardTitle}>Nail Salon</span>
                <span className={styles.cardDetail}>Includes Gel Manicures, Acrylics, and Treatment Consent.</span>
              </button>

              <button
                type="button"
                className={`${styles.verticalCard} ${formData.industry === 'aesthetics' ? styles.verticalCardSelected : ''}`}
                onClick={() => handleIndustrySelect('aesthetics')}
              >
                <span className={styles.cardEmoji}>💉</span>
                <span className={styles.cardTitle}>Aesthetics Clinic</span>
                <span className={styles.cardDetail}>Includes Laser Facials, Botox consultations, and Clinical Consent.</span>
              </button>
            </div>
          </div>
        )}

        {/* STEP 3: Owner Details */}
        {step === 3 && (
          <div className={styles.stepContainer}>
            <h3>Step 3: Salon Owner Profile</h3>
            <p className={styles.stepDesc}>Register the owner's credential details. You must create the auth user account first to acquire their Supabase Auth ID.</p>

            <div className={styles.inputGroup}>
              <label htmlFor="ownerEmail" className={styles.label}>Owner Email</label>
              <input
                id="ownerEmail"
                type="email"
                className={styles.input}
                placeholder="e.g. owner@salonname.com"
                value={formData.ownerEmail}
                onChange={(e) => handleInputChange('ownerEmail', e.target.value)}
              />
            </div>

            <div className={styles.inputGroup}>
              <label htmlFor="ownerId" className={styles.label}>Supabase Auth ID (UUID)</label>
              <input
                id="ownerId"
                type="text"
                className={styles.input}
                placeholder="e.g. d68a35e2-2cf2-4c22-8ea9-..."
                value={formData.ownerId}
                onChange={(e) => handleInputChange('ownerId', e.target.value)}
              />
            </div>
          </div>
        )}

        {/* STEP 4: Confirmation & Trigger */}
        {step === 4 && (
          <div className={styles.stepContainer}>
            <h3>Step 4: Confirm Workspace Setup</h3>
            <p className={styles.stepDesc}>Double check the configuration profiles before triggering the database provision actions.</p>

            <div className={styles.confirmationTable}>
              <div className={styles.confirmRow}>
                <span>Salon Name:</span>
                <strong>{formData.salonName}</strong>
              </div>
              <div className={styles.confirmRow}>
                <span>URL Domain:</span>
                <strong>{formData.subdomain}.growthos.com</strong>
              </div>
              <div className={styles.confirmRow}>
                <span>Industry Vertical:</span>
                <strong style={{ textTransform: 'capitalize' }}>{formData.industry}</strong>
              </div>
              <div className={styles.confirmRow}>
                <span>Owner Email:</span>
                <strong>{formData.ownerEmail}</strong>
              </div>
              <div className={styles.confirmRow}>
                <span>Owner Auth UUID:</span>
                <span className={styles.monoUuid}>{formData.ownerId}</span>
              </div>
            </div>

            <p className={styles.warningAlertText}>
              ⚠️ Triggers multi-row table insertions, schemas creation, and user role overrides inside database records.
            </p>
          </div>
        )}

        {/* STEP 5: Success Output */}
        {step === 5 && (
          <div className={styles.successScreen}>
            <span className={styles.successIcon}>🎉</span>
            <h3>Workspace Provisioned!</h3>
            <p><strong>{formData.salonName}</strong> has been successfully configured.</p>
            <div className={styles.successDetails}>
              <div>Tenant ID: <span className={styles.monoUuid}>{successTenantId}</span></div>
              <div>Subdomain: <span>{formData.subdomain}.growthos.com</span></div>
              <div>Starter Pack Installed: <span style={{ textTransform: 'capitalize' }}>{formData.industry}</span></div>
            </div>
            <button
              type="button"
              className={styles.successResetButton}
              onClick={() => {
                setFormData({
                  salonName: '',
                  subdomain: '',
                  industry: '',
                  ownerEmail: '',
                  ownerId: '',
                });
                setStep(1);
                setSuccessTenantId(null);
              }}
            >
              Onboard Another Salon
            </button>
          </div>
        )}
      </div>

      {/* Footer Nav Controls */}
      {step <= 4 && (
        <div className={styles.wizardFooter}>
          {step > 1 && (
            <button type="button" className={styles.backButton} onClick={prevStep} disabled={isProcessing}>
              Back
            </button>
          )}
          {step < 4 ? (
            <button type="button" className={styles.nextButton} onClick={nextStep}>
              Next Step
            </button>
          ) : (
            <button
              type="button"
              className={styles.provisionButton}
              onClick={triggerProvisioning}
              disabled={isProcessing}
            >
              {isProcessing ? 'Provisioning...' : 'Provision Workspace Now'}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
