import { index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid, varchar, boolean } from 'drizzle-orm/pg-core';
import { agencyUsers, tenants } from './schema.js';

export const designLibraryItems = pgTable('design_library_items', {
  id: uuid('id').defaultRandom().primaryKey(),
  publicReference: uuid('public_reference').defaultRandom().notNull().unique(),
  slug: varchar('slug', { length: 120 }).notNull().unique(),
  name: varchar('name', { length: 160 }).notNull(),
  description: text('description').notNull(),
  itemKind: varchar('item_kind', { length: 30 }).notNull(),
  category: varchar('category', { length: 80 }).notNull(),
  status: varchar('status', { length: 30 }).default('DRAFT').notNull(),
  sourceType: varchar('source_type', { length: 30 }).notNull(),
  tagsJson: jsonb('tags_json').default([]).notNull(),
  themeJson: jsonb('theme_json').default({}).notNull(),
  definitionJson: jsonb('definition_json').default({}).notNull(),
  pageManifestJson: jsonb('page_manifest_json').default([]).notNull(),
  previewJson: jsonb('preview_json').default({}).notNull(),
  previewImageUrl: text('preview_image_url'),
  previewHtmlUrl: text('preview_html_url'),
  sourceMetadataJson: jsonb('source_metadata_json').default({}).notNull(),
  accessibilityJson: jsonb('accessibility_json').default({}).notNull(),
  latestRevision: integer('latest_revision').default(1).notNull(),
  availableForClientDelivery: boolean('available_for_client_delivery').default(false).notNull(),
  isSystem: boolean('is_system').default(false).notNull(),
  createdByAgencyUserId: uuid('created_by_agency_user_id').references(() => agencyUsers.id, { onDelete: 'restrict' }),
  approvedByAgencyUserId: uuid('approved_by_agency_user_id').references(() => agencyUsers.id, { onDelete: 'restrict' }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, table => ({
  kindStatusIdx: index('design_library_items_kind_status_idx').on(table.itemKind, table.status, table.updatedAt),
  categoryStatusIdx: index('design_library_items_category_status_idx').on(table.category, table.status, table.updatedAt),
  sourceStatusIdx: index('design_library_items_source_status_idx').on(table.sourceType, table.status, table.updatedAt),
  deliveryIdx: index('design_library_items_delivery_idx').on(table.itemKind, table.availableForClientDelivery, table.status),
}));

export const designLibraryGenerations = pgTable('design_library_generations', {
  id: uuid('id').defaultRandom().primaryKey(),
  publicReference: uuid('public_reference').defaultRandom().notNull().unique(),
  itemId: uuid('item_id').notNull().references(() => designLibraryItems.id, { onDelete: 'restrict' }),
  status: varchar('status', { length: 30 }).default('PENDING').notNull(),
  targetKind: varchar('target_kind', { length: 30 }).notNull(),
  sourceType: varchar('source_type', { length: 30 }).notNull(),
  prompt: text('prompt').notNull(),
  providerKey: varchar('provider_key', { length: 80 }),
  modelKey: varchar('model_key', { length: 160 }),
  stitchProjectReference: varchar('stitch_project_reference', { length: 255 }),
  stitchScreenReference: varchar('stitch_screen_reference', { length: 255 }),
  outputDigestSha256: varchar('output_digest_sha256', { length: 64 }),
  safeMetadataJson: jsonb('safe_metadata_json').default({}).notNull(),
  failureCode: varchar('failure_code', { length: 100 }),
  failureMessage: varchar('failure_message', { length: 500 }),
  requestedByAgencyUserId: uuid('requested_by_agency_user_id').notNull().references(() => agencyUsers.id, { onDelete: 'restrict' }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  failedAt: timestamp('failed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}, table => ({
  itemCreatedIdx: index('design_library_generations_item_created_idx').on(table.itemId, table.createdAt),
  statusCreatedIdx: index('design_library_generations_status_created_idx').on(table.status, table.createdAt),
  requesterCreatedIdx: index('design_library_generations_requester_created_idx').on(table.requestedByAgencyUserId, table.createdAt),
}));

export const designLibraryAssignments = pgTable('design_library_assignments', {
  id: uuid('id').defaultRandom().primaryKey(),
  publicReference: uuid('public_reference').defaultRandom().notNull().unique(),
  itemId: uuid('item_id').notNull().references(() => designLibraryItems.id, { onDelete: 'restrict' }),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'restrict' }),
  status: varchar('status', { length: 20 }).default('ACTIVE').notNull(),
  assignedByAgencyUserId: uuid('assigned_by_agency_user_id').notNull().references(() => agencyUsers.id, { onDelete: 'restrict' }),
  assignedAt: timestamp('assigned_at', { withTimezone: true }).defaultNow().notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, table => ({
  tenantStatusIdx: index('design_library_assignments_tenant_status_idx').on(table.tenantId, table.status, table.assignedAt),
  itemStatusIdx: index('design_library_assignments_item_status_idx').on(table.itemId, table.status, table.assignedAt),
  tenantItemUnique: uniqueIndex('design_library_assignments_tenant_item_unique').on(table.tenantId, table.itemId, table.assignedAt),
}));
