import { boolean, index, integer, jsonb, pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { agencySupportSessions, agencyUsers, tenants, users } from './schema.js';

export const platformErrorEvents = pgTable('platform_error_events', {
  id: uuid('id').defaultRandom().primaryKey(),
  fingerprint: varchar('fingerprint', { length: 64 }).notNull(),
  severity: varchar('severity', { length: 20 }).notNull(),
  statusCode: integer('status_code').notNull(),
  errorCode: varchar('error_code', { length: 120 }).notNull(),
  errorType: varchar('error_type', { length: 160 }).notNull(),
  message: text('message').notNull(),
  stack: text('stack'),
  originFile: varchar('origin_file', { length: 500 }),
  originFunction: varchar('origin_function', { length: 255 }),
  originLine: integer('origin_line'),
  originColumn: integer('origin_column'),
  requestId: varchar('request_id', { length: 100 }).notNull(),
  correlationId: varchar('correlation_id', { length: 100 }),
  method: varchar('method', { length: 12 }).notNull(),
  route: varchar('route', { length: 500 }).notNull(),
  sourceComponent: varchar('source_component', { length: 120 }).default('ks-os-api').notNull(),
  environment: varchar('environment', { length: 40 }).default('production').notNull(),
  tenantId: uuid('tenant_id').references(() => tenants.id, { onDelete: 'restrict' }),
  tenantUserId: uuid('tenant_user_id').references(() => users.id, { onDelete: 'restrict' }),
  agencyUserId: uuid('agency_user_id').references(() => agencyUsers.id, { onDelete: 'restrict' }),
  authUserId: uuid('auth_user_id'),
  supportSessionId: uuid('support_session_id').references(() => agencySupportSessions.id, { onDelete: 'restrict' }),
  applicationContext: varchar('application_context', { length: 20 }),
  sessionId: uuid('session_id'),
  ipHash: varchar('ip_hash', { length: 64 }),
  userAgent: varchar('user_agent', { length: 500 }),
  retryable: boolean('retryable').default(false).notNull(),
  context: jsonb('context').default({}).notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).defaultNow().notNull(),
}, table => ({
  occurredIdx: index('platform_error_events_occurred_idx').on(table.occurredAt),
  fingerprintOccurredIdx: index('platform_error_events_fingerprint_occurred_idx').on(table.fingerprint, table.occurredAt),
  tenantOccurredIdx: index('platform_error_events_tenant_occurred_idx').on(table.tenantId, table.occurredAt),
  tenantUserOccurredIdx: index('platform_error_events_tenant_user_occurred_idx').on(table.tenantUserId, table.occurredAt),
  agencyUserOccurredIdx: index('platform_error_events_agency_user_occurred_idx').on(table.agencyUserId, table.occurredAt),
  requestIdx: index('platform_error_events_request_idx').on(table.requestId),
  statusOccurredIdx: index('platform_error_events_status_occurred_idx').on(table.statusCode, table.occurredAt),
  routeOccurredIdx: index('platform_error_events_route_occurred_idx').on(table.route, table.occurredAt),
}));
