export interface MigrationManifestEntry {
  filename: string;
  order: number;
  description: string;
}

export const MIGRATION_MANIFEST: MigrationManifestEntry[] = [
  { filename: '0000_uneven_richard_fisk.sql', order: 1, description: 'Core schema initialization (tenants, users, appointments, clients, services, transactions)' },
  { filename: '0001_amazing_solo.sql', order: 2, description: 'Base tables for email outbox, stripe disputes, payment attempts, payouts' },
  { filename: '0001_stripe_booking_payments.sql', order: 3, description: 'FK constraints and unique indices for stripe_payment_attempts' },
  { filename: '0002_stripe_refunds.sql', order: 4, description: 'Stripe refunds table and transaction/appointment foreign keys' },
  { filename: '0003_stripe_finance.sql', order: 5, description: 'Stripe payout items, payout summary indices, and finance foreign keys' },
  { filename: '0004_phase_6_1_secure_forms.sql', order: 6, description: 'Form versions and form assignments schema' },
  { filename: '0005_phase_6_3_transactional_sms.sql', order: 7, description: 'SMS outbox and Twilio webhook event tracking' },
  { filename: '0006_phase_7_1_workflow_automation_engine.sql', order: 8, description: 'Automation rules, action runs, business events, internal notifications' },
  { filename: '0007_phase_7_2_operations_inbox.sql', order: 9, description: 'Operations issue tracking schema' },
  { filename: '0008_phase_7_3_tasks_and_followups.sql', order: 10, description: 'Tasks and task activity tracking' },
  { filename: '20260719120000_phase_6_2_transactional_email.sql', order: 11, description: 'Transactional email outbox and suppressions schema' },
  { filename: '20260719170000_phase_9_1_team_management.sql', order: 12, description: 'Staff invitations and staff service assignments' },
  { filename: '20260719200000_phase_9_2_9_5_team_operations.sql', order: 13, description: 'Multi-location support, staff locations, service locations, time off, commission rules' },
  { filename: '20260719210000_phase_8_3_8_4_reporting_analytics.sql', order: 14, description: 'Reporting schedules, export jobs, and schedule runs' },
  { filename: '20260720100000_phase_10_1_customer_portal.sql', order: 15, description: 'Customer accounts, client link resolution, account claims' },
  { filename: '20260720135949_phase_10_2_customer_booking_management.sql', order: 16, description: 'Self-service customer booking management tokens, policy settings, audit history' },
  { filename: '20260720170000_phase_10_6_external_reviews.sql', order: 17, description: 'Reputation management, review provider connections, review invitations' },
  { filename: '20260720230000_phase_12_agency_operations.sql', order: 18, description: 'Agency users, commercial billing accounts, platform entitlements, onboarding stages' },
  { filename: '20260720235900_phase_12_0_unified_authentication.sql', order: 19, description: 'Unified authentication schema, application sessions, account invitations' },
  { filename: '20260722000000_provider_neutral_pos.sql', order: 20, description: 'Provider-neutral checkout payment components' },
  { filename: '20260722130000_production_schema_reconciliation.sql', order: 21, description: 'Production additive schema reconciliation for 13 missing tables' },
  { filename: '20260722220000_phase_14_compliance_operations.sql', order: 22, description: 'Phase 14 compliance audit, consent, privacy requests, legal holds, and retention operations' },
  { filename: '20260723000000_phase_13_integrations.sql', order: 23, description: 'Phase 13 provider-neutral integrations, automation credentials, and supported hardware' },
  { filename: '20260723010000_advanced_intake_forms.sql', order: 24, description: 'Advanced versioned intake forms, save-and-resume, files, templates, review, and analytics' },
  { filename: '20260723020000_booking_operations_platform.sql', order: 25, description: 'Booking operations calendar, automatic public booking pages, temporary slot holds, source attribution, audit, and analytics' },
  { filename: '20260724180000_align_checkout_payment_components_schema.sql', order: 26, description: 'Align production checkout payment components with provider-neutral POS schema' },
  { filename: '20260724090000_phase_15_0_15_2_website_foundation.sql', order: 27, description: 'Phase 15.0-15.2 managed website architecture, site domain model, entitlements, and native booking references' },
  { filename: '20260724110000_phase_15_3_template_intelligence.sql', order: 28, description: 'Phase 15.3 secure template inventory, deterministic analysis, approved layout compatibility, and site-specific licensing' },
  { filename: '20260724130000_phase_15_4_site_blueprint_engine.sql', order: 29, description: 'Phase 15.4 deterministic site blueprint revisions, typed page mappings, generation runs, action items, and approved-architecture immutability' },
  { filename: '20260724150000_phase_15_5_public_site_renderer.sql', order: 30, description: 'Phase 15.5 compile-time renderer mappings, immutable public render snapshots, and signed-preview revocation records' },
  { filename: '20260725090000_phase_15_6a_site_worker_foundation.sql', order: 31, description: 'Phase 15.6A durable site-job leasing, attempt history, operational events, cancellation, and worker safety constraints' },
  { filename: '20260725130000_phase_15_6b_expert_knowledge_engine.sql', order: 32, description: 'Phase 15.6B immutable expert-knowledge packs, provenance, rule applicability, playbooks, import governance, and activation safety' },
  { filename: '20260725170000_phase_15_6c_structured_ai_generation.sql', order: 33, description: 'Phase 15.6C controlled structured site generation, provenance, findings, claims, contexts, and draft-only recovery records' },
  { filename: '20260725180000_phase_15_6c_generation_runtime.sql', order: 34, description: 'Phase 15.6C validated structured page persistence for generation and controlled regeneration' },
  { filename: '20260726090000_phase_15_7a_site_review_workflows.sql', order: 35, description: 'Phase 15.7A version-pinned Site Studio review cycles, comments, change requests, facts, approvals, invitations, sessions, and audit activity' },
  { filename: '20260726130000_phase_15_7b_unified_provisioning_site_studio.sql', order: 36, description: 'Phase 15.7B controlled fact finding, locked production briefs, resumable unified workspace provisioning, and Site Studio readiness' },
  { filename: '20260727100000_phase_15_8_site_quality_gates.sql', order: 37, description: 'Phase 15.8 exact-version SEO, accessibility, UX, conversion, booking, content, asset, evidence, waiver, and publication-readiness quality gates' },
  { filename: '20260727110000_reconcile_site_jobs_status_constraint.sql', order: 38, description: 'Remove the obsolete duplicate site-job status check while preserving the canonical Phase 15.6A lifecycle constraint' },
  { filename: '20260727120000_reconcile_site_quality_child_scope_trigger.sql', order: 39, description: 'Reconcile polymorphic Phase 15.8 quality child-scope validation without weakening ownership, digest, or parent-child guarantees' },
  { filename: '20260727130000_phase_15_9_site_publishing_domains.sql', order: 40, description: 'Phase 15.9 immutable publication pointers, governed hostnames, reviewed DNS operations, health evidence, cache invalidation, and rollback history' },
  { filename: '20260727170000_reconcile_agency_audit_columns.sql', order: 41, description: 'Reconcile append-only agency audit columns required by launch, support, recovery, and administrative actions' },
  { filename: '20260727233000_workspace_hard_delete_and_test_reset.sql', order: 42, description: 'Platform-owner workspace test reset, irreversible tenant purge, private file cleanup, and authentication identity removal support' },
  { filename: '20260728010000_platform_error_log.sql', order: 43, description: 'Append-only privacy-minimised platform error evidence with actor, workspace, request, route, origin and stack context' },
  { filename: '20260728030000_default_client_onboarding_fact_find.sql', order: 44, description: 'Seed the recommended active KS OS client onboarding intake used for assisted and self-service fact finding' },
  { filename: '20260728113000_repair_workspace_test_reset.sql', order: 45, description: 'Repair workspace test reset for Supabase system-trigger restrictions, optional baselined tables, compliance retention, and server-only execution' },
  { filename: '20260728100000_stripe_first_pos.sql', order: 46, description: 'Set the first inventory-enabled package to £197 for the Stripe-first POS launch' },
  { filename: '20260728170000_workspace_public_surface_routes.sql', order: 47, description: 'Assign stable public form slugs and support workspace-hosted booking and form routes' },
  { filename: '20260729213000_seed_native_design_delivery.sql', order: 48, description: 'Seed the owned KS Native Component System and approved renderer mappings used by one-click design-library delivery' },
  { filename: '20260729221500_agency_design_component_studio.sql', order: 49, description: 'Add the governed agency Design Studio library, AI and Stitch generation history, prebuilt site themes, and client theme assignments' },
  { filename: '20260729234500_calendar_availability_overrides.sql', order: 50, description: 'Date-specific in-shop and mobile booking-hour overrides managed from the booking calendar' },
  { filename: '20260730182500_expand_appointment_status_constraint.sql', order: 51, description: 'Allow the full operational appointment lifecycle including checked-in walk-ins, in-service work, and awaiting-payment states' },
  { filename: '20260730210500_standalone_retail_pos.sql', order: 52, description: 'Allow idempotent product-only POS transactions without an appointment and preserve transaction history when bookings are removed' },
  { filename: '20260731130000_reconcile_phase_13_integrations.sql', order: 53, description: 'Reconcile Phase 13 integration tables missing behind an applied historical migration ledger entry' },
  { filename: '20260730223000_omnichannel_conversations.sql', order: 54, description: 'Tenant-isolated omnichannel channels, conversations, messages, attachments, assignment, unread state, and booking context' },
  { filename: '20260731102000_connected_mailbox_timestamp.sql', order: 55, description: 'Connected mailbox authorization timestamp and bounded Google/Zoho sync index' },
  { filename: '20260801033000_whatsapp_tier_messaging.sql', order: 56, description: 'Package-aware WhatsApp service windows, approved templates, and marketing consent evidence' },
];
