import { randomUUID } from 'node:crypto';
import { sql } from 'drizzle-orm';
import { getDatabase } from '@ks-os/database';
import { getStripeClient } from '../../lib/stripe.js';
import { decryptSecret,encryptSecret,hashSecret,issueOpaqueSecret,signState,validateWebhookUrl } from './integration-security.js';
import { renderCalendar } from './ical.js';

const db=()=>getDatabase();
const fail=(statusCode:number,code:string,message:string)=>Object.assign(new Error(message),{statusCode,code});
const csv=(rows:Record<string,unknown>[])=>{if(!rows.length)return'';const keys=Object.keys(rows[0]);const cell=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');};

export class IntegrationsService{
 async list(tenantId:string){const r=await db().execute(sql`select id,kind,provider,external_account_id,external_resource_id,external_resource_name,status,sync_direction,settings,last_successful_sync_at,last_attempted_sync_at,last_sync_error,webhook_expires_at,disconnected_at,created_at,updated_at from integration_connections where tenant_id=${tenantId}::uuid order by kind,provider`);return r.rows;}
 oauthUrl(tenantId:string,userId:string,provider:string,returnPath:string){const state=signState({tenantId,userId,provider,returnPath,nonce:randomUUID()});const config:any={GOOGLE_CALENDAR:{base:'https://accounts.google.com/o/oauth2/v2/auth',client:process.env.GOOGLE_CALENDAR_CLIENT_ID,redirect:process.env.GOOGLE_CALENDAR_REDIRECT_URI,scope:'openid email https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.readonly'},MICROSOFT_OUTLOOK:{base:'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',client:process.env.MICROSOFT_CALENDAR_CLIENT_ID,redirect:process.env.MICROSOFT_CALENDAR_REDIRECT_URI,scope:'offline_access User.Read Calendars.ReadWrite'},XERO:{base:'https://login.xero.com/identity/connect/authorize',client:process.env.XERO_CLIENT_ID,redirect:process.env.XERO_REDIRECT_URI,scope:'openid profile email offline_access accounting.transactions accounting.contacts'},QUICKBOOKS:{base:'https://appcenter.intuit.com/connect/oauth2',client:process.env.QUICKBOOKS_CLIENT_ID,redirect:process.env.QUICKBOOKS_REDIRECT_URI,scope:'com.intuit.quickbooks.accounting openid profile email'}}[provider];if(!config?.client||!config.redirect)throw fail(503,'PROVIDER_NOT_CONFIGURED',`${provider} credentials are not configured.`);const q=new URLSearchParams({client_id:config.client,redirect_uri:config.redirect,response_type:'code',scope:config.scope,state});if(provider==='GOOGLE_CALENDAR')q.set('access_type','offline');return`${config.base}?${q}`;}
 async disconnect(tenantId:string,userId:string,id:string){const r=await db().execute(sql`update integration_connections set status='DISCONNECTED',token_ciphertext=null,disconnected_at=now(),updated_at=now() where id=${id}::uuid and tenant_id=${tenantId}::uuid returning id,status`);if(!r.rows[0])throw fail(404,'INTEGRATION_NOT_FOUND','Integration not found');await this.audit(tenantId,userId,'INTEGRATION_DISCONNECTED','INTEGRATION',id);return r.rows[0];}
 async createFeed(tenantId:string,userId:string,input:any,origin:string){const token=issueOpaqueSecret('cal');const r=await db().execute(sql`insert into calendar_feeds(tenant_id,scope,staff_user_id,location_id,token_hash,booking_statuses,privacy_level,created_by_user_id) values(${tenantId}::uuid,${input.scope},${input.staffUserId??null}::uuid,${input.locationId??null}::uuid,${hashSecret(token)},${input.bookingStatuses}::text[],${input.privacyLevel},${userId}::uuid) returning id,scope,staff_user_id,location_id,privacy_level,created_at`);await this.audit(tenantId,userId,'CALENDAR_FEED_CREATED','CALENDAR_FEED',(r.rows[0] as any).id);return{...r.rows[0],url:`${origin}/api/v1/public/calendar-feeds/${token}.ics`};}
 async rotateFeed(tenantId:string,userId:string,id:string,origin:string){const token=issueOpaqueSecret('cal');const r=await db().execute(sql`update calendar_feeds set token_hash=${hashSecret(token)},rotated_at=now() where id=${id}::uuid and tenant_id=${tenantId}::uuid and revoked_at is null returning id`);if(!r.rows[0])throw fail(404,'CALENDAR_FEED_NOT_FOUND','Calendar feed not found');await this.audit(tenantId,userId,'CALENDAR_FEED_TOKEN_ROTATED','CALENDAR_FEED',id);return{id,url:`${origin}/api/v1/public/calendar-feeds/${token}.ics`};}
 async revokeFeed(tenantId:string,userId:string,id:string){const r=await db().execute(sql`update calendar_feeds set revoked_at=now() where id=${id}::uuid and tenant_id=${tenantId}::uuid and revoked_at is null returning id`);if(!r.rows[0])throw fail(404,'CALENDAR_FEED_NOT_FOUND','Calendar feed not found');await this.audit(tenantId,userId,'CALENDAR_FEED_REVOKED','CALENDAR_FEED',id);}
 async calendar(token:string){const feed=(await db().execute(sql`select * from calendar_feeds where token_hash=${hashSecret(token)} and revoked_at is null limit 1`)).rows[0] as any;if(!feed)throw fail(404,'CALENDAR_FEED_NOT_FOUND','Calendar feed not found');const r=await db().execute(sql`select a.id,a.public_reference,a.start_time,a.end_time,a.updated_at,a.status,a.version,s.name service_name,u.name staff_name,l.name location_name from appointments a left join services s on s.id=a.service_id and s.tenant_id=a.tenant_id left join users u on u.id=a.user_id and u.tenant_id=a.tenant_id left join locations l on l.id=a.location_id and l.tenant_id=a.tenant_id where a.tenant_id=${feed.tenant_id}::uuid and a.status=any(${feed.booking_statuses}::text[]) and (${feed.scope}!='STAFF' or a.user_id=${feed.staff_user_id}::uuid) and (${feed.scope}!='LOCATION' or a.location_id=${feed.location_id}::uuid) and a.end_time>=now()-interval '30 days' and a.start_time<now()+interval '1 year' order by a.start_time limit 10000`);return renderCalendar('KS OS bookings',(r.rows as any[]).map(x=>({id:x.id,reference:x.public_reference,start:x.start_time,end:x.end_time,updated:x.updated_at,status:x.status,version:x.version,summary:feed.privacy_level==='BUSY_ONLY'?'Busy':`${x.service_name||'Booking'} — ${x.staff_name||'Staff'}`,location:x.location_name})));}
 async accountingExport(tenantId:string,userId:string,q:any){const r=await db().execute(sql`select ct.created_at "transactionDate",a.public_reference "bookingReference",c.id "customerReference",c.name "customerName",ct.id "paymentReference",s.name description,s.name service,l.name location,u.name "staffMember",ct.total_amount "grossAmount",greatest(ct.total_amount-coalesce(ref.refunded,0),0) "netAmount",0 "taxAmount",0 discount,0 tip,0 "processingFee",coalesce(ref.refunded,0) "refundAmount",t.currency,ct.payment_method "paymentMethod",ct.payment_status "paymentStatus",null "taxCode",null "accountCode",ct.stripe_payment_intent_id "externalAccountingId" from checkout_transactions ct join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id join tenants t on t.id=ct.tenant_id left join clients c on c.id=a.client_id and c.tenant_id=a.tenant_id left join services s on s.id=a.service_id and s.tenant_id=a.tenant_id left join users u on u.id=a.user_id and u.tenant_id=a.tenant_id left join locations l on l.id=a.location_id and l.tenant_id=a.tenant_id left join lateral(select coalesce(sum(amount) filter(where status='SUCCEEDED'),0) refunded from stripe_refunds where checkout_transaction_id=ct.id)ref on true where ct.tenant_id=${tenantId}::uuid and ct.created_at>=${q.from} and ct.created_at<${q.to} and ct.payment_status in ('SUCCEEDED','REFUNDED') and (${q.locationId??null}::uuid is null or a.location_id=${q.locationId??null}::uuid) and (${q.paymentStatus??null}::text is null or ct.payment_status=${q.paymentStatus??null}) order by ct.created_at`);await this.audit(tenantId,userId,'ACCOUNTING_EXPORT_CREATED','ACCOUNTING_EXPORT',randomUUID());return q.format==='json'?JSON.stringify({schemaVersion:1,rows:r.rows},null,2):csv(r.rows as any);}
 async createCredential(tenantId:string,userId:string,input:any){const secret=issueOpaqueSecret(input.environment==='test'?'ks_test':'ks_live');const r=await db().execute(sql`insert into api_credentials(tenant_id,name,key_hash,key_prefix,scopes,environment,created_by_user_id,expires_at) values(${tenantId}::uuid,${input.name},${hashSecret(secret)},${secret.slice(0,16)},${input.scopes}::text[],${input.environment},${userId}::uuid,${input.expiresAt??null}) returning id,name,key_prefix,scopes,environment,created_at,expires_at`);await this.audit(tenantId,userId,'API_KEY_CREATED','API_CREDENTIAL',(r.rows[0] as any).id);return{...r.rows[0],key:secret};}
 async revokeCredential(tenantId:string,userId:string,id:string){const r=await db().execute(sql`update api_credentials set revoked_at=now() where id=${id}::uuid and tenant_id=${tenantId}::uuid and revoked_at is null returning id`);if(!r.rows[0])throw fail(404,'API_CREDENTIAL_NOT_FOUND','API credential not found');await this.audit(tenantId,userId,'API_KEY_REVOKED','API_CREDENTIAL',id);}
 async createWebhook(tenantId:string,userId:string,input:any){const target=await validateWebhookUrl(input.targetUrl);const secret=issueOpaqueSecret('whsec');const r=await db().execute(sql`insert into webhook_subscriptions(tenant_id,name,target_url,secret_ciphertext,event_types,description,allowed_host,environment,created_by_user_id) values(${tenantId}::uuid,${input.name},${target.url},${encryptSecret({secret})},${input.eventTypes}::text[],${input.description??null},${target.host},${input.environment},${userId}::uuid) returning id,name,target_url,event_types,enabled,api_version,environment,created_at`);await this.audit(tenantId,userId,'WEBHOOK_SUBSCRIPTION_CREATED','WEBHOOK_SUBSCRIPTION',(r.rows[0] as any).id);return{...r.rows[0],signingSecret:secret};}
 async terminalToken(tenantId:string,userId:string,locationId:string){const device=await db().execute(sql`select h.id,h.external_device_id,sc.stripe_account_id from hardware_integrations h join stripe_connections sc on sc.tenant_id=h.tenant_id where h.tenant_id=${tenantId}::uuid and h.location_id=${locationId}::uuid and h.provider='STRIPE_TERMINAL' and h.enabled=true and sc.charges_enabled=true limit 1`);const row=device.rows[0] as any;if(!row)throw fail(409,'TERMINAL_NOT_CONFIGURED','No enabled Stripe Terminal device is assigned to this location');const token=await getStripeClient().terminal.connectionTokens.create({}, {stripeAccount:row.stripe_account_id});await this.audit(tenantId,userId,'TERMINAL_CONNECTION_TOKEN_CREATED','HARDWARE_INTEGRATION',row.id);return{secret:token.secret};}
 async authenticateApiKey(value:string,scope:string){const r=await db().execute(sql`update api_credentials set last_used_at=now() where key_hash=${hashSecret(value)} and revoked_at is null and (expires_at is null or expires_at>now()) and ${scope}=any(scopes) returning id,tenant_id,scopes,rate_limit_tier`);if(!r.rows[0])throw fail(401,'API_KEY_INVALID','API credential is invalid or lacks the required scope');return r.rows[0] as any;}
 private async audit(tenantId:string,userId:string,action:string,targetType:string,targetId:string){await db().execute(sql`insert into platform_audit_events(tenant_id,action,target_type,target_id,outcome,event_category,description,environment,source_component,metadata) values(${tenantId}::uuid,${action},${targetType},${targetId},'SUCCESS','INTEGRATION',${action.replaceAll('_',' ').toLowerCase()},${process.env.NODE_ENV||'development'},'integrations',jsonb_build_object('tenantUserId',${userId}))`);}
}
