import { createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual } from 'node:crypto';
import { isIP } from 'node:net';
import { lookup } from 'node:dns/promises';

const key=()=>{const raw=process.env.INTEGRATION_ENCRYPTION_KEY||'';const value=/^[a-f\d]{64}$/i.test(raw)?Buffer.from(raw,'hex'):Buffer.from(raw,'base64');if(value.length!==32)throw Object.assign(new Error('Integration encryption is not configured.'),{statusCode:503,code:'INTEGRATION_ENCRYPTION_UNAVAILABLE'});return value;};
export function encryptSecret(value:unknown){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return ['v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),body.toString('base64url')].join('.');}
export function decryptSecret<T>(value:string):T{const[v,iv,tag,body]=value.split('.');if(v!=='v1'||!iv||!tag||!body)throw new Error('Invalid encrypted payload');const decipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(body,'base64url')),decipher.final()]).toString('utf8'));}
export const hashSecret=(value:string)=>createHash('sha256').update(value).digest('hex');
export const issueOpaqueSecret=(prefix:string)=>`${prefix}_${randomBytes(32).toString('base64url')}`;
export function signState(payload:Record<string,unknown>,ttlSeconds=600){const body=Buffer.from(JSON.stringify({...payload,exp:Math.floor(Date.now()/1000)+ttlSeconds})).toString('base64url');const sig=createHmac('sha256',key()).update(body).digest('base64url');return `${body}.${sig}`;}
export function verifyState<T>(state:string):T{const[body,sig]=state.split('.');if(!body||!sig)throw new Error('Invalid OAuth state');const expected=createHmac('sha256',key()).update(body).digest();const actual=Buffer.from(sig,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new Error('Invalid OAuth state');const parsed=JSON.parse(Buffer.from(body,'base64url').toString()) as any;if(parsed.exp<Math.floor(Date.now()/1000))throw new Error('Expired OAuth state');return parsed;}
const privateIp=(ip:string)=>ip==='::1'||ip.startsWith('fc')||ip.startsWith('fd')||ip.startsWith('fe80:')||/^127\.|^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\./.test(ip);
export async function validateWebhookUrl(value:string,production=process.env.NODE_ENV==='production'){const url=new URL(value);if(url.username||url.password||url.port&&!['443',''].includes(url.port))throw new Error('Webhook URL contains forbidden authority details');if(production&&url.protocol!=='https:')throw new Error('Webhook URL must use HTTPS');if(!['https:',...(production?[]:['http:'])].includes(url.protocol))throw new Error('Webhook protocol is not supported');if(isIP(url.hostname)&&privateIp(url.hostname))throw new Error('Private webhook targets are forbidden');const resolved=await lookup(url.hostname,{all:true});if(!resolved.length||resolved.some(x=>privateIp(x.address)))throw new Error('Webhook target resolves to a private address');return{url:url.toString(),host:url.hostname.toLowerCase()};}
export function webhookSignature(secret:string,timestamp:number,body:string){return createHmac('sha256',secret).update(`${timestamp}.${body}`).digest('hex');}
