import { and, desc, eq, getTableColumns, lt, sql } from 'drizzle-orm';
import { appointments, automationActionRuns, emailOutbox, getDatabase, operationsIssues, smsOutbox, users } from '@ks-os/database';
import type { OperationsIssueListQuery } from '@ks-os/contracts';
import { AutomationService } from '../automations/automation.service.js';

export type OperationsActor={tenantId:string;userId:string;role:'owner'|'staff'};
const hiddenForStaff=['PAYMENT','REFUND','STRIPE','PAYOUT','DISPUTE','AUTOMATION','TEAM','SYSTEM'];
const iso=(value:Date|string|null)=>value?new Date(value).toISOString():null;
const serialize=(row:any)=>({id:row.id,tenantId:row.tenantId,category:row.category,issueType:row.issueType,severity:row.severity,status:row.status,title:row.title,message:row.message,sourceType:row.sourceType,sourceId:row.sourceId,deduplicationKey:row.deduplicationKey,occurrenceCount:row.occurrenceCount,relatedAppointmentId:row.relatedAppointmentId,actionDeadline:iso(row.actionDeadline),metadata:row.metadataJson??{},assignedToUserId:row.assignedToUserId,acknowledgedByUserId:row.acknowledgedByUserId,resolvedByUserId:row.resolvedByUserId,occurredAt:iso(row.occurredAt),lastOccurredAt:iso(row.lastOccurredAt),acknowledgedAt:iso(row.acknowledgedAt),resolvedAt:iso(row.resolvedAt),dismissedAt:iso(row.dismissedAt),createdAt:iso(row.createdAt),updatedAt:iso(row.updatedAt)});
export class OperationsService {private db=getDatabase();
  private filters(actor:OperationsActor,query:Partial<OperationsIssueListQuery>={}){const conditions:any[]=[eq(operationsIssues.tenantId,actor.tenantId)];if(query.status)conditions.push(eq(operationsIssues.status,query.status));if(query.category)conditions.push(eq(operationsIssues.category,query.category));if(query.severity)conditions.push(eq(operationsIssues.severity,query.severity));if(query.assignedTo)conditions.push(eq(operationsIssues.assignedToUserId,query.assignedTo));if(query.cursor)conditions.push(lt(operationsIssues.lastOccurredAt,new Date(query.cursor)));if(actor.role==='staff'){conditions.push(eq(appointments.userId,actor.userId));conditions.push(sql`${operationsIssues.category} NOT IN (${sql.join(hiddenForStaff.map(x=>sql`${x}`),sql`,`)})`);}return and(...conditions);}
  async list(actor:OperationsActor,query:OperationsIssueListQuery){const base=this.db.select(getTableColumns(operationsIssues)).from(operationsIssues);const joined=actor.role==='staff'?base.innerJoin(appointments,and(eq(appointments.id,operationsIssues.relatedAppointmentId),eq(appointments.tenantId,actor.tenantId))):base;const rows=await joined.where(this.filters(actor,query)).orderBy(desc(sql`CASE ${operationsIssues.severity} WHEN 'CRITICAL' THEN 3 WHEN 'WARNING' THEN 2 ELSE 1 END`),desc(operationsIssues.lastOccurredAt)).limit(query.limit+1);const page=rows.slice(0,query.limit);return{data:page.map(serialize),nextCursor:rows.length>query.limit?iso(page.at(-1)!.lastOccurredAt):null};}
  async get(actor:OperationsActor,id:string){const base=this.db.select(getTableColumns(operationsIssues)).from(operationsIssues);const joined=actor.role==='staff'?base.innerJoin(appointments,and(eq(appointments.id,operationsIssues.relatedAppointmentId),eq(appointments.tenantId,actor.tenantId))):base;const[issue]=await joined.where(and(this.filters(actor),eq(operationsIssues.id,id))).limit(1);if(!issue)throw Object.assign(new Error('Issue not found'),{statusCode:404,code:'OPERATIONS_ISSUE_NOT_FOUND'});return serialize(issue);}
  async summary(actor:OperationsActor){const selection={open:sql<number>`count(*) filter (where ${operationsIssues.status}='OPEN')::int`,acknowledged:sql<number>`count(*) filter (where ${operationsIssues.status}='ACKNOWLEDGED')::int`,critical:sql<number>`count(*) filter (where ${operationsIssues.status} in ('OPEN','ACKNOWLEDGED') and ${operationsIssues.severity}='CRITICAL')::int`,totalActionable:sql<number>`count(*) filter (where ${operationsIssues.status} in ('OPEN','ACKNOWLEDGED'))::int`};const base=this.db.select(selection).from(operationsIssues);const joined=actor.role==='staff'?base.innerJoin(appointments,and(eq(appointments.id,operationsIssues.relatedAppointmentId),eq(appointments.tenantId,actor.tenantId))):base;const[row]=await joined.where(this.filters(actor));return row??{open:0,acknowledged:0,critical:0,totalActionable:0};}
  private async mutate(actor:OperationsActor,id:string,set:Record<string,unknown>){await this.get(actor,id);const [row]=await this.db.update(operationsIssues).set({...set,updatedAt:new Date()}).where(and(eq(operationsIssues.id,id),eq(operationsIssues.tenantId,actor.tenantId))).returning();return serialize(row);}
  acknowledge(actor:OperationsActor,id:string){return this.mutate(actor,id,{status:'ACKNOWLEDGED',acknowledgedAt:new Date(),acknowledgedByUserId:actor.userId});}
  resolve(actor:OperationsActor,id:string){return this.mutate(actor,id,{status:'RESOLVED',resolvedAt:new Date(),resolvedByUserId:actor.userId});}
  dismiss(actor:OperationsActor,id:string){if(actor.role!=='owner')throw Object.assign(new Error('Owner access required'),{statusCode:403,code:'FORBIDDEN'});return this.mutate(actor,id,{status:'DISMISSED',dismissedAt:new Date()});}
  async assign(actor:OperationsActor,id:string,assignedToUserId:string|null){if(actor.role!=='owner')throw Object.assign(new Error('Owner access required'),{statusCode:403,code:'FORBIDDEN'});if(assignedToUserId){const [assignee]=await this.db.select({id:users.id}).from(users).where(and(eq(users.id,assignedToUserId),eq(users.tenantId,actor.tenantId),eq(users.accountStatus,'ACTIVE'))).limit(1);if(!assignee)throw Object.assign(new Error('Assignee is not an active tenant member'),{statusCode:400,code:'INVALID_ASSIGNEE'});}return this.mutate(actor,id,{assignedToUserId});}
  async retry(actor:OperationsActor,id:string){if(actor.role!=='owner')throw Object.assign(new Error('Owner access required'),{statusCode:403,code:'FORBIDDEN'});const issue=await this.get(actor,id);if(!['OPEN','ACKNOWLEDGED'].includes(issue.status))throw Object.assign(new Error('Only actionable issues can be retried'),{statusCode:409,code:'ISSUE_NOT_ACTIONABLE'});const now=new Date();if(issue.sourceType==='EMAIL_OUTBOX'){await this.db.update(emailOutbox).set({status:'PENDING',nextAttemptAt:now,failedAt:null,lastErrorCode:null}).where(and(eq(emailOutbox.id,issue.sourceId),eq(emailOutbox.tenantId,actor.tenantId)));return{accepted:true as const,status:'QUEUED' as const};}if(issue.sourceType==='SMS_OUTBOX'){await this.db.update(smsOutbox).set({status:'PENDING',nextAttemptAt:now,failedAt:null,lastErrorCode:null}).where(and(eq(smsOutbox.id,issue.sourceId),eq(smsOutbox.tenantId,actor.tenantId)));return{accepted:true as const,status:'QUEUED' as const};}if(issue.sourceType==='AUTOMATION_ACTION_RUN'){await new AutomationService().retry(actor,issue.sourceId);return{accepted:true as const,status:'QUEUED' as const};}throw Object.assign(new Error('This issue type has no safe retry operation'),{statusCode:409,code:'RETRY_NOT_SUPPORTED'});}
}
