import { and, inArray, lt } from 'drizzle-orm';
import { appointments, formAssignments, getDatabase, stripeConnections, stripeDisputes, stripePaymentAttempts, stripePayouts, stripeRefunds } from '@ks-os/database';
import { OperationsIssueReporter } from './operations.issue-service.js';

export class OperationsReconciliationService {private db=getDatabase();private issues=new OperationsIssueReporter();
 async run(){let reconciled=0;
  for(const row of await this.db.select().from(stripePaymentAttempts).limit(500)){const key=`PAYMENT_FAILED:${row.id}`;if(row.status==='FAILED'){await this.issues.report({tenantId:row.tenantId,category:'PAYMENT',issueType:'PAYMENT_FAILED',severity:'CRITICAL',title:'Payment failed',message:'A booking payment needs owner attention.',sourceType:'PAYMENT_ATTEMPT',sourceId:row.id,deduplicationKey:key,relatedAppointmentId:row.appointmentId,metadata:{failureCode:row.failureCode}});reconciled++;}else if(['SUCCEEDED','COMPLETED'].includes(row.status))await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(stripeRefunds).limit(500)){const key=`REFUND_FAILED:${row.id}`;if(row.status==='FAILED'){await this.issues.report({tenantId:row.tenantId,category:'REFUND',issueType:'REFUND_FAILED',severity:'CRITICAL',title:'Refund failed',message:'A refund could not be completed.',sourceType:'REFUND',sourceId:row.id,deduplicationKey:key,relatedAppointmentId:row.appointmentId,metadata:{failureCode:row.failureCode}});reconciled++;}else if(['SUCCEEDED','COMPLETED'].includes(row.status))await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(stripeConnections).limit(500)){const key=`STRIPE_ACTION_REQUIRED:${row.id}`;if(!row.chargesEnabled||!row.payoutsEnabled||row.connectionStatus!=='READY'){await this.issues.report({tenantId:row.tenantId,category:'STRIPE',issueType:'STRIPE_ACTION_REQUIRED',severity:row.disabledReason?'CRITICAL':'WARNING',title:'Stripe action required',message:'The salon Stripe connection is not fully ready.',sourceType:'STRIPE_CONNECTION',sourceId:row.id,deduplicationKey:key,metadata:{connectionStatus:row.connectionStatus,disabledReason:row.disabledReason}});reconciled++;}else await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(stripePayouts).limit(500)){const key=`PAYOUT_FAILED:${row.id}`;if(row.status==='failed'){await this.issues.report({tenantId:row.tenantId,category:'PAYOUT',issueType:'PAYOUT_FAILED',severity:'CRITICAL',title:'Payout failed',message:'A Stripe payout failed and needs owner attention.',sourceType:'PAYOUT',sourceId:row.id,deduplicationKey:key,metadata:{failureCode:row.failureCode}});reconciled++;}else if(row.status==='paid')await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(stripeDisputes).limit(500)){const key=`DISPUTE_EVIDENCE_REQUIRED:${row.id}`;if(row.hasEvidenceDue&&row.status!=='won'&&row.status!=='lost'){await this.issues.report({tenantId:row.tenantId,category:'DISPUTE',issueType:'DISPUTE_EVIDENCE_REQUIRED',severity:'CRITICAL',title:'Dispute evidence required',message:'A payment dispute has an evidence deadline.',sourceType:'DISPUTE',sourceId:row.id,deduplicationKey:key,relatedAppointmentId:row.appointmentId,actionDeadline:row.evidenceDueBy,metadata:{reason:row.reason,status:row.status}});reconciled++;}else await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(formAssignments).limit(500)){const key=`FORM_OVERDUE:${row.id}`;if(['PENDING','OPENED'].includes(row.status)&&row.expiresAt<new Date()){await this.issues.report({tenantId:row.tenantId,category:'FORM',issueType:'FORM_OVERDUE',severity:'WARNING',title:'Client form overdue',message:'A required client form was not completed before its deadline.',sourceType:'FORM_ASSIGNMENT',sourceId:row.id,deduplicationKey:key,relatedAppointmentId:row.appointmentId,actionDeadline:row.expiresAt,metadata:{formId:row.formId}});reconciled++;}else await this.issues.resolve(row.tenantId,key);}
  for(const row of await this.db.select().from(appointments).limit(500)){const key=`APPOINTMENT_PAYMENT_REQUIRED:${row.id}`;if(row.status==='AWAITING_PAYMENT'){await this.issues.report({tenantId:row.tenantId,category:'APPOINTMENT',issueType:'APPOINTMENT_PAYMENT_REQUIRED',severity:'WARNING',title:'Appointment awaiting payment',message:'An appointment is still awaiting payment.',sourceType:'APPOINTMENT',sourceId:row.id,deduplicationKey:key,relatedAppointmentId:row.id,metadata:{paymentStatus:row.paymentStatus}});reconciled++;}else await this.issues.resolve(row.tenantId,key);}
  return{reconciled};
 }
}
