import { sql, type SQL } from 'drizzle-orm';
import { getDatabase } from '@ks-os/database';
import type {
  AppointmentsReportQuery, ClientsReportQuery, CommunicationsReportQuery, FormsReportQuery, PaymentsReportQuery,
  ProductsReportQuery, RefundsReportQuery, ServicesReportQuery, StaffReportQuery, StockReportQuery,
} from '@ks-os/contracts';
import type { AnalyticsPeriod } from '../analytics/analytics.period.js';
import { decodeReportCursor, deriveReportPaymentState, mapReportPaymentSource, reportIso, reportNumber, reportPagination, reportPeriodMeta } from './reports.utils.js';

type TenantConfig = { timezone:string; currency:string };
type ReportContext = TenantConfig & { period:AnalyticsPeriod };
const generatedAt = () => new Date().toISOString();

const order = <T extends string>(value:T, choices:Record<T,SQL>) => choices[value];

export interface ReportsRepositoryLike {
  getTenantConfig(tenantId:string):Promise<TenantConfig|null>;
  appointments(tenantId:string,ctx:ReportContext,query:AppointmentsReportQuery):Promise<any>;
  clients(tenantId:string,ctx:ReportContext,query:ClientsReportQuery):Promise<any>;
  services(tenantId:string,ctx:ReportContext,query:ServicesReportQuery):Promise<any>;
  staff(tenantId:string,ctx:ReportContext,query:StaffReportQuery):Promise<any>;
  products(tenantId:string,ctx:ReportContext,query:ProductsReportQuery):Promise<any>;
  stock(tenantId:string,ctx:TenantConfig,query:StockReportQuery):Promise<any>;
  payments(tenantId:string,ctx:ReportContext,query:PaymentsReportQuery):Promise<any>;
  refunds(tenantId:string,ctx:ReportContext,query:RefundsReportQuery):Promise<any>;
  forms(tenantId:string,ctx:ReportContext,query:FormsReportQuery):Promise<any>;
  communications(tenantId:string,ctx:ReportContext,query:CommunicationsReportQuery):Promise<any>;
}

export class ReportsRepository implements ReportsRepositoryLike {
  private get db(){return getDatabase();}

  async getTenantConfig(tenantId:string){
    const result=await this.db.execute(sql`select timezone,currency from tenants where id=${tenantId}::uuid limit 1`);
    const row=result.rows[0] as any;return row?{timezone:row.timezone,currency:row.currency}:null;
  }

  async appointments(tenantId:string,ctx:ReportContext,q:AppointmentsReportQuery){
    const offset=decodeReportCursor(q.cursor);const p=ctx.period;
    const where=sql`a.tenant_id=${tenantId}::uuid and a.start_time>=${p.from.toISOString()}::timestamptz and a.start_time<${p.to.toISOString()}::timestamptz and a.status<>'BLOCKED'
      and (${q.status??null}::text is null or a.status=${q.status??null})
      and (${q.staffId??null}::uuid is null or a.user_id=${q.staffId??null}::uuid)
      and (${q.serviceId??null}::uuid is null or a.service_id=${q.serviceId??null}::uuid)
      and (${q.clientId??null}::uuid is null or a.client_id=${q.clientId??null}::uuid)
      and (${q.bookingChannel??null}::text is null or a.booking_channel=${q.bookingChannel??null})
      and (${q.paymentStatus??null}::text is null or a.payment_status=${q.paymentStatus??null})
      and (${q.search??null}::text is null or coalesce(c.name,a.client_name,'') ilike ${`%${q.search??''}%`} or coalesce(s.name,'') ilike ${`%${q.search??''}%`} or a.public_reference::text ilike ${`%${q.search??''}%`})`;
    const sort=order(q.sort,{date_desc:sql`a.start_time desc,a.id desc`,date_asc:sql`a.start_time asc,a.id asc`,created_desc:sql`a.created_at desc,a.id desc`,amount_desc:sql`a.quoted_amount desc,a.id desc`});
    const [summaryResult,rowResult]=await Promise.all([
      this.db.execute(sql`select count(*)::int total,count(*) filter(where a.status='COMPLETED')::int completed,count(*) filter(where a.status='CANCELLED')::int cancelled,count(*) filter(where a.status='NO_SHOW')::int no_show,count(*) filter(where a.status='AWAITING_PAYMENT')::int awaiting_payment,coalesce(sum(a.quoted_amount),0)::int quoted_total from appointments a left join clients c on c.id=a.client_id and c.tenant_id=a.tenant_id left join services s on s.id=a.service_id and s.tenant_id=a.tenant_id where ${where}`),
      this.db.execute(sql`select a.id,a.public_reference,a.start_time,a.end_time,a.client_id,coalesce(c.name,a.client_name) client_name,a.service_id,s.name service_name,a.user_id,u.name staff_name,a.status,a.booking_channel,a.quoted_amount,a.payment_status,a.created_at from appointments a left join clients c on c.id=a.client_id and c.tenant_id=a.tenant_id left join services s on s.id=a.service_id and s.tenant_id=a.tenant_id join users u on u.id=a.user_id and u.tenant_id=a.tenant_id where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`),
    ]);
    const s=(summaryResult.rows[0]??{}) as any;const paged=reportPagination(rowResult.rows as any[],q.limit,offset);
    return{period:reportPeriodMeta(p),currency:ctx.currency,filters:{search:q.search??null,status:q.status??null,staffId:q.staffId??null,serviceId:q.serviceId??null,clientId:q.clientId??null,bookingChannel:q.bookingChannel??null,paymentStatus:q.paymentStatus??null,sort:q.sort},summary:{total:reportNumber(s.total),completed:reportNumber(s.completed),cancelled:reportNumber(s.cancelled),noShow:reportNumber(s.no_show),awaitingPayment:reportNumber(s.awaiting_payment),quotedAmountTotal:reportNumber(s.quoted_total)},rows:paged.rows.map((r:any)=>({appointmentId:r.id,publicReference:r.public_reference,startTime:reportIso(r.start_time)!,endTime:reportIso(r.end_time)!,clientId:r.client_id,clientDisplayName:r.client_name,serviceId:r.service_id,serviceName:r.service_name,staffId:r.user_id,staffName:r.staff_name,status:r.status,bookingChannel:r.booking_channel,quotedAmount:reportNumber(r.quoted_amount),paymentState:r.payment_status,createdAt:reportIso(r.created_at)!})),pagination:paged.pagination,generatedAt:generatedAt()};
  }

  private clientsCte(tenantId:string,ctx:ReportContext,q:ClientsReportQuery){const p=ctx.period;return sql`
    with period_stats as (select client_id,count(*) filter(where status='COMPLETED')::int completed_count,count(*) filter(where status='CANCELLED')::int cancelled_count,count(*) filter(where status='NO_SHOW')::int no_show_count from appointments where tenant_id=${tenantId}::uuid and client_id is not null and start_time>=${p.from.toISOString()}::timestamptz and start_time<${p.to.toISOString()}::timestamptz and status in ('CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED','CANCELLED','NO_SHOW') group by client_id),
    history as (select client_id,min(start_time) filter(where status in ('CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED','CANCELLED','NO_SHOW')) first_at,max(start_time) filter(where status in ('CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED','CANCELLED','NO_SHOW')) last_at,max(start_time) filter(where status='COMPLETED' and start_time<=now()) last_completed from appointments where tenant_id=${tenantId}::uuid and client_id is not null group by client_id),
    spend as (select a.client_id,coalesce(sum(ct.total_amount) filter(where ct.payment_status in ('SUCCEEDED','REFUNDED')),0)::int recorded_spend from checkout_transactions ct join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id where ct.tenant_id=${tenantId}::uuid and ct.created_at>=${p.from.toISOString()}::timestamptz and ct.created_at<${p.to.toISOString()}::timestamptz group by a.client_id),
    future as (select client_id,count(*) filter(where status in ('PENDING','CONFIRMED','CHECKED_IN'))::int future_count from appointments where tenant_id=${tenantId}::uuid and client_id is not null and start_time>=now() group by client_id),
    base as (select c.id,c.name,h.first_at,h.last_at,h.last_completed,ps.completed_count,ps.cancelled_count,ps.no_show_count,coalesce(sp.recorded_spend,0)::int recorded_spend,coalesce(f.future_count,0)::int future_count,case when h.first_at<${p.from.toISOString()}::timestamptz then 'RETURNING' else 'NEW' end client_type from period_stats ps join clients c on c.id=ps.client_id and c.tenant_id=${tenantId}::uuid join history h on h.client_id=c.id left join spend sp on sp.client_id=c.id left join future f on f.client_id=c.id)
    `;}

  async clients(tenantId:string,ctx:ReportContext,q:ClientsReportQuery){
    const offset=decodeReportCursor(q.cursor);const p=ctx.period;const cte=this.clientsCte(tenantId,ctx,q);
    const where=sql`(${q.search??null}::text is null or name ilike ${`%${q.search??''}%`}) and (${q.newOrReturning??null}::text is null or client_type=${q.newOrReturning??null}) and (
      ${q.lastVisitRange??null}::text is null or (${q.lastVisitRange??null}='LAST_30_DAYS' and last_completed>=now()-interval '30 days') or (${q.lastVisitRange??null}='LAST_90_DAYS' and last_completed>=now()-interval '90 days') or (${q.lastVisitRange??null}='OVER_90_DAYS' and last_completed<now()-interval '90 days') or (${q.lastVisitRange??null}='NEVER' and last_completed is null))`;
    const sort=order(q.sort,{last_visit_desc:sql`last_at desc nulls last,id desc`,name_asc:sql`name asc,id asc`,spend_desc:sql`recorded_spend desc,id desc`,appointments_desc:sql`(completed_count+cancelled_count+no_show_count) desc,id desc`});
    const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total_clients,count(*) filter(where client_type='NEW')::int new_clients,count(*) filter(where client_type='RETURNING')::int returning_clients,coalesce(sum(recorded_spend),0)::int recorded_spend from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);
    const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(p),currency:ctx.currency,filters:{search:q.search??null,newOrReturning:q.newOrReturning??null,lastVisitRange:q.lastVisitRange??null,sort:q.sort},summary:{totalClients:reportNumber(s.total_clients),newClients:reportNumber(s.new_clients),returningClients:reportNumber(s.returning_clients),recordedSpend:reportNumber(s.recorded_spend)},rows:paged.rows.map((r:any)=>({clientId:r.id,name:r.name,firstAppointmentAt:reportIso(r.first_at),lastAppointmentAt:reportIso(r.last_at),completedAppointmentCount:reportNumber(r.completed_count),cancelledCount:reportNumber(r.cancelled_count),noShowCount:reportNumber(r.no_show_count),recordedSpend:reportNumber(r.recorded_spend),futureAppointmentCount:reportNumber(r.future_count),clientType:r.client_type})),pagination:paged.pagination,generatedAt:generatedAt()};
  }

  private servicesCte(tenantId:string,ctx:ReportContext){const p=ctx.period;return sql`with activity as (select service_id,count(*) filter(where status<>'BLOCKED')::int bookings,count(*) filter(where status='COMPLETED')::int completed,count(*) filter(where status='CANCELLED')::int cancelled,count(*) filter(where status='NO_SHOW')::int no_shows,count(distinct client_id) filter(where client_id is not null)::int unique_clients from appointments where tenant_id=${tenantId}::uuid and service_id is not null and start_time>=${p.from.toISOString()}::timestamptz and start_time<${p.to.toISOString()}::timestamptz group by service_id),revenue as (select a.service_id,coalesce(sum(ct.total_amount) filter(where ct.payment_status in ('SUCCEEDED','REFUNDED')),0)::int recorded_revenue,count(*) filter(where ct.payment_status in ('SUCCEEDED','REFUNDED'))::int transaction_count from checkout_transactions ct join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id where ct.tenant_id=${tenantId}::uuid and ct.created_at>=${p.from.toISOString()}::timestamptz and ct.created_at<${p.to.toISOString()}::timestamptz group by a.service_id),base as (select s.id,s.name,a.bookings,a.completed,a.cancelled,a.no_shows,a.unique_clients,coalesce(r.recorded_revenue,0)::int recorded_revenue,coalesce(r.transaction_count,0)::int transaction_count from activity a join services s on s.id=a.service_id and s.tenant_id=${tenantId}::uuid left join revenue r on r.service_id=s.id)`;}
  async services(tenantId:string,ctx:ReportContext,q:ServicesReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.servicesCte(tenantId,ctx);const where=sql`(${q.search??null}::text is null or name ilike ${`%${q.search??''}%`}) and (${q.serviceId??null}::uuid is null or id=${q.serviceId??null}::uuid)`;const sort=order(q.sort,{bookings_desc:sql`bookings desc,id desc`,revenue_desc:sql`recorded_revenue desc,id desc`,name_asc:sql`name asc,id asc`,completed_desc:sql`completed desc,id desc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total_services,coalesce(sum(bookings),0)::int bookings,coalesce(sum(completed),0)::int completed,coalesce(sum(recorded_revenue),0)::int revenue from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{search:q.search??null,serviceId:q.serviceId??null,sort:q.sort},summary:{totalServices:reportNumber(s.total_services),bookings:reportNumber(s.bookings),completed:reportNumber(s.completed),recordedRevenue:reportNumber(s.revenue)},rows:paged.rows.map((r:any)=>({serviceId:r.id,serviceName:r.name,bookings:reportNumber(r.bookings),completed:reportNumber(r.completed),cancelled:reportNumber(r.cancelled),noShows:reportNumber(r.no_shows),recordedRevenue:reportNumber(r.recorded_revenue),averageRecordedTransaction:reportNumber(r.transaction_count)>0?Math.round(reportNumber(r.recorded_revenue)/reportNumber(r.transaction_count)):0,uniqueClients:reportNumber(r.unique_clients),rebookingIndicator:null})),pagination:paged.pagination,generatedAt:generatedAt()};}

  private staffCte(tenantId:string,ctx:ReportContext){const p=ctx.period;return sql`with days as (select generate_series(${p.localFrom}::date,${p.localTo}::date,'1 day')::date as calendar_date),availability as (select ss.user_id,round(sum(extract(epoch from ((d.calendar_date+ss.end_time::time)-(d.calendar_date+ss.start_time::time)))/60))::int scheduled_minutes from staff_schedules ss join days d on extract(dow from d.calendar_date)=ss.day_of_week where ss.tenant_id=${tenantId}::uuid group by ss.user_id),activity as (select user_id,round(coalesce(sum(extract(epoch from(end_time-start_time))/60) filter(where status in ('CONFIRMED','CHECKED_IN','IN_SERVICE','AWAITING_PAYMENT','COMPLETED')),0))::int booked_minutes,count(*) filter(where status='COMPLETED')::int completed,count(*) filter(where status='CANCELLED')::int cancelled,count(*) filter(where status='NO_SHOW')::int no_shows,count(distinct client_id) filter(where client_id is not null)::int unique_clients from appointments where tenant_id=${tenantId}::uuid and start_time>=${p.from.toISOString()}::timestamptz and start_time<${p.to.toISOString()}::timestamptz group by user_id),revenue as (select a.user_id,coalesce(sum(ct.total_amount) filter(where ct.payment_status in ('SUCCEEDED','REFUNDED')),0)::int recorded_revenue from checkout_transactions ct join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id where ct.tenant_id=${tenantId}::uuid and ct.created_at>=${p.from.toISOString()}::timestamptz and ct.created_at<${p.to.toISOString()}::timestamptz group by a.user_id),base as (select u.id,u.name,coalesce(to_jsonb(u)->>'account_status','ACTIVE') account_status,av.scheduled_minutes,coalesce(ac.booked_minutes,0)::int booked_minutes,coalesce(ac.completed,0)::int completed,coalesce(ac.cancelled,0)::int cancelled,coalesce(ac.no_shows,0)::int no_shows,coalesce(ac.unique_clients,0)::int unique_clients,coalesce(r.recorded_revenue,0)::int recorded_revenue,case when av.scheduled_minutes>0 then round((coalesce(ac.booked_minutes,0)::numeric/av.scheduled_minutes)*100,1) else null end utilisation from users u left join availability av on av.user_id=u.id left join activity ac on ac.user_id=u.id left join revenue r on r.user_id=u.id where u.tenant_id=${tenantId}::uuid and u.role in ('owner','staff'))`;}
  async staff(tenantId:string,ctx:ReportContext,q:StaffReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.staffCte(tenantId,ctx);const where=sql`(${q.search??null}::text is null or name ilike ${`%${q.search??''}%`}) and (${q.staffId??null}::uuid is null or id=${q.staffId??null}::uuid) and (${q.accountStatus??null}::text is null or account_status=${q.accountStatus??null})`;const sort=order(q.sort,{booked_desc:sql`booked_minutes desc,id desc`,utilisation_desc:sql`utilisation desc nulls last,id desc`,revenue_desc:sql`recorded_revenue desc,id desc`,name_asc:sql`name asc,id asc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total_staff,coalesce(sum(scheduled_minutes),0)::int scheduled,coalesce(sum(booked_minutes),0)::int booked,coalesce(sum(completed),0)::int completed,coalesce(sum(recorded_revenue),0)::int revenue from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{search:q.search??null,staffId:q.staffId??null,accountStatus:q.accountStatus??null,sort:q.sort},summary:{totalStaff:reportNumber(s.total_staff),scheduledMinutes:reportNumber(s.scheduled),bookedMinutes:reportNumber(s.booked),completedAppointments:reportNumber(s.completed),recordedRevenue:reportNumber(s.revenue)},rows:paged.rows.map((r:any)=>({staffId:r.id,staffName:r.name,accountStatus:r.account_status,scheduledMinutes:r.scheduled_minutes==null?null:reportNumber(r.scheduled_minutes),bookedMinutes:reportNumber(r.booked_minutes),completedAppointments:reportNumber(r.completed),cancelledAppointments:reportNumber(r.cancelled),noShows:reportNumber(r.no_shows),recordedRevenue:reportNumber(r.recorded_revenue),uniqueClients:reportNumber(r.unique_clients),utilisationPercentage:r.utilisation==null?null:Number(r.utilisation)})),pagination:paged.pagination,generatedAt:generatedAt()};}

  private productsCte(tenantId:string,ctx?:ReportContext){const period=ctx?.period;return sql`with sale_lines as (select ct.id transaction_id,ct.created_at,item->>'productId' product_id,case when item->>'quantity'~'^[0-9]+$' then (item->>'quantity')::int else 0 end quantity from checkout_transactions ct cross join lateral jsonb_array_elements(case when jsonb_typeof(ct.purchased_products)='array' then ct.purchased_products else '[]'::jsonb end) item where ct.tenant_id=${tenantId}::uuid and ct.payment_status in ('SUCCEEDED','REFUNDED') ${period?sql`and ct.created_at>=${period.from.toISOString()}::timestamptz and ct.created_at<${period.to.toISOString()}::timestamptz`:sql``}),sales as (select product_id,coalesce(sum(quantity),0)::int quantity_sold,count(distinct transaction_id)::int transaction_count,max(created_at) last_sale_at from sale_lines group by product_id),base as (select p.id,p.name,p.sku,p.stock_quantity,coalesce(s.quantity_sold,0)::int quantity_sold,coalesce(s.transaction_count,0)::int transaction_count,s.last_sale_at from products p left join sales s on s.product_id=p.id::text where p.tenant_id=${tenantId}::uuid)`;}
  async products(tenantId:string,ctx:ReportContext,q:ProductsReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.productsCte(tenantId,ctx);const where=sql`(${q.search??null}::text is null or name ilike ${`%${q.search??''}%`} or sku ilike ${`%${q.search??''}%`})`;const sort=order(q.sort,{quantity_desc:sql`quantity_sold desc,id desc`,sales_desc:sql`quantity_sold desc,id desc`,name_asc:sql`name asc,id asc`,stock_asc:sql`stock_quantity asc,id asc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total_products,count(*) filter(where quantity_sold>0)::int products_sold,coalesce(sum(quantity_sold),0)::int quantity_sold from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{search:q.search??null,sort:q.sort},summary:{totalProducts:reportNumber(s.total_products),productsSold:reportNumber(s.products_sold),quantitySold:reportNumber(s.quantity_sold),grossRecordedSales:null},rows:paged.rows.map((r:any)=>({productId:r.id,name:r.name,sku:r.sku,quantitySold:reportNumber(r.quantity_sold),grossRecordedSales:null,transactionCount:reportNumber(r.transaction_count),currentStock:reportNumber(r.stock_quantity),lastSaleAt:reportIso(r.last_sale_at)})),pagination:paged.pagination,generatedAt:generatedAt()};}

  async stock(tenantId:string,ctx:TenantConfig,q:StockReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.productsCte(tenantId);const where=sql`(${q.search??null}::text is null or name ilike ${`%${q.search??''}%`} or sku ilike ${`%${q.search??''}%`}) and (${q.status??null}::text is null or (${q.status??null}='OUT_OF_STOCK' and stock_quantity<=0) or (${q.status??null}='LOW_STOCK' and stock_quantity between 1 and 5) or (${q.status??null}='IN_STOCK' and stock_quantity>5))`;const sort=order(q.sort,{quantity_asc:sql`stock_quantity asc,id asc`,quantity_desc:sql`stock_quantity desc,id desc`,name_asc:sql`name asc,id asc`,last_sale_desc:sql`last_sale_at desc nulls last,id desc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total_products,count(*) filter(where stock_quantity>5)::int in_stock,count(*) filter(where stock_quantity between 1 and 5)::int low_stock,count(*) filter(where stock_quantity<=0)::int out_stock from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{currency:ctx.currency,asOf:generatedAt(),filters:{search:q.search??null,status:q.status??null,sort:q.sort},summary:{totalProducts:reportNumber(s.total_products),inStock:reportNumber(s.in_stock),lowStock:reportNumber(s.low_stock),outOfStock:reportNumber(s.out_stock)},rows:paged.rows.map((r:any)=>({productId:r.id,name:r.name,sku:r.sku,currentQuantity:reportNumber(r.stock_quantity),lowStock:reportNumber(r.stock_quantity)>0&&reportNumber(r.stock_quantity)<=5,outOfStock:reportNumber(r.stock_quantity)<=0,lastSaleAt:reportIso(r.last_sale_at)})),pagination:paged.pagination,generatedAt:generatedAt()};}

  private paymentsCte(tenantId:string,ctx:ReportContext){const p=ctx.period;return sql`with refunds as (select checkout_transaction_id,coalesce(sum(amount) filter(where status='SUCCEEDED'),0)::int refunded_amount from stripe_refunds where tenant_id=${tenantId}::uuid group by checkout_transaction_id),base as (select ct.id,ct.created_at,ct.appointment_id,a.public_reference,coalesce(c.name,a.client_name) client_name,s.name service_name,ct.payment_method,ct.purpose,ct.total_amount,ct.payment_status,coalesce(r.refunded_amount,0)::int refunded_amount,case when ct.payment_method='CARD' and ct.purpose='booking_payment' then 'STRIPE_ONLINE' when ct.payment_method='CASH' then 'MANUAL_CASH' when ct.payment_method='SPLIT' then 'MANUAL_SPLIT' else 'EXTERNAL_TERMINAL' end source,case when ct.payment_status='FAILED' then 'FAILED' when ct.payment_status='PENDING' then 'PENDING' when ct.payment_status='REFUNDED' or (coalesce(r.refunded_amount,0)>=ct.total_amount and ct.total_amount>0) then 'REFUNDED' when coalesce(r.refunded_amount,0)>0 then 'PARTIALLY_REFUNDED' else 'SUCCEEDED' end derived_status from checkout_transactions ct left join appointments a on a.id=ct.appointment_id and a.tenant_id=ct.tenant_id left join clients c on c.id=a.client_id and c.tenant_id=ct.tenant_id left join services s on s.id=a.service_id and s.tenant_id=ct.tenant_id left join refunds r on r.checkout_transaction_id=ct.id where ct.tenant_id=${tenantId}::uuid and ct.created_at>=${p.from.toISOString()}::timestamptz and ct.created_at<${p.to.toISOString()}::timestamptz)`;}
  async payments(tenantId:string,ctx:ReportContext,q:PaymentsReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.paymentsCte(tenantId,ctx);const where=sql`(${q.search??null}::text is null or coalesce(client_name,'') ilike ${`%${q.search??''}%`} or coalesce(service_name,'') ilike ${`%${q.search??''}%`} or coalesce(public_reference::text,'') ilike ${`%${q.search??''}%`}) and (${q.source??null}::text is null or source=${q.source??null}) and (${q.method??null}::text is null or payment_method=${q.method??null}) and (${q.status??null}::text is null or derived_status=${q.status??null})`;const sort=order(q.sort,{date_desc:sql`created_at desc,id desc`,date_asc:sql`created_at asc,id asc`,amount_desc:sql`total_amount desc,id desc`,net_desc:sql`(total_amount-refunded_amount) desc,id desc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total,count(*) filter(where derived_status in ('SUCCEEDED','PARTIALLY_REFUNDED','REFUNDED'))::int succeeded,count(*) filter(where derived_status='FAILED')::int failed,coalesce(sum(total_amount),0)::int gross,coalesce(sum(refunded_amount),0)::int refunded,coalesce(sum(total_amount-refunded_amount),0)::int net from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{search:q.search??null,source:q.source??null,method:q.method??null,status:q.status??null,sort:q.sort},summary:{totalTransactions:reportNumber(s.total),succeeded:reportNumber(s.succeeded),failed:reportNumber(s.failed),grossAmount:reportNumber(s.gross),refundedAmount:reportNumber(s.refunded),netAmount:reportNumber(s.net)},rows:paged.rows.map((r:any)=>({transactionId:r.id,date:reportIso(r.created_at)!,appointmentId:r.appointment_id,bookingReference:r.public_reference,clientDisplayName:r.client_name,serviceName:r.service_name,source:mapReportPaymentSource(r.payment_method,r.purpose),method:r.payment_method,grossAmount:reportNumber(r.total_amount),refundedAmount:reportNumber(r.refunded_amount),netAmount:reportNumber(r.total_amount)-reportNumber(r.refunded_amount),status:deriveReportPaymentState(r.payment_status,reportNumber(r.refunded_amount),reportNumber(r.total_amount))})),pagination:paged.pagination,generatedAt:generatedAt()};}

  async refunds(tenantId:string,ctx:ReportContext,q:RefundsReportQuery){const offset=decodeReportCursor(q.cursor);const p=ctx.period;const where=sql`r.tenant_id=${tenantId}::uuid and r.created_at>=${p.from.toISOString()}::timestamptz and r.created_at<${p.to.toISOString()}::timestamptz and (${q.status??null}::text is null or r.status=${q.status??null}) and (${q.source??null}::text is null or r.refund_source=${q.source??null}) and (${q.search??null}::text is null or coalesce(a.public_reference::text,'') ilike ${`%${q.search??''}%`} or r.id::text ilike ${`%${q.search??''}%`})`;const sort=order(q.sort,{requested_desc:sql`r.created_at desc,r.id desc`,completed_desc:sql`r.completed_at desc nulls last,r.id desc`,amount_desc:sql`r.amount desc,r.id desc`});const [sr,rr]=await Promise.all([this.db.execute(sql`select count(*)::int total,coalesce(sum(r.amount),0)::int requested,coalesce(sum(r.amount) filter(where r.status='SUCCEEDED'),0)::int completed,count(*) filter(where r.status='FAILED')::int failed from stripe_refunds r left join appointments a on a.id=r.appointment_id and a.tenant_id=r.tenant_id where ${where}`),this.db.execute(sql`select r.id,r.checkout_transaction_id,a.public_reference,r.created_at,r.completed_at,r.amount,r.currency,r.status,r.reason,r.refund_source,u.name requested_by from stripe_refunds r left join appointments a on a.id=r.appointment_id and a.tenant_id=r.tenant_id left join users u on u.id=r.requested_by_user_id and u.tenant_id=r.tenant_id where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(p),currency:ctx.currency,filters:{search:q.search??null,status:q.status??null,source:q.source??null,sort:q.sort},summary:{totalRefunds:reportNumber(s.total),requestedAmount:reportNumber(s.requested),completedAmount:reportNumber(s.completed),failed:reportNumber(s.failed)},rows:paged.rows.map((r:any)=>({refundId:r.id,transactionId:r.checkout_transaction_id,bookingReference:r.public_reference,dateRequested:reportIso(r.created_at)!,dateCompleted:reportIso(r.completed_at),amount:reportNumber(r.amount),currency:r.currency,status:r.status,reason:r.reason,source:r.refund_source,requestedBy:r.requested_by})),pagination:paged.pagination,generatedAt:generatedAt()};}

  private formsCte(tenantId:string,ctx:ReportContext){const p=ctx.period;return sql`with base as (select fa.id,fa.form_id,fv.title_snapshot,fv.version_number,fa.client_id,c.name client_name,fa.appointment_id,a.public_reference,fa.created_at,fa.opened_at,fa.submitted_at,case when fa.status in ('PENDING','OPENED') and fa.expires_at<=now() then 'EXPIRED' else fa.status end derived_status,assigner.name assigned_by,a.user_id staff_id,a.service_id from form_assignments fa join form_versions fv on fv.id=fa.form_version_id and fv.tenant_id=fa.tenant_id join clients c on c.id=fa.client_id and c.tenant_id=fa.tenant_id join users assigner on assigner.id=fa.assigned_by_user_id and assigner.tenant_id=fa.tenant_id left join appointments a on a.id=fa.appointment_id and a.tenant_id=fa.tenant_id where fa.tenant_id=${tenantId}::uuid and coalesce(a.start_time,fa.created_at)>=${p.from.toISOString()}::timestamptz and coalesce(a.start_time,fa.created_at)<${p.to.toISOString()}::timestamptz)`;}
  async forms(tenantId:string,ctx:ReportContext,q:FormsReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.formsCte(tenantId,ctx);const where=sql`(${q.search??null}::text is null or title_snapshot ilike ${`%${q.search??''}%`} or client_name ilike ${`%${q.search??''}%`} or coalesce(public_reference::text,'') ilike ${`%${q.search??''}%`}) and (${q.status??null}::text is null or derived_status=${q.status??null}) and (${q.templateId??null}::uuid is null or form_id=${q.templateId??null}::uuid) and (${q.versionId??null}::uuid is null or id in (select id from form_assignments where form_version_id=${q.versionId??null}::uuid and tenant_id=${tenantId}::uuid)) and (${q.staffId??null}::uuid is null or staff_id=${q.staffId??null}::uuid) and (${q.serviceId??null}::uuid is null or service_id=${q.serviceId??null}::uuid)`;const sort=order(q.sort,{assigned_desc:sql`created_at desc,id desc`,appointment_desc:sql`public_reference desc nulls last,id desc`,submitted_desc:sql`submitted_at desc nulls last,id desc`,title_asc:sql`title_snapshot asc,id asc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int assigned,count(*) filter(where derived_status='OPENED')::int opened,count(*) filter(where derived_status='SUBMITTED')::int submitted,count(*) filter(where derived_status='EXPIRED')::int expired,count(*) filter(where derived_status='CANCELLED')::int cancelled from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const assigned=reportNumber(s.assigned),submitted=reportNumber(s.submitted);const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{search:q.search??null,status:q.status??null,templateId:q.templateId??null,versionId:q.versionId??null,staffId:q.staffId??null,serviceId:q.serviceId??null,sort:q.sort},summary:{assigned,opened:reportNumber(s.opened),submitted,expired:reportNumber(s.expired),cancelled:reportNumber(s.cancelled),completionRate:assigned?Number(((submitted/assigned)*100).toFixed(1)):0},rows:paged.rows.map((r:any)=>({assignmentId:r.id,formId:r.form_id,formTitle:r.title_snapshot,formVersion:reportNumber(r.version_number),clientDisplayName:r.client_name,appointmentId:r.appointment_id,appointmentReference:r.public_reference,assignedAt:reportIso(r.created_at)!,openedAt:reportIso(r.opened_at),submittedAt:reportIso(r.submitted_at),status:r.derived_status,assignedBy:r.assigned_by})),pagination:paged.pagination,generatedAt:generatedAt()};}

  private communicationsCte(tenantId:string,ctx:ReportContext){const p=ctx.period;return sql`with base as (select e.id,'EMAIL'::text channel,e.template_key category,(left(e.recipient_email,1)||'***@'||split_part(e.recipient_email,'@',2)) masked_recipient,e.related_entity_type related_type,e.related_entity_id related_id,e.created_at queued_at,e.sent_at,e.delivered_at,upper(e.status) status,null::int segment_count,case when e.last_error_code is null then null when upper(e.status) in ('FAILED','BOUNCED','COMPLAINED') then 'DELIVERY_FAILED' else 'NOT_SENT' end failure_category from email_outbox e where e.tenant_id=${tenantId}::uuid and e.created_at>=${p.from.toISOString()}::timestamptz and e.created_at<${p.to.toISOString()}::timestamptz union all select s.id,'SMS'::text,s.template_key,('***'||right(regexp_replace(s.recipient_phone_e164,'\\D','','g'),4)),case when s.form_assignment_id is not null then 'form_assignment' when s.appointment_id is not null then 'appointment' else null end,coalesce(s.form_assignment_id,s.appointment_id),s.created_at,s.sent_at,s.delivered_at,upper(s.status),s.segment_count,case when s.last_error_code is null then null when upper(s.status) in ('FAILED','UNDELIVERED','EXPIRED') then 'DELIVERY_FAILED' else 'NOT_SENT' end from sms_outbox s where s.tenant_id=${tenantId}::uuid and s.created_at>=${p.from.toISOString()}::timestamptz and s.created_at<${p.to.toISOString()}::timestamptz)`;}
  async communications(tenantId:string,ctx:ReportContext,q:CommunicationsReportQuery){const offset=decodeReportCursor(q.cursor);const cte=this.communicationsCte(tenantId,ctx);const where=sql`(${q.channel??null}::text is null or channel=${q.channel??null}) and (${q.template??null}::text is null or category=${q.template??null}) and (${q.status??null}::text is null or status=${q.status??null})`;const sort=order(q.sort,{queued_desc:sql`queued_at desc,id desc`,queued_asc:sql`queued_at asc,id asc`,status_asc:sql`status asc,id asc`});const [sr,rr]=await Promise.all([this.db.execute(sql`${cte} select count(*)::int total,count(*) filter(where channel='EMAIL')::int email,count(*) filter(where channel='SMS')::int sms,count(*) filter(where status='DELIVERED')::int delivered,count(*) filter(where status in ('FAILED','UNDELIVERED','BOUNCED','COMPLAINED','EXPIRED'))::int failed,coalesce(sum(segment_count),0)::int segments from base where ${where}`),this.db.execute(sql`${cte} select * from base where ${where} order by ${sort} limit ${q.limit+1} offset ${offset}`)]);const s=(sr.rows[0]??{}) as any;const paged=reportPagination(rr.rows as any[],q.limit,offset);return{period:reportPeriodMeta(ctx.period),currency:ctx.currency,filters:{channel:q.channel??null,template:q.template??null,status:q.status??null,sort:q.sort},summary:{total:reportNumber(s.total),email:reportNumber(s.email),sms:reportNumber(s.sms),delivered:reportNumber(s.delivered),failed:reportNumber(s.failed),segments:reportNumber(s.segments)},rows:paged.rows.map((r:any)=>({communicationId:r.id,channel:r.channel,category:r.category,maskedRecipient:r.masked_recipient,relatedType:r.related_type,relatedId:r.related_id,queuedAt:reportIso(r.queued_at)!,sentAt:reportIso(r.sent_at),deliveredAt:reportIso(r.delivered_at),status:r.status,segmentCount:r.segment_count==null?null:reportNumber(r.segment_count),failureCategory:r.failure_category})),pagination:paged.pagination,generatedAt:generatedAt()};}
}
