/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false apps/web/worker/env.d.ts` (hash: fb68e3ee492c89746f801e5957b0cdc4)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	API_ORIGIN: "https://api.kasimshah.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
